/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Dev-only tenant UUID → workspace plugin id (guest-surface-host). */
export const DEV_PLUGIN_ID_BY_TENANT_ID: Readonly<Record<string, string>> = Object.freeze({
  "00000000-0000-4000-8000-000000000003": "denali",
  "00000000-0000-4000-8000-000000000004": "urban",
  "00000000-0000-4000-8000-000000000014": "denali",
  "eb29a07b-40bb-4e06-9e35-522cb22dab02": "guest-club",
  "fbdcae8a-2cd8-4c2c-898c-f408bd51321a": "harbor",
});
