/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Dev-only tenant UUID → workspace plugin id (guest-surface-host). */
export const DEV_PLUGIN_ID_BY_TENANT_ID: Readonly<Record<string, string>> = Object.freeze({
  "00000000-0000-4000-8000-000000000003": "denali",
  "00000000-0000-4000-8000-000000000004": "urban",
  "00000000-0000-4000-8000-000000000014": "denali",
  "78951423-370e-4eb8-b5bc-11c643fd775e": "profile-cert",
  "83d7dd00-d961-4fe3-ade9-1aaf0a6b84a5": "cert-club",
  "89205133-892b-4b58-9554-f8afb5634157": "cert-events",
  "eb29a07b-40bb-4e06-9e35-522cb22dab02": "guest-club",
  "fbdcae8a-2cd8-4c2c-898c-f408bd51321a": "harbor",
});
