/**
 * Product-facing copy for `/leader/review` (Phase 16.4).
 */
export const LEADER_REVIEW_COPY = {
  metadata: {
    title: "داشبورد بررسی و تایید درخواست‌ها",
    description: "صف بررسی متقاضیان تور و تایید درخواست‌های ثبت‌نام در سطح ورک‌اسپیس.",
  },
  page: {
    documentTitle: "صف بررسی متقاضیان تور",
    title: "داشبورد بررسی و تایید درخواست‌ها",
    breadcrumbHome: "خانه",
    breadcrumbDashboard: "داشبورد",
    breadcrumbQueue: "صف بررسی متقاضیان",
    description: (pending: number, total: number) =>
      `${pending} در انتظار بررسی · ${total} درخواست در کل تورهای ورک‌اسپیس.`,
    loadingSession: "در حال بارگذاری نشست…",
    signInTitle: "ورود لازم است",
    signInButton: "ورود",
    accessRestrictedTitle: "دسترسی محدود",
    accessRestrictedDescription: "فقط نقش رهبر/مدیر می‌تواند به این داشبورد دسترسی داشته باشد.",
    tenantInvalid: "ورک‌اسپیس شما معتبر نیست. لطفاً دوباره وارد شوید.",
    apiNotConfiguredTitle: "API پیکربندی نشده",
    apiNotConfiguredDescription:
      "این برنامه را روی هاست ورک‌اسپیس (مثلاً ws1-rbac.localhost) با API فعال باز کنید.",
    loadErrorTitle: "بارگذاری درخواست‌ها ناموفق بود",
    loadErrorFallback: "درخواست‌ها بارگذاری نشد. اتصال را بررسی و دوباره تلاش کنید.",
    loadingRows: "در حال بارگذاری درخواست‌ها در همه تورها…",
    exportToast: (count: number) => `${count} ردیف در فایل CSV ذخیره شد.`,
    mutationErrorFallback: "درخواست انجام نشد.",
  },
  filters: {
    queueLabel: "صف",
    queuePending: "فقط در انتظار بررسی",
    queueAll: "همه وضعیت‌ها",
    statusLabel: "وضعیت",
    statusAll: "همه وضعیت‌های بررسی",
    participantLabel: "متقاضی",
    participantPlaceholder: "نام یا تلفن",
    fromLabel: "از تاریخ",
    toLabel: "تا تاریخ",
    exportCsv: "خروجی CSV",
    refresh: "بروزرسانی",
    clearFilters: "پاک کردن فیلترها",
  },
  summary: {
    total: "کل درخواست‌ها",
    pending: "در انتظار بررسی",
    approved: "تایید شده",
    rejectedCancelled: "رد / لغو شده",
  },
  reporting: {
    title: "منابع داده گزارش",
    partial: "نمایش داده ناقص (محدودیت صفحه‌بندی)",
    sourceNote:
      "منبع: GET /api/v2/dashboard/leader-registration-rows · تغییر وضعیت: PATCH /api/v2/registrations/{id}/status · پرداخت: PATCH /api/v2/registrations/{id}/payment",
    partialLoadWarning: "برخی تورها بارگذاری نشدند. «بروزرسانی» را بزنید.",
  },
  table: {
    title: (count: number) => `درخواست‌های در انتظار بررسی (${count} مورد)`,
    emptyTitle: "موردی در این صف نیست",
    emptyDescription: "فیلتر را تغییر دهید یا ورک‌اسپیس تور را باز کنید.",
    colTour: "تور",
    colParticipant: "متقاضی",
    colTransportNotes: "وسیله نقلیه / توضیحات",
    colUpdated: "آخرین بروزرسانی",
    colStatus: "وضعیت",
    colUpdateStatus: "تغییر وضعیت",
    colPayment: "پرداخت",
    colQuickActions: "اقدام سریع",
    colWorkspace: "ورک‌اسپیس",
    tourLink: (idPrefix: string) => `تور · ${idPrefix}…`,
    applyStatus: "اعمال وضعیت",
    savePayment: "ذخیره پرداخت",
    paidAmountPlaceholder: "مبلغ پرداخت‌شده",
    inspect: "جزئیات بیشتر",
    approve: "تایید اولیه (صدور فاکتور)",
    reject: "رد درخواست",
    openWorkspace: "ورک‌اسپیس تور",
  },
  inspection: {
    title: "پنل بررسی جزئیات",
    emptyTitle: "موردی انتخاب نشده",
    emptyDescription: "از جدول «جزئیات بیشتر» را بزنید.",
    loading: "در حال بارگذاری جزئیات…",
    loadErrorTitle: "بارگذاری جزئیات ناموفق بود",
    loadErrorFallback: "درخواست انجام نشد.",
    tour: "تور",
    status: "وضعیت",
    payment: "پرداخت",
    paidAmount: "مبلغ پرداخت‌شده",
    transport: "نحوه حمل‌ونقل",
    entryMode: "کانال ثبت",
    telegram: "تلگرام",
    vehicleSeats: "صندلی خودرو",
    participantNote: "یادداشت متقاضی",
    paymentContext: "زمینه پرداخت",
    reasonContext: "دلیل / زمینه",
    updated: "بروزرسانی",
    fallbackWarning: "نمایش خلاصه ردیف (endpoint جزئیات در دسترس نبود).",
    openWorkspace: "ورک‌اسپیس تور",
    none: "—",
  },
} as const;
