/** Root barrel surface — re-exported from `index.ts` only. */
export {
  assertCanonicalDocument,
  assertCanonicalDocumentRoots,
  assertCanonicalPathSegments,
  CanonicalDocumentValidationError,
  createCanonicalDocument,
  freezeCanonicalDocumentData,
  type CanonicalDocument,
  type CanonicalDocumentValidationErrorCode,
} from "./canonical/canonical-document";
export { assertStablePlainPrototype, readOwnDataProperty } from "./canonical/plain-object-shield";
export {
  parseCanonicalDocumentFromStorage,
  tryParseCanonicalDocumentFromStorage,
  type CanonicalIngressErrorCode,
} from "./ingress/parse-canonical-document";
export {
  parseWorkspacePluginFromStorage,
  tryParseWorkspacePluginFromStorage,
  type ParseWorkspacePluginOptions,
  type WorkspacePluginIngressErrorCode,
} from "./ingress/parse-workspace-plugin";
export {
  IngressSanitizationError,
  WorkspacePluginIngressError,
  WorkspaceThemeValidationError,
  sdkErr,
  sdkOk,
  type IngressSanitizationErrorCode,
  type SdkResult,
  workspaceSdkValidationErrorCode,
  type WorkspacePluginIngressErrorCode as WorkspacePluginRootIngressErrorCode,
  type WorkspaceThemeValidationErrorCode,
} from "./errors";
export {
  createStarterWorkspacePlugin,
  getStarterWorkspacePlugin,
  starterWorkspacePlugin,
  STARTER_THEME_TOKENS_STYLESHEET,
  explainWorkspacePluginRejection,
  isWorkspacePlugin,
  validateWorkspacePlugin,
  isWorkspaceSdkValidationError,
  assertWorkspacePlugin,
  assertWorkspaceThemeContract,
  STARTER_WORKSPACE_PLUGIN_ID,
  DENALI_WORKSPACE_PLUGIN_ID,
  DEFAULT_WORKSPACE_TYPE_BINDINGS,
  resolveWorkspacePluginIdForType,
  STARTER_WORKSPACE_TYPE,
  DENALI_WORKSPACE_TYPE,
  workspaceTypesFromPlugin,
  isWorkspaceTypeId,
  noopWorkspaceValidationHooks,
  WorkspacePluginShapeError,
  type WorkspacePlugin,
  type WorkspacePluginId,
  type WorkspaceTypeBinding,
  type WorkspaceTypeId,
  type WorkspaceLifecycleContract,
  type WorkspaceLifecycleTransition,
  type WorkspaceValidationHooks,
  type WorkspaceViolation,
  type WorkspaceWizardMode,
  type WorkspaceWizardSurface,
  type WorkspaceSdkValidationError,
  type WorkspaceSdkValidationErrorCode,
  type WorkspacePluginValidationErrorCode,
} from "./plugin/index";
export {
  tryValidateTenantTheme,
  validateTenantTheme,
  snapshotWorkspaceTheme,
  getWorkspaceThemePresets,
  workspaceThemePresets,
  WORKSPACE_THEME_CSS_VARIABLE,
  workspaceAccentCssValue,
  normalizeThemeCssKey,
  normalizeTenantCssKey,
  type TenantThemeConfig,
  type WorkspaceThemeContract,
  type SealedTenantTheme,
  type SealedWorkspaceTheme,
  type WorkspaceThemeCssVariable,
  type WorkspaceThemePresetId,
  assertWorkspaceThemeSealed,
  assertTenantThemeSealed,
} from "./theme/index";
export { tryParseTenantAuthContext, type AuthContextErrorCode } from "./auth/validate-auth-context";
export {
  buildTenantAuthz,
  canAccessWorkspaceTheme,
  createTenantAuthz,
  parseTenantAuthContext,
} from "./auth/index";
export type {
  ActorRole,
  MembershipStatus,
  TenantAuthContext,
  TenantAuthz,
  ScopedTenantAuthz,
  CanAccessWorkspaceThemeAuthzParams,
  WorkspaceThemeSubject,
} from "./auth/index";
export {
  getWorkspaceRuleCell,
  type WorkspaceFieldKind,
  type WorkspaceFieldRegistry,
  type WorkspaceFieldRegistryEntry,
  type WorkspaceRuleCell,
  type WorkspaceRuleFieldOverride,
  type WorkspaceRuleSet,
} from "./registry";
