import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/** Repository root (scripts/codegen/workspace-registry → ../../../). */
export const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "../../..");

export const DEFAULT_WORKSPACES_DIR = join(REPO_ROOT, "packages/workspaces");

export const BANNER = `/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */
`;

export const WIZARD_I18N_LOCALES = ["fa", "en"];
