/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspacePlugin } from "@app-tour/workspace-sdk";
import { getDenaliWorkspacePlugin } from "@app-tour/workspace-denali/plugin";
import { getGuestClubWorkspacePlugin } from "@app-tour/workspace-guest-club/plugin";
import { getStarterWorkspacePlugin } from "@app-tour/workspace-starter";
import { getUrbanWorkspacePlugin } from "@app-tour/workspace-urban/plugin";

export function listApiWorkspacePluginsFromManifest(): readonly WorkspacePlugin[] {
  return [
    getDenaliWorkspacePlugin(),
    getGuestClubWorkspacePlugin(),
    getStarterWorkspacePlugin(),
    getUrbanWorkspacePlugin(),
  ];
}
