/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceOutboxPublishedRow } from "./workspace-outbox-row-context";

export type WorkspaceOutboxSideEffectRunner = (
  row: WorkspaceOutboxPublishedRow
) => Promise<void | boolean>;

/** Non–financeEventReaction host side effects only. Finance TourCreated uses the reaction registry. */
export const WORKSPACE_OUTBOX_SIDE_EFFECT_BINDINGS: readonly {
  readonly workspaceTypes: readonly string[];
  readonly eventType: string;
  readonly run: WorkspaceOutboxSideEffectRunner;
}[] = [];

export { registerTourCreatedFinanceSideEffectDeps, runTourCreatedFinanceSideEffect, type TourCreatedFinanceSideEffectRow } from "@app-tour/workspace-denali/host/finance/api-tour-created-adapter";
