/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspacePlugin } from "@app-tour/workspace-sdk";

/** Product trunk plugin ids from workspace.manifest.json (excludes registryOnly fixtures). */
export const API_WORKSPACE_PLUGIN_IDS = [
  "acme",
  "booking-ws2",
  "denali",
  "finance-ws5",
  "guest-club",
  "harbor",
  "starter",
  "urban",
] as const;

export type ApiWorkspacePluginId = (typeof API_WORKSPACE_PLUGIN_IDS)[number];

export function listApiWorkspacePluginIdsFromManifest(): readonly ApiWorkspacePluginId[] {
  return API_WORKSPACE_PLUGIN_IDS;
}

const apiPluginLoadCache = new Map<string, Promise<WorkspacePlugin>>();

export async function loadApiWorkspacePluginByIdFromManifest(
  pluginId: string
): Promise<WorkspacePlugin> {
  const cached = apiPluginLoadCache.get(pluginId);
  if (cached) {
    return cached;
  }
  const load = (async (): Promise<WorkspacePlugin> => {
    switch (pluginId) {
    case "acme": {
      const mod = await import("@app-tour/workspace-acme/plugin");
      return mod.getWorkspacePlugin();
    }
    case "booking-ws2": {
      const mod = await import("@app-tour/workspace-booking-ws2/plugin");
      return mod.getWorkspacePlugin();
    }
    case "denali": {
      const mod = await import("@app-tour/workspace-denali/plugin");
      return mod.getWorkspacePlugin();
    }
    case "finance-ws5": {
      const mod = await import("@app-tour/workspace-finance-ws5/plugin");
      return mod.getWorkspacePlugin();
    }
    case "guest-club": {
      const mod = await import("@app-tour/workspace-guest-club/plugin");
      return mod.getWorkspacePlugin();
    }
    case "harbor": {
      const mod = await import("@app-tour/workspace-harbor/plugin");
      return mod.getWorkspacePlugin();
    }
    case "starter": {
      const mod = await import("@app-tour/workspace-starter");
      return mod.getWorkspacePlugin();
    }
    case "urban": {
      const mod = await import("@app-tour/workspace-urban/plugin");
      return mod.getWorkspacePlugin();
    }
      default:
        throw new Error(`WORKSPACE_PLUGIN_NOT_FOUND:${pluginId}`);
    }
  })();
  apiPluginLoadCache.set(pluginId, load);
  try {
    return await load;
  } catch (error) {
    apiPluginLoadCache.delete(pluginId);
    throw error;
  }
}

/** Warm/admin helper — prefer {@link loadApiWorkspacePluginByIdFromManifest} on request paths. */
export async function listApiWorkspacePluginsFromManifest(): Promise<readonly WorkspacePlugin[]> {
  return Promise.all(
    API_WORKSPACE_PLUGIN_IDS.map((id) => loadApiWorkspacePluginByIdFromManifest(id))
  );
}
