/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceOutboxPublishedRow } from "./workspace-outbox-row-context";
import { runTourCreatedFinanceSideEffect } from "@app-tour/workspace-denali/host/finance/api-tour-created-adapter";

export type WorkspaceOutboxSideEffectRunner = (
  row: WorkspaceOutboxPublishedRow
) => Promise<void | boolean>;

export const WORKSPACE_OUTBOX_SIDE_EFFECT_BINDINGS: readonly {
  readonly workspaceTypes: readonly string[];
  readonly eventType: string;
  readonly run: WorkspaceOutboxSideEffectRunner;
}[] = [
  {
    workspaceTypes: ["denali"],
    eventType: "TourCreated",
    run: runTourCreatedFinanceSideEffect,
  },
];
