/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspacePlugin } from "@app-tour/workspace-sdk";
import { getBookingWs2WorkspacePlugin } from "@app-tour/workspace-booking-ws2/plugin";
import { getDenaliWorkspacePlugin } from "@app-tour/workspace-denali/plugin";
import { getFinanceWs5WorkspacePlugin } from "@app-tour/workspace-finance-ws5/plugin";
import { getGuestClubWorkspacePlugin } from "@app-tour/workspace-guest-club/plugin";
import { getStarterWorkspacePlugin } from "@app-tour/workspace-starter";
import { getUrbanWorkspacePlugin } from "@app-tour/workspace-urban/plugin";

export function listApiWorkspacePluginsFromManifest(): readonly WorkspacePlugin[] {
  return [
    getBookingWs2WorkspacePlugin(),
    getDenaliWorkspacePlugin(),
    getFinanceWs5WorkspacePlugin(),
    getGuestClubWorkspacePlugin(),
    getStarterWorkspacePlugin(),
    getUrbanWorkspacePlugin(),
  ];
}
