/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { normalizeDenaliRegistrationTransportIntake as denali_transport_normalizer } from "@app-tour/workspace-denali/host/http/resolve-denali-registration-transport";

export type RegistrationTransportNormalizerBinding = {
  readonly workspaceType: string;
  readonly normalizeRegistrationTransportIntake: (...args: never[]) => unknown;
};

export const REGISTRATION_TRANSPORT_NORMALIZER_BINDINGS: readonly RegistrationTransportNormalizerBinding[] = [
  {
    workspaceType: "denali",
    normalizeRegistrationTransportIntake: denali_transport_normalizer,
  },
] as const;

export function resolveRegistrationTransportNormalizer(
  workspaceType: string
): RegistrationTransportNormalizerBinding["normalizeRegistrationTransportIntake"] | undefined {
  const binding = REGISTRATION_TRANSPORT_NORMALIZER_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.normalizeRegistrationTransportIntake;
}
