/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export const WORKSPACE_ENGAGEMENT_BINDINGS = [
  {
    workspaceType: "denali",
    defaultModuleEnabledWhenUnset: true as const,
  },
] as const;

const supportedWorkspaceTypes = new Set(
  WORKSPACE_ENGAGEMENT_BINDINGS.map((binding) => binding.workspaceType as string),
);

const defaultEnabledWhenUnset = new Set(
  WORKSPACE_ENGAGEMENT_BINDINGS.filter(
    (binding) =>
      "defaultModuleEnabledWhenUnset" in binding &&
      binding.defaultModuleEnabledWhenUnset === true,
  ).map((binding) => binding.workspaceType as string),
);

export function isEngagementSupportedWorkspace(workspaceType: string): boolean {
  return supportedWorkspaceTypes.has(workspaceType.trim().toLowerCase());
}

export function isEngagementDefaultEnabledWhenModulesUnset(workspaceType: string): boolean {
  return defaultEnabledWhenUnset.has(workspaceType.trim().toLowerCase());
}
