/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { registerWorkspaceIntakePlugin, registerWorkspaceRegistrationFlowPlugin } from "@app-tour/workspace-sdk";
import { registerWorkspaceRegistrationFlowSteps } from "./registration-flow";

/** Intake registrar for "denali" — plugin entry only (no registration-flow UI graph). */
export async function registerWorkspaceIntakeDENALIFromManifest(): Promise<void> {
  const { getDenaliWorkspacePlugin } = await import("@app-tour/workspace-denali/plugin");
  const plugin = getDenaliWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
}

/** Full registrar for "denali" — intake, transport, and registration-flow surfaces. */
export async function registerWorkspacePluginDENALIFromManifest(): Promise<void> {
  const { getDenaliWorkspacePlugin } = await import("@app-tour/workspace-denali/plugin");
  const plugin = getDenaliWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }

  const { registerDenaliCatalogRegistrationTransportInitializer } = await import("@app-tour/workspace-denali/host/catalog-registration-flow");
  registerDenaliCatalogRegistrationTransportInitializer();

  const { denaliCatalogRegistrationFlowSurface } = await import("@app-tour/workspace-denali/host/catalog-registration-flow");
  const { denaliRegistrationFlowSteps } = await import("@app-tour/workspace-denali/host/catalog-registration-flow/react");
  registerWorkspaceRegistrationFlowPlugin({
    id: "denali",
    catalogRegistrationFlow: denaliCatalogRegistrationFlowSurface,
  });
  registerWorkspaceRegistrationFlowSteps("denali", denaliRegistrationFlowSteps);
}
