/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { registerWorkspaceIntakePlugin, registerWorkspaceRegistrationFlowPlugin } from "@app-tour/workspace-sdk";
import { registerWorkspaceRegistrationFlowSteps } from "./registration-flow";

/** Intake registrar for "urban" — plugin entry only (no registration-flow UI graph). */
export async function registerWorkspaceIntakeURBANFromManifest(): Promise<void> {
  const { getUrbanWorkspacePlugin } = await import("@app-tour/workspace-urban/plugin");
  const plugin = getUrbanWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
}

/** Full registrar for "urban" — intake, transport, and registration-flow surfaces. */
export async function registerWorkspacePluginURBANFromManifest(): Promise<void> {
  const { getUrbanWorkspacePlugin } = await import("@app-tour/workspace-urban/plugin");
  const plugin = getUrbanWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }

  const { urbanCatalogRegistrationFlowSurface } = await import("@app-tour/workspace-urban/host/catalog-registration-flow");
  const { UrbanIntakeStep, UrbanDoneStep } = await import("@app-tour/workspace-urban/host/catalog-registration-flow/react");
  const { CatalogRegistrationOtpStep, CatalogRegistrationPhoneStep, CatalogRegistrationProfileStep } = await import("@app-tour/catalog-registration-flow-ui/react");
  registerWorkspaceRegistrationFlowPlugin({
    id: "urban",
    catalogRegistrationFlow: urbanCatalogRegistrationFlowSurface,
  });
  registerWorkspaceRegistrationFlowSteps("urban", {
    phone: CatalogRegistrationPhoneStep,
    otp: CatalogRegistrationOtpStep,
    profile: CatalogRegistrationProfileStep,
    intake: UrbanIntakeStep,
    done: UrbanDoneStep,
  });
}
