/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 *
 * P3.2.b — IDs + revision only. Product registrars live under apps/portal/src/bootstrap/.
 */

/** Sorted trunk plugin ids — cache bust when codegen regen changes membership. */
export const WORKSPACE_PLUGIN_REGISTER_REVISION = "denali,guest-club,harbor,starter,urban";

export const WORKSPACE_PLUGIN_REGISTER_IDS = Object.freeze([
  "denali",
  "guest-club",
  "harbor",
  "starter",
  "urban",
]) as readonly string[];
