/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { registerWorkspaceIntakePlugin } from "@app-tour/workspace-sdk";
import { getDenaliWorkspacePlugin } from "@app-tour/workspace-denali/plugin";
import { getGuestClubWorkspacePlugin } from "@app-tour/workspace-guest-club/plugin";
import { getStarterWorkspacePlugin } from "@app-tour/workspace-starter";
import { getUrbanWorkspacePlugin } from "@app-tour/workspace-urban/plugin";

export function registerWorkspaceIntakePluginsFromManifest(): void {
  for (const plugin of [
    getDenaliWorkspacePlugin(),
    getGuestClubWorkspacePlugin(),
    getStarterWorkspacePlugin(),
    getUrbanWorkspacePlugin(),
  ]) {
    if (plugin.catalogIntake === undefined) {
      continue;
    }
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
}
