/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Sorted trunk plugin ids — cache bust when codegen regen changes membership. */
export const WORKSPACE_PLUGIN_REGISTER_REVISION = "denali,guest-club,starter,urban";

export const WORKSPACE_PLUGIN_REGISTER_IDS = Object.freeze([
  "denali",
  "guest-club",
  "starter",
  "urban",
]) as readonly string[];

/** Dynamic per-plugin full registrar — no static workspace imports in this module. */
export async function invokeWorkspacePluginRegister(pluginId: string): Promise<void> {
  switch (pluginId) {
    case "denali": {
      const mod = await import("@app-tour/workspace-plugin-host/register-denali");
      await mod.registerWorkspacePluginDENALIFromManifest();
      return;
    }
    case "guest-club": {
      const mod = await import("@app-tour/workspace-plugin-host/register-guest-club");
      await mod.registerWorkspacePluginGUEST_CLUBFromManifest();
      return;
    }
    case "starter": {
      const mod = await import("@app-tour/workspace-plugin-host/register-starter");
      await mod.registerWorkspacePluginSTARTERFromManifest();
      return;
    }
    case "urban": {
      const mod = await import("@app-tour/workspace-plugin-host/register-urban");
      await mod.registerWorkspacePluginURBANFromManifest();
      return;
    }
    default:
      throw new Error(`WORKSPACE_PLUGIN_REGISTER_UNKNOWN:${pluginId}`);
  }
}

/** Dynamic per-plugin intake registrar — plugin entry only (API dispatch path). */
export async function invokeWorkspaceIntakeRegister(pluginId: string): Promise<void> {
  switch (pluginId) {
    case "denali": {
      const mod = await import("@app-tour/workspace-plugin-host/register-denali");
      await mod.registerWorkspaceIntakeDENALIFromManifest();
      return;
    }
    case "guest-club": {
      const mod = await import("@app-tour/workspace-plugin-host/register-guest-club");
      await mod.registerWorkspaceIntakeGUEST_CLUBFromManifest();
      return;
    }
    case "starter": {
      const mod = await import("@app-tour/workspace-plugin-host/register-starter");
      await mod.registerWorkspaceIntakeSTARTERFromManifest();
      return;
    }
    case "urban": {
      const mod = await import("@app-tour/workspace-plugin-host/register-urban");
      await mod.registerWorkspaceIntakeURBANFromManifest();
      return;
    }
    default:
      throw new Error(`WORKSPACE_PLUGIN_REGISTER_UNKNOWN:${pluginId}`);
  }
}
