/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { registerWorkspaceRegistrationFlowPlugin } from "@app-tour/workspace-sdk";
import { CatalogRegistrationOtpStep, CatalogRegistrationPhoneStep, CatalogRegistrationProfileStep } from "@app-tour/catalog-registration-flow-ui/react";
import { GuestClubIntakeStep, GuestClubDoneStep } from "@app-tour/workspace-guest-club/catalog-registration-flow/react";
import { UrbanIntakeStep, UrbanDoneStep } from "@app-tour/workspace-urban/catalog-registration-flow/react";
import { denaliCatalogRegistrationFlowSurface } from "@app-tour/workspace-denali/catalog-registration-flow";
import { denaliRegistrationFlowSteps } from "@app-tour/workspace-denali/catalog-registration-flow/react";
import { guestClubCatalogRegistrationFlowSurface } from "@app-tour/workspace-guest-club/catalog-registration-flow";
import { urbanCatalogRegistrationFlowSurface } from "@app-tour/workspace-urban/catalog-registration-flow";

import { registerWorkspaceRegistrationFlowSteps } from "./registration-flow";

export function registerWorkspaceRegistrationFlowPluginsFromManifest(): void {
  registerWorkspaceRegistrationFlowPlugin({
    id: "denali",
    catalogRegistrationFlow: denaliCatalogRegistrationFlowSurface,
  });
  registerWorkspaceRegistrationFlowSteps("denali", denaliRegistrationFlowSteps);

  registerWorkspaceRegistrationFlowPlugin({
    id: "guest-club",
    catalogRegistrationFlow: guestClubCatalogRegistrationFlowSurface,
  });
  registerWorkspaceRegistrationFlowSteps("guest-club", {
    phone: CatalogRegistrationPhoneStep,
    otp: CatalogRegistrationOtpStep,
    profile: CatalogRegistrationProfileStep,
    intake: GuestClubIntakeStep,
    done: GuestClubDoneStep,
  });

  registerWorkspaceRegistrationFlowPlugin({
    id: "urban",
    catalogRegistrationFlow: urbanCatalogRegistrationFlowSurface,
  });
  registerWorkspaceRegistrationFlowSteps("urban", {
    phone: CatalogRegistrationPhoneStep,
    otp: CatalogRegistrationOtpStep,
    profile: CatalogRegistrationProfileStep,
    intake: UrbanIntakeStep,
    done: UrbanDoneStep,
  });
}
