/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { registerDenaliCatalogRegistrationTransportInitializer } from "@app-tour/workspace-denali/host/catalog/registration-flow/register-transport-initializer";

export function registerWorkspaceRegistrationTransportInitializersFromManifest(): void {
  registerDenaliCatalogRegistrationTransportInitializer();
}
