/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { registerCertClubCatalogRegistrationTransportInitializer } from "@app-tour/workspace-cert-club/host/transport/register-transport-initializer";
import { registerDenaliCatalogRegistrationTransportInitializer } from "@app-tour/workspace-denali/catalog/registration-flow/register-transport-initializer";

export function registerWorkspaceRegistrationTransportInitializersFromManifest(): void {
  registerCertClubCatalogRegistrationTransportInitializer();
  registerDenaliCatalogRegistrationTransportInitializer();
}
