/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export const WORKSPACE_TICKETING_BINDINGS = [
  {
    workspaceType: "denali",
  },
] as const;

const supportedWorkspaceTypes = new Set(
  WORKSPACE_TICKETING_BINDINGS.map((binding) => binding.workspaceType as string),
);

const defaultEnabledWhenUnset = new Set(
  WORKSPACE_TICKETING_BINDINGS.filter(
    (binding) => "defaultModuleEnabledWhenUnset" in binding && binding.defaultModuleEnabledWhenUnset === true,
  ).map((binding) => binding.workspaceType as string),
);

export function isTicketingSupportedWorkspace(workspaceType: string): boolean {
  return supportedWorkspaceTypes.has(workspaceType.trim().toLowerCase());
}

export function isTicketingDefaultEnabledWhenModulesUnset(workspaceType: string): boolean {
  return defaultEnabledWhenUnset.has(workspaceType.trim().toLowerCase());
}
