/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { URBAN_WORKSPACE_TYPE } from "@app-tour/workspace-urban";
import { readUrbanTourPublishStatusFromCanonical, detectUrbanTourPublishTransition } from "@app-tour/workspace-urban/tours";

export const WORKSPACE_CANONICAL_TOUR_BINDINGS = [
  {
    workspaceType: URBAN_WORKSPACE_TYPE,
    readPublishStatusFromCanonical: readUrbanTourPublishStatusFromCanonical,
    detectPublishTransition: detectUrbanTourPublishTransition,
  },
] as const;
