/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";
import { HARBOR_WORKSPACE_TYPE } from "@app-tour/workspace-harbor";
import { URBAN_WORKSPACE_TYPE } from "@app-tour/workspace-urban";

export const WORKSPACE_PUBLISH_LABEL_MAPPINGS = [
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    mapping: {
    publishedLabels: ["active"],
    notPublishedLabels: ["draft"],
    },
  },
  {
    workspaceType: HARBOR_WORKSPACE_TYPE,
    mapping: {
    publishedLabels: ["published"],
    notPublishedLabels: ["draft"],
    },
  },
  {
    workspaceType: URBAN_WORKSPACE_TYPE,
    mapping: {
    publishedLabels: ["published"],
    notPublishedLabels: ["draft"],
    archiveCapability: true as const,
    optionalArchiveLabels: ["archived"],
    },
  },
] as const;
