/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";
import { readDenaliTourPublishStatusFromCanonical, detectDenaliTourPublishTransition } from "@app-tour/workspace-denali/host/tours";
import { migrateDenaliCanonical, LEGACY_TRIP_DETAILS_SOT_ROOT, DENALI_CURRENT_CANONICAL_SCHEMA_VERSION, DENALI_LEGACY_TRIP_DETAILS_SCHEMA_VERSION, wrapLegacyTripDetailsForMigration } from "@app-tour/workspace-denali/host/acl";
import { DENALI_FORM_PROFILE_GHOST_PATHS } from "@app-tour/workspace-denali/host/composites/wizard-composite-registry-surface";
import { URBAN_WORKSPACE_TYPE } from "@app-tour/workspace-urban";
import { readUrbanTourPublishStatusFromCanonical, detectUrbanTourPublishTransition } from "@app-tour/workspace-urban/host/tours";

export const WORKSPACE_CANONICAL_TOUR_BINDINGS = [
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    readPublishStatusFromCanonical: readDenaliTourPublishStatusFromCanonical,
    detectPublishTransition: detectDenaliTourPublishTransition,
    migrateCanonical: migrateDenaliCanonical,
    legacySoTRoot: LEGACY_TRIP_DETAILS_SOT_ROOT,
    currentSchemaVersion: DENALI_CURRENT_CANONICAL_SCHEMA_VERSION,
    legacySchemaVersion: DENALI_LEGACY_TRIP_DETAILS_SCHEMA_VERSION,
    wrapLegacyCanonical: wrapLegacyTripDetailsForMigration,
    formProfileGhostPaths: DENALI_FORM_PROFILE_GHOST_PATHS,
    validationSyncOnly: true as const,
    catalogRefEnrichment: true as const,
  },
  {
    workspaceType: URBAN_WORKSPACE_TYPE,
    readPublishStatusFromCanonical: readUrbanTourPublishStatusFromCanonical,
    detectPublishTransition: detectUrbanTourPublishTransition,
  },
] as const;
