/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { isDenaliTourPublished } from "@app-tour/workspace-denali/host/catalog/denali-publish-status";
import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";
import { isHarborTourPublished } from "@app-tour/workspace-harbor/host/catalog";
import { HARBOR_WORKSPACE_TYPE } from "@app-tour/workspace-harbor";
import { isUrbanTourPublished } from "@app-tour/workspace-urban/host/http/publish-status";
import { URBAN_WORKSPACE_TYPE } from "@app-tour/workspace-urban";

export const WORKSPACE_PUBLISH_VISIBILITY_BINDINGS = [
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    isTourPubliclyVisible: isDenaliTourPublished,
  },
  {
    workspaceType: HARBOR_WORKSPACE_TYPE,
    isTourPubliclyVisible: isHarborTourPublished,
  },
  {
    workspaceType: URBAN_WORKSPACE_TYPE,
    isTourPubliclyVisible: isUrbanTourPublished,
  },
] as const;
