/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";
import { resolveDenaliCatalogRefAllowlists } from "../canonical/resolve-denali-catalog-ref-allowlists.ts";
import type { CatalogRefAllowlists } from "../canonical/assert-catalog-ref-integrity.ts";

export const WORKSPACE_CATALOG_REF_ALLOWLIST_RESOLVERS = [
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    resolve: resolveDenaliCatalogRefAllowlists,
  },
] as const;

export async function resolveCatalogRefAllowlistsForWorkspaceBinding(
  workspaceType: string,
  tenantId: string
): Promise<CatalogRefAllowlists | undefined> {
  const binding = WORKSPACE_CATALOG_REF_ALLOWLIST_RESOLVERS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  if (binding === undefined) {
    return undefined;
  }
  return binding.resolve(tenantId);
}
