/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali/plugin";

export const WORKSPACE_INTEGRATION_CAPABILITY_BINDINGS = [
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    providerId: "telegram",
    tourPublishedPolicyDriftCheck: true,
    tourPublishedExposureRemap: true,
    deprecatedEventTypes: Object.freeze({ TourCreated: "TourPublished" }),
    deliveryReferenceDisplayFieldIds: ["denali.destination"],
  },
] as const;

function normalizeWorkspaceType(workspaceType: string | null): string | null {
  if (workspaceType === null) {
    return null;
  }
  const trimmed = workspaceType.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function resolveBinding(workspaceType: string | null, providerId: string) {
  const normalizedWorkspaceType = normalizeWorkspaceType(workspaceType);
  if (normalizedWorkspaceType === null) {
    return undefined;
  }
  return WORKSPACE_INTEGRATION_CAPABILITY_BINDINGS.find(
    (entry) => entry.workspaceType === normalizedWorkspaceType && entry.providerId === providerId
  );
}

export function resolveIntegrationDeprecatedEventSupersededBy(
  workspaceType: string | null,
  providerId: string,
  eventType: string
): string | undefined {
  const binding = resolveBinding(workspaceType, providerId);
  const deprecated = binding?.deprecatedEventTypes as Readonly<Record<string, string>> | undefined;
  return deprecated?.[eventType];
}

export function requiresTourPublishedPolicyDriftCheck(
  workspaceType: string | null,
  providerId: string
): boolean {
  const binding = resolveBinding(workspaceType, providerId);
  return binding?.tourPublishedPolicyDriftCheck === true;
}

export function listTourPublishedPolicyDriftCheckTargets(): readonly {
  readonly workspaceType: string;
  readonly providerId: string;
}[] {
  return WORKSPACE_INTEGRATION_CAPABILITY_BINDINGS.filter(
    (entry) => entry.tourPublishedPolicyDriftCheck === true
  ).map((entry) => ({
    workspaceType: entry.workspaceType,
    providerId: entry.providerId,
  }));
}

export function supportsTourPublishedExposureRemap(
  workspaceType: string | null,
  surface: string
): boolean {
  const normalizedWorkspaceType = normalizeWorkspaceType(workspaceType);
  if (normalizedWorkspaceType === null) {
    return false;
  }
  return WORKSPACE_INTEGRATION_CAPABILITY_BINDINGS.some(
    (entry) =>
      entry.workspaceType === normalizedWorkspaceType &&
      entry.tourPublishedExposureRemap === true &&
      entry.providerId === surface
  );
}

export function listTourPublishedExposureRemapTargets(): readonly {
  readonly workspaceType: string;
  readonly providerId: string;
}[] {
  return WORKSPACE_INTEGRATION_CAPABILITY_BINDINGS.filter(
    (entry) => entry.tourPublishedExposureRemap === true
  ).map((entry) => ({
    workspaceType: entry.workspaceType,
    providerId: entry.providerId,
  }));
}

export function supportsDeliveryReferenceDisplay(
  workspaceType: string | null,
  providerId: string
): boolean {
  const normalizedWorkspaceType = normalizeWorkspaceType(workspaceType);
  if (normalizedWorkspaceType === null) {
    return false;
  }
  return WORKSPACE_INTEGRATION_CAPABILITY_BINDINGS.some(
    (entry) =>
      entry.workspaceType === normalizedWorkspaceType &&
      entry.providerId === providerId &&
      Array.isArray(entry.deliveryReferenceDisplayFieldIds) &&
      entry.deliveryReferenceDisplayFieldIds.length > 0
  );
}

export function listDeliveryReferenceDisplayFieldIds(
  workspaceType: string | null,
  providerId: string
): readonly string[] {
  const normalizedWorkspaceType = normalizeWorkspaceType(workspaceType);
  if (normalizedWorkspaceType === null) {
    return [];
  }
  const binding = WORKSPACE_INTEGRATION_CAPABILITY_BINDINGS.find(
    (entry) => entry.workspaceType === normalizedWorkspaceType && entry.providerId === providerId
  );
  return binding?.deliveryReferenceDisplayFieldIds ?? [];
}
