/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export const WORKSPACE_MARKETING_PAGES_BINDINGS = [
  {
    workspaceType: "denali",
    allowedPageKeys: Object.freeze(["home-hero"]),
    defaultModuleEnabledWhenUnset: true,
  },
] as const;

const bindingsByWorkspace = new Map(
  WORKSPACE_MARKETING_PAGES_BINDINGS.map((binding) => [binding.workspaceType as string, binding]),
);

const defaultEnabledWhenUnset = new Set(
  WORKSPACE_MARKETING_PAGES_BINDINGS.filter(
    (binding) => binding.defaultModuleEnabledWhenUnset === true,
  ).map((binding) => binding.workspaceType as string),
);

export function isMarketingPagesSupportedWorkspace(workspaceType: string): boolean {
  return bindingsByWorkspace.has(workspaceType.trim().toLowerCase());
}

export function resolveMarketingPagesAllowedKeys(workspaceType: string): readonly string[] {
  const binding = bindingsByWorkspace.get(workspaceType.trim().toLowerCase());
  return binding?.allowedPageKeys ?? [];
}

export function isMarketingPagesDefaultEnabledWhenModulesUnset(workspaceType: string): boolean {
  return defaultEnabledWhenUnset.has(workspaceType.trim().toLowerCase());
}
