/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 * Location: packages/guest-workspace-runtime (P5.3) — product dynamic imports stay package-owned.
 */

import {
  registerWorkspaceIntakePlugin,
  registerWorkspaceMemberPortalRenderers,
  registerWorkspaceRegistrationFlowPlugin,
} from "@app-tour/workspace-sdk";
import { registerWorkspaceRegistrationFlowSteps } from "@app-tour/workspace-plugin-host/registration-flow";

/** Intake registrar for "denali" — plugin entry only (no registration-flow UI graph). */
export async function registerWorkspaceIntakeDENALIFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-denali/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);
}

/** Full registrar for "denali" — intake, transport, and registration-flow surfaces. */
export async function registerWorkspacePluginDENALIFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-denali/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);
  const { registerDenaliCatalogRegistrationTransportInitializer } =
    await import("@app-tour/workspace-denali/host/catalog-registration-flow");
  registerDenaliCatalogRegistrationTransportInitializer();

  const { denaliCatalogRegistrationFlowSurface } =
    await import("@app-tour/workspace-denali/host/catalog-registration-flow");
  const { denaliRegistrationFlowSteps } =
    await import("@app-tour/workspace-denali/host/catalog-registration-flow/react");
  registerWorkspaceRegistrationFlowPlugin({
    id: "denali",
    catalogRegistrationFlow: denaliCatalogRegistrationFlowSurface,
  });
  registerWorkspaceRegistrationFlowSteps("denali", denaliRegistrationFlowSteps);
}
