/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 * Location: packages/guest-workspace-runtime (P5.3) — product dynamic imports stay package-owned.
 */

import {
  registerWorkspaceIntakePlugin,
  registerWorkspaceMemberPortalRenderers,
  registerWorkspaceRegistrationFlowPlugin,
} from "@app-tour/workspace-sdk";
import { registerWorkspaceRegistrationFlowSteps } from "@app-tour/workspace-plugin-host/registration-flow";

/** Intake registrar for "cert-club" — plugin entry only (no registration-flow UI graph). */
export async function registerWorkspaceIntakeCERT_CLUBFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-cert-club/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);
}

/** Full registrar for "cert-club" — intake, transport, and registration-flow surfaces. */
export async function registerWorkspacePluginCERT_CLUBFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-cert-club/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);
  const { registerCertClubCatalogRegistrationTransportInitializer } =
    await import("@app-tour/workspace-cert-club/host/transport/register-transport-initializer");
  registerCertClubCatalogRegistrationTransportInitializer();

  const { certClubCatalogRegistrationFlowSurface } =
    await import("@app-tour/workspace-cert-club/host/catalog-registration-flow");
  const { CertClubIntakeStep, CertClubDoneStep } =
    await import("@app-tour/workspace-cert-club/host/catalog-registration-flow/react");
  const {
    CatalogRegistrationOtpStep,
    CatalogRegistrationPhoneStep,
    CatalogRegistrationProfileStep,
  } = await import("@app-tour/catalog-registration-flow-ui/react");
  registerWorkspaceRegistrationFlowPlugin({
    id: "cert-club",
    catalogRegistrationFlow: certClubCatalogRegistrationFlowSurface,
  });
  registerWorkspaceRegistrationFlowSteps("cert-club", {
    phone: CatalogRegistrationPhoneStep,
    otp: CatalogRegistrationOtpStep,
    profile: CatalogRegistrationProfileStep,
    intake: CertClubIntakeStep,
    done: CertClubDoneStep,
  });
}
