/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 * Location: packages/guest-workspace-runtime (P5.3) — product dynamic imports stay package-owned.
 */

import {
  registerWorkspaceIntakePlugin,
  registerWorkspaceMemberPortalRenderers,
} from "@app-tour/workspace-sdk";

/** Intake registrar for "alpine" — plugin entry only (no registration-flow UI graph). */
export async function registerWorkspaceIntakeALPINEFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-alpine/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);
}

/** Full registrar for "alpine" — intake, transport, and registration-flow surfaces. */
export async function registerWorkspacePluginALPINEFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-alpine/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);
}
