/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 * Location: packages/guest-workspace-runtime (P5.3) — product dynamic imports stay package-owned.
 */

import { registerWorkspaceIntakePlugin, registerWorkspaceRegistrationFlowPlugin } from "@app-tour/workspace-sdk";
import { registerWorkspaceRegistrationFlowSteps } from "@app-tour/workspace-plugin-host/registration-flow";

/** Intake registrar for "guest-club" — plugin entry only (no registration-flow UI graph). */
export async function registerWorkspaceIntakeGUEST_CLUBFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-guest-club/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
}

/** Full registrar for "guest-club" — intake, transport, and registration-flow surfaces. */
export async function registerWorkspacePluginGUEST_CLUBFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-guest-club/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  const { guestClubCatalogRegistrationFlowSurface } = await import("@app-tour/workspace-guest-club/host/catalog-registration-flow");
  const { GuestClubIntakeStep, GuestClubDoneStep } = await import("@app-tour/workspace-guest-club/host/catalog-registration-flow/react");
  const { CatalogRegistrationOtpStep, CatalogRegistrationPhoneStep, CatalogRegistrationProfileStep } = await import("@app-tour/catalog-registration-flow-ui/react");
  registerWorkspaceRegistrationFlowPlugin({
    id: "guest-club",
    catalogRegistrationFlow: guestClubCatalogRegistrationFlowSurface,
  });
  registerWorkspaceRegistrationFlowSteps("guest-club", {
    phone: CatalogRegistrationPhoneStep,
    otp: CatalogRegistrationOtpStep,
    profile: CatalogRegistrationProfileStep,
    intake: GuestClubIntakeStep,
    done: GuestClubDoneStep,
  });
}
