/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 * Location: packages/guest-workspace-runtime (P5.3) — product dynamic imports stay package-owned.
 */

import { registerWorkspaceIntakePlugin, registerWorkspaceRegistrationFlowPlugin } from "@app-tour/workspace-sdk";
import { registerWorkspaceRegistrationFlowSteps } from "@app-tour/workspace-plugin-host/registration-flow";

/** Intake registrar for "harbor" — plugin entry only (no registration-flow UI graph). */
export async function registerWorkspaceIntakeHARBORFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-harbor/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
}

/** Full registrar for "harbor" — intake, transport, and registration-flow surfaces. */
export async function registerWorkspacePluginHARBORFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-harbor/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  const { harborCatalogRegistrationFlowSurface } = await import("@app-tour/workspace-harbor/host/catalog-registration-flow");
  const { HarborIntakeStep, HarborDoneStep } = await import("@app-tour/workspace-harbor/host/catalog-registration-flow/react");
  const { CatalogRegistrationOtpStep, CatalogRegistrationPhoneStep, CatalogRegistrationProfileStep } = await import("@app-tour/catalog-registration-flow-ui/react");
  registerWorkspaceRegistrationFlowPlugin({
    id: "harbor",
    catalogRegistrationFlow: harborCatalogRegistrationFlowSurface,
  });
  registerWorkspaceRegistrationFlowSteps("harbor", {
    phone: CatalogRegistrationPhoneStep,
    otp: CatalogRegistrationOtpStep,
    profile: CatalogRegistrationProfileStep,
    intake: HarborIntakeStep,
    done: HarborDoneStep,
  });
}
