/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 * Location: packages/guest-workspace-runtime (P5.3) — product dynamic imports stay package-owned.
 */

import { registerWorkspaceIntakePlugin } from "@app-tour/workspace-sdk";

/** Intake registrar for "starter" — plugin entry only (no registration-flow UI graph). */
export async function registerWorkspaceIntakeSTARTERFromManifest(): Promise<void> {
  const { getStarterWorkspacePlugin } = await import("@app-tour/workspace-starter");
  const plugin = getStarterWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
}

/** Full registrar for "starter" — intake, transport, and registration-flow surfaces. */
export async function registerWorkspacePluginSTARTERFromManifest(): Promise<void> {
  const { getStarterWorkspacePlugin } = await import("@app-tour/workspace-starter");
  const plugin = getStarterWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
}
