/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 * Location: packages/guest-workspace-runtime (P5.3) — product dynamic imports stay package-owned.
 */

import { registerWorkspaceIntakePlugin, registerWorkspaceMemberPortalRenderers, registerWorkspaceRegistrationFlowPlugin } from "@app-tour/workspace-sdk";
import { registerWorkspaceRegistrationFlowSteps } from "@app-tour/workspace-plugin-host/registration-flow";

/** Intake registrar for "urban" — plugin entry only (no registration-flow UI graph). */
export async function registerWorkspaceIntakeURBANFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-urban/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);
}

/** Full registrar for "urban" — intake, transport, and registration-flow surfaces. */
export async function registerWorkspacePluginURBANFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-urban/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);
  const { urbanCatalogRegistrationFlowSurface } = await import("@app-tour/workspace-urban/host/catalog-registration-flow");
  const { UrbanIntakeStep, UrbanDoneStep } = await import("@app-tour/workspace-urban/host/catalog-registration-flow/react");
  const { CatalogRegistrationOtpStep, CatalogRegistrationPhoneStep, CatalogRegistrationProfileStep } = await import("@app-tour/catalog-registration-flow-ui/react");
  registerWorkspaceRegistrationFlowPlugin({
    id: "urban",
    catalogRegistrationFlow: urbanCatalogRegistrationFlowSurface,
  });
  registerWorkspaceRegistrationFlowSteps("urban", {
    phone: CatalogRegistrationPhoneStep,
    otp: CatalogRegistrationOtpStep,
    profile: CatalogRegistrationProfileStep,
    intake: UrbanIntakeStep,
    done: UrbanDoneStep,
  });
}
