/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 * Location: packages/guest-workspace-runtime (P5.3) — product dynamic imports stay package-owned.
 */

import {
  registerWorkspaceIntakePlugin,
  registerWorkspaceMemberPortalRenderers,
  registerWorkspaceRegistrationFlowPlugin,
} from "@app-tour/workspace-sdk";
import { registerWorkspaceRegistrationFlowSteps } from "@app-tour/workspace-plugin-host/registration-flow";

/** Intake registrar for "cert-events" — plugin entry only (no registration-flow UI graph). */
export async function registerWorkspaceIntakeCERT_EVENTSFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-cert-events/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);
}

/** Full registrar for "cert-events" — intake, transport, and registration-flow surfaces. */
export async function registerWorkspacePluginCERT_EVENTSFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-cert-events/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);
  const { certEventsCatalogRegistrationFlowSurface } =
    await import("@app-tour/workspace-cert-events/host/catalog-registration-flow");
  const { CertEventsIntakeStep, CertEventsDoneStep } =
    await import("@app-tour/workspace-cert-events/host/catalog-registration-flow/react");
  const {
    CatalogRegistrationOtpStep,
    CatalogRegistrationPhoneStep,
    CatalogRegistrationProfileStep,
  } = await import("@app-tour/catalog-registration-flow-ui/react");
  registerWorkspaceRegistrationFlowPlugin({
    id: "cert-events",
    catalogRegistrationFlow: certEventsCatalogRegistrationFlowSurface,
  });
  registerWorkspaceRegistrationFlowSteps("cert-events", {
    phone: CatalogRegistrationPhoneStep,
    otp: CatalogRegistrationOtpStep,
    profile: CatalogRegistrationProfileStep,
    intake: CertEventsIntakeStep,
    done: CertEventsDoneStep,
  });
}
