/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 * Location: packages/guest-workspace-runtime (P5.3) — product dynamic imports stay package-owned.
 */

import {
  registerWorkspaceIntakePlugin,
  registerWorkspaceMemberPortalRenderers,
  registerWorkspaceRegistrationFlowPlugin,
} from "@app-tour/workspace-sdk";
import { registerWorkspaceRegistrationFlowSteps } from "@app-tour/workspace-plugin-host/registration-flow";

/** Intake registrar for "profile-cert" — plugin entry only (no registration-flow UI graph). */
export async function registerWorkspaceIntakePROFILE_CERTFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-profile-cert/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);
}

/** Full registrar for "profile-cert" — intake, transport, and registration-flow surfaces. */
export async function registerWorkspacePluginPROFILE_CERTFromManifest(): Promise<void> {
  const { getWorkspacePlugin } = await import("@app-tour/workspace-profile-cert/plugin");
  const plugin = getWorkspacePlugin();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);
  const { profileCertCatalogRegistrationFlowSurface } =
    await import("@app-tour/workspace-profile-cert/host/catalog-registration-flow");
  const { ProfileCertIntakeStep, ProfileCertDoneStep } =
    await import("@app-tour/workspace-profile-cert/host/catalog-registration-flow/react");
  const {
    CatalogRegistrationOtpStep,
    CatalogRegistrationPhoneStep,
    CatalogRegistrationProfileStep,
  } = await import("@app-tour/catalog-registration-flow-ui/react");
  registerWorkspaceRegistrationFlowPlugin({
    id: "profile-cert",
    catalogRegistrationFlow: profileCertCatalogRegistrationFlowSurface,
  });
  registerWorkspaceRegistrationFlowSteps("profile-cert", {
    phone: CatalogRegistrationPhoneStep,
    otp: CatalogRegistrationOtpStep,
    profile: CatalogRegistrationProfileStep,
    intake: ProfileCertIntakeStep,
    done: ProfileCertDoneStep,
  });
}
