/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */
/// <reference path="./workspace-theme-css.d.ts" />


/** Starter workspace owns the default marketing L3 skin (Phase D.3). */
export const WORKSPACE_GUEST_MARKETING_DEFAULT_SKIN =
  "@app-tour/workspace-starter/theme/starter-marketing.css" as const;

/** Manifest paths per workspace plugin (documentation / guards). */
export const WORKSPACE_GUEST_MARKETING_THEME_REGISTRY = Object.freeze({
  "cert-club": Object.freeze(["theme/marketing.css"]),
  "cert-events": Object.freeze(["theme/marketing.css"]),
  "denali": Object.freeze(["theme/denali-marketing.css"]),
  "guest-club": Object.freeze(["theme/marketing/marketing.css"]),
  "profile-cert": Object.freeze(["theme/marketing.css"]),
  "urban": Object.freeze(["theme/urban-marketing.css"]),
}) as Readonly<Record<string, readonly string[]>>;

/** Load workspace skin CSS for the active plugin only (dynamic import). */
export async function importGuestMarketingThemeForPlugin(pluginId: string): Promise<void> {
  await import("@app-tour/workspace-starter/theme/starter-marketing.css");
  switch (pluginId) {
    case "cert-club":
      await import("@app-tour/workspace-cert-club/theme/marketing.css");
      return;

    case "cert-events":
      await import("@app-tour/workspace-cert-events/theme/marketing.css");
      return;

    case "denali":
      await import("@app-tour/workspace-denali/theme/denali-marketing.css");
      return;

    case "guest-club":
      await import("@app-tour/workspace-guest-club/theme/marketing/marketing.css");
      return;

    case "profile-cert":
      await import("@app-tour/workspace-profile-cert/theme/marketing.css");
      return;

    case "urban":
      await import("@app-tour/workspace-urban/theme/urban-marketing.css");
      return;
    default:
      return;
  }
}
