/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { MarketingCatalogSurface } from "./marketing-catalog-surface-types";

/** Manifest plugin ids with marketingCatalog — sync id check, no product imports. */
const MARKETING_CATALOG_PLUGIN_IDS = new Set<string>([
  "denali"
]);

export function hasMarketingCatalogSurface(pluginId: string): boolean {
  return MARKETING_CATALOG_PLUGIN_IDS.has(pluginId);
}

/** Lazy product catalog surface — dynamic import only (Wave C.a). */
export async function resolveMarketingCatalogSurface(
  pluginId: string
): Promise<MarketingCatalogSurface | null> {
  switch (pluginId) {
    case "denali": {
      const mod = await import("@app-tour/workspace-denali/host/marketing/marketing-catalog-surface");
      return mod.denaliMarketingCatalogSurface;
    }
    default:
      return null;
  }
}
