/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 * Location: packages/guest-workspace-runtime (P5.3) — product dynamic imports stay package-owned.
 */

/** Sorted trunk plugin ids — cache bust when codegen regen changes membership. */
export const WORKSPACE_PLUGIN_REGISTER_REVISION = "alpine,cert-club,cert-events,denali,guest-club,harbor,profile-cert,starter,urban";

export const WORKSPACE_PLUGIN_REGISTER_IDS = Object.freeze([
  "alpine",
  "cert-club",
  "cert-events",
  "denali",
  "guest-club",
  "harbor",
  "profile-cert",
  "starter",
  "urban",
]) as readonly string[];

/** Dynamic per-plugin full registrar — product imports live in register-*.generated.ts. */
export async function invokeWorkspacePluginRegister(pluginId: string): Promise<void> {
  switch (pluginId) {
    case "alpine": {
      const mod = await import("./register-alpine.generated");
      await mod.registerWorkspacePluginALPINEFromManifest();
      return;
    }
    case "cert-club": {
      const mod = await import("./register-cert-club.generated");
      await mod.registerWorkspacePluginCERT_CLUBFromManifest();
      return;
    }
    case "cert-events": {
      const mod = await import("./register-cert-events.generated");
      await mod.registerWorkspacePluginCERT_EVENTSFromManifest();
      return;
    }
    case "denali": {
      const mod = await import("./register-denali.generated");
      await mod.registerWorkspacePluginDENALIFromManifest();
      return;
    }
    case "guest-club": {
      const mod = await import("./register-guest-club.generated");
      await mod.registerWorkspacePluginGUEST_CLUBFromManifest();
      return;
    }
    case "harbor": {
      const mod = await import("./register-harbor.generated");
      await mod.registerWorkspacePluginHARBORFromManifest();
      return;
    }
    case "profile-cert": {
      const mod = await import("./register-profile-cert.generated");
      await mod.registerWorkspacePluginPROFILE_CERTFromManifest();
      return;
    }
    case "starter": {
      const mod = await import("./register-starter.generated");
      await mod.registerWorkspacePluginSTARTERFromManifest();
      return;
    }
    case "urban": {
      const mod = await import("./register-urban.generated");
      await mod.registerWorkspacePluginURBANFromManifest();
      return;
    }
    default:
      throw new Error(`WORKSPACE_PLUGIN_REGISTER_UNKNOWN:${pluginId}`);
  }
}

/** Dynamic per-plugin intake registrar — plugin entry only (API dispatch path). */
export async function invokeWorkspaceIntakeRegister(pluginId: string): Promise<void> {
  switch (pluginId) {
    case "alpine": {
      const mod = await import("./register-alpine.generated");
      await mod.registerWorkspaceIntakeALPINEFromManifest();
      return;
    }
    case "cert-club": {
      const mod = await import("./register-cert-club.generated");
      await mod.registerWorkspaceIntakeCERT_CLUBFromManifest();
      return;
    }
    case "cert-events": {
      const mod = await import("./register-cert-events.generated");
      await mod.registerWorkspaceIntakeCERT_EVENTSFromManifest();
      return;
    }
    case "denali": {
      const mod = await import("./register-denali.generated");
      await mod.registerWorkspaceIntakeDENALIFromManifest();
      return;
    }
    case "guest-club": {
      const mod = await import("./register-guest-club.generated");
      await mod.registerWorkspaceIntakeGUEST_CLUBFromManifest();
      return;
    }
    case "harbor": {
      const mod = await import("./register-harbor.generated");
      await mod.registerWorkspaceIntakeHARBORFromManifest();
      return;
    }
    case "profile-cert": {
      const mod = await import("./register-profile-cert.generated");
      await mod.registerWorkspaceIntakePROFILE_CERTFromManifest();
      return;
    }
    case "starter": {
      const mod = await import("./register-starter.generated");
      await mod.registerWorkspaceIntakeSTARTERFromManifest();
      return;
    }
    case "urban": {
      const mod = await import("./register-urban.generated");
      await mod.registerWorkspaceIntakeURBANFromManifest();
      return;
    }
    default:
      throw new Error(`WORKSPACE_PLUGIN_REGISTER_UNKNOWN:${pluginId}`);
  }
}
