/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { MemberModuleManifest } from "./member-module-manifest";
import type { MemberPortalAvailability } from "./member-portal-availability";

export type MemberPortalContractRow =
  | { readonly availability: "off" }
  | {
      readonly availability: Extract<MemberPortalAvailability, "minimal" | "full">;
      readonly includePlatformHome: boolean;
      readonly defaultPrimaryModuleId: string;
      readonly modules: readonly MemberModuleManifest[];
    };

/** SSOT — compiled member portal contract per workspace (manifest → codegen). */
export const WORKSPACE_MEMBER_PORTAL_CONTRACTS: Readonly<
  Record<string, MemberPortalContractRow>
> = Object.freeze({
  "denali": Object.freeze({
    availability: "full",
    includePlatformHome: true,
    defaultPrimaryModuleId: "trips",
    modules: Object.freeze([
      Object.freeze({
        id: "trips",
        routePath: "/me/registrations",
        nav: Object.freeze({
          tier: "primary",
          labelKey: "trips",
        }),
      }),
      Object.freeze({
        id: "profile",
        routePath: "/me/profile",
        nav: Object.freeze({
          tier: "user_menu",
          labelKey: "profile",
        }),
      }),
      Object.freeze({
        id: "wallet",
        routePath: "/me/wallet",
        nav: Object.freeze({
          tier: "hidden",
          labelKey: "wallet",
        }),
      }),
    ] as const satisfies readonly MemberModuleManifest[]),
  }),
  "guest-club": Object.freeze({
    availability: "minimal",
    includePlatformHome: false,
    defaultPrimaryModuleId: "trips",
    modules: Object.freeze([
      Object.freeze({
        id: "trips",
        routePath: "/me/registrations",
        nav: Object.freeze({
          tier: "primary",
          labelKey: "trips",
        }),
      }),
      Object.freeze({
        id: "profile",
        routePath: "/me/profile",
        nav: Object.freeze({
          tier: "user_menu",
          labelKey: "profile",
        }),
      }),
    ] as const satisfies readonly MemberModuleManifest[]),
  }),
  "starter": Object.freeze({ availability: "off" as const }),
  "urban": Object.freeze({
    availability: "minimal",
    includePlatformHome: false,
    defaultPrimaryModuleId: "trips",
    modules: Object.freeze([
      Object.freeze({
        id: "trips",
        routePath: "/me/registrations",
        nav: Object.freeze({
          tier: "primary",
          labelKey: "trips",
        }),
      }),
      Object.freeze({
        id: "profile",
        routePath: "/me/profile",
        nav: Object.freeze({
          tier: "user_menu",
          labelKey: "profile",
        }),
      }),
    ] as const satisfies readonly MemberModuleManifest[]),
  }),
});
