/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { MemberRegistrationDisplayStatus } from "../registration/member-registration-display-status";

export type WorkspaceMemberRegistrationStatusDisplayMap = Readonly<
  Record<string, MemberRegistrationDisplayStatus>
>;

/** SSOT — native wire status → member display semantic (manifest → codegen). */
export const WORKSPACE_MEMBER_REGISTRATION_STATUS_DISPLAY: Readonly<
  Record<string, WorkspaceMemberRegistrationStatusDisplayMap>
> = Object.freeze({
  "denali": Object.freeze({
      "approved": "accepted",
      "cancelled": "cancelled",
      "pending": "pending_review",
      "rejected": "rejected",
      "waitlisted": "waitlisted",
    }),
  "guest-club": Object.freeze({
      "cancelled": "cancelled",
      "confirmed": "accepted",
      "waitlist": "waitlisted",
    }),
  "urban": Object.freeze({
      "cancelled": "cancelled",
      "confirmed": "accepted",
      "waitlist": "waitlisted",
    }),
});
