/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import {
  manifestPathToParamRegex,
  staticRoutesFromManifest,
} from "./workspace-route-manifest-bridge";
import type { WorkspaceHttpMethod } from "./workspace-http-method";

import { CATALOG_HTTP_ROUTE_MANIFEST } from "@app-tour/workspace-denali/host/http";
import { FINANCE_HTTP_ROUTE_MANIFEST } from "@app-tour/finance-http";
import { GUEST_CLUB_HTTP_ROUTE_MANIFEST } from "@app-tour/workspace-guest-club/host/http";
import { URBAN_HTTP_ROUTE_MANIFEST } from "@app-tour/workspace-urban/host/http";

export type WorkspaceHttpHandlerKey =
  | "handleFinanceCreateManualPayment"
  | "handleFinanceGenerateSchedule"
  | "handleFinanceGetRegistrationInvoice"
  | "handleFinanceGetSchedule"
  | "handleFinanceLedgerEvents"
  | "handleFinanceListBookingSyncDegraded"
  | "handleFinanceListPayments"
  | "handleFinanceListPrepayments"
  | "handleFinanceListSchedules"
  | "handleFinanceOpenPayments"
  | "handleFinancePatchScheduleItem"
  | "handleFinancePendingReceipts"
  | "handleFinanceReceiptUpload"
  | "handleFinanceReceiptUrl"
  | "handleFinanceRecordPrepayment"
  | "handleFinanceReportByTour"
  | "handleFinanceRetryBookingSync"
  | "handleFinanceReviewReceipt"
  | "handleFinanceSubmitReceipt"
  | "handleFinanceSummary"
  | "handleGetDenaliCatalog"
  | "handleGetDenaliCatalogTour"
  | "handleGetDenaliDashboardTour"
  | "handleGetDenaliReminderFeed"
  | "handleGetGuestClubCatalog"
  | "handleGetGuestClubCatalogTour"
  | "handleGetUrbanCatalog"
  | "handleGetUrbanCatalogTour"
  | "handleGetUrbanSettings"
  | "handlePatchUrbanSettings"
  | "handlePostDenaliRegistration"
  | "handlePostGuestClubRegistration"
  | "handlePostUrbanRegistration";

export type WorkspaceHttpStaticRoute = {
  readonly method: WorkspaceHttpMethod;
  readonly path: string;
  readonly handlerKey: WorkspaceHttpHandlerKey;
};

export type WorkspaceHttpParamRoute = {
  readonly method: WorkspaceHttpMethod;
  readonly pathPattern: RegExp;
  readonly handlerKey: WorkspaceHttpHandlerKey;
};

function paramRoutesFromManifest(
  manifest: readonly { readonly method: WorkspaceHttpMethod; readonly path: string }[],
  handlerByRouteKey: Readonly<Record<string, WorkspaceHttpHandlerKey>>
): readonly WorkspaceHttpParamRoute[] {
  const routes: WorkspaceHttpParamRoute[] = [];
  for (const route of manifest) {
    if (!route.path.includes(":")) {
      continue;
    }
    const routeKey = `${route.method} ${route.path}`;
    const handlerKey = handlerByRouteKey[routeKey];
    if (handlerKey === undefined) {
      throw new Error(`workspace http route manifest missing param handler for ${routeKey}`);
    }
    routes.push({
      method: route.method,
      pathPattern: manifestPathToParamRegex(route.path),
      handlerKey,
    });
  }
  return routes;
}

const DENALI_CATALOG_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS = {
  "GET /denali/catalog": "handleGetDenaliCatalog",
  "GET /denali/reminders/feed": "handleGetDenaliReminderFeed",
  "POST /denali/registrations": "handlePostDenaliRegistration"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const DENALI_FINANCE_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS = {
  "GET /finance/reports/summary": "handleFinanceSummary",
  "GET /finance/reports/open-payments": "handleFinanceOpenPayments",
  "GET /finance/reports/ledger-events": "handleFinanceLedgerEvents",
  "GET /finance/reports/by-tour": "handleFinanceReportByTour",
  "GET /finance/payments": "handleFinanceListPayments",
  "POST /finance/payments/manual": "handleFinanceCreateManualPayment",
  "POST /finance/receipts": "handleFinanceSubmitReceipt",
  "POST /finance/receipts/upload": "handleFinanceReceiptUpload",
  "GET /finance/receipts/pending": "handleFinancePendingReceipts",
  "GET /finance/prepayments": "handleFinanceListPrepayments",
  "POST /finance/prepayments": "handleFinanceRecordPrepayment",
  "GET /finance/prepayments/booking-sync-degraded": "handleFinanceListBookingSyncDegraded",
  "POST /finance/prepayments/booking-sync-retry": "handleFinanceRetryBookingSync",
  "GET /finance/schedules": "handleFinanceListSchedules",
  "POST /finance/schedules/generate": "handleFinanceGenerateSchedule"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const GUEST_CLUB_GUEST_CLUB_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS = {
  "GET /guest-club/catalog": "handleGetGuestClubCatalog",
  "POST /guest-club/registrations": "handlePostGuestClubRegistration"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const URBAN_URBAN_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS = {
  "GET /urban/settings": "handleGetUrbanSettings",
  "PATCH /urban/settings": "handlePatchUrbanSettings",
  "GET /urban/catalog": "handleGetUrbanCatalog",
  "POST /urban/registrations": "handlePostUrbanRegistration"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const DENALI_CATALOG_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS = {
  "GET /denali/catalog/:tourId": "handleGetDenaliCatalogTour",
  "GET /denali/dashboard/tours/:tourId": "handleGetDenaliDashboardTour"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const DENALI_FINANCE_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS = {
  "PATCH /finance/receipts/:receiptId/review": "handleFinanceReviewReceipt",
  "GET /finance/receipts/:receiptId/url": "handleFinanceReceiptUrl",
  "GET /finance/invoices/:registrationId": "handleFinanceGetRegistrationInvoice",
  "GET /finance/schedules/:registrationId": "handleFinanceGetSchedule",
  "PATCH /finance/schedules/:registrationId/items/:itemId": "handleFinancePatchScheduleItem"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const GUEST_CLUB_GUEST_CLUB_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS = {
  "GET /guest-club/catalog/:tourId": "handleGetGuestClubCatalogTour"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const URBAN_URBAN_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS = {
  "GET /urban/catalog/:tourId": "handleGetUrbanCatalogTour"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

export const WORKSPACE_HTTP_STATIC_ROUTES: readonly WorkspaceHttpStaticRoute[] = [
...staticRoutesFromManifest(CATALOG_HTTP_ROUTE_MANIFEST, DENALI_CATALOG_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS),
...staticRoutesFromManifest(FINANCE_HTTP_ROUTE_MANIFEST, DENALI_FINANCE_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS),
...staticRoutesFromManifest(GUEST_CLUB_HTTP_ROUTE_MANIFEST, GUEST_CLUB_GUEST_CLUB_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS),
...staticRoutesFromManifest(URBAN_HTTP_ROUTE_MANIFEST, URBAN_URBAN_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS),
];

export const WORKSPACE_HTTP_PARAM_ROUTES: readonly WorkspaceHttpParamRoute[] = [
...paramRoutesFromManifest(CATALOG_HTTP_ROUTE_MANIFEST, DENALI_CATALOG_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS),
...paramRoutesFromManifest(FINANCE_HTTP_ROUTE_MANIFEST, DENALI_FINANCE_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS),
...paramRoutesFromManifest(GUEST_CLUB_HTTP_ROUTE_MANIFEST, GUEST_CLUB_GUEST_CLUB_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS),
...paramRoutesFromManifest(URBAN_HTTP_ROUTE_MANIFEST, URBAN_URBAN_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS),
];
