/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import {
  manifestPathToParamRegex,
  staticRoutesFromManifest,
} from "./workspace-route-manifest-bridge";
import type { WorkspaceHttpMethod } from "./workspace-http-method";

import { CATALOG_HTTP_ROUTE_MANIFEST } from "@app-tour/workspace-denali/host/http";
import { CERT_CLUB_HTTP_ROUTE_MANIFEST } from "@app-tour/workspace-cert-club/host/http";
import { CERT_EVENTS_HTTP_ROUTE_MANIFEST } from "@app-tour/workspace-cert-events/host/http";
import { FINANCE_HTTP_ROUTE_MANIFEST } from "@app-tour/finance-http";
import { GUEST_CLUB_HTTP_ROUTE_MANIFEST } from "@app-tour/workspace-guest-club/host/http";
import { HARBOR_HTTP_ROUTE_MANIFEST } from "@app-tour/workspace-harbor/host/http";
import { PROFILE_CERT_HTTP_ROUTE_MANIFEST } from "@app-tour/workspace-profile-cert/host/http";
import { URBAN_HTTP_ROUTE_MANIFEST } from "@app-tour/workspace-urban/host/http";

export type WorkspaceHttpHandlerKey =
  | "handleFinanceApproveRefund"
  | "handleFinanceCancelPendingManualPayment"
  | "handleFinanceCancelRefund"
  | "handleFinanceCaseCommandReviewReceipt"
  | "handleFinanceCaseEncounter"
  | "handleFinanceCompleteRefund"
  | "handleFinanceCreateManualPayment"
  | "handleFinanceGenerateSchedule"
  | "handleFinanceGetRefund"
  | "handleFinanceGetRegistrationInvoice"
  | "handleFinanceGetSchedule"
  | "handleFinanceLedgerEvents"
  | "handleFinanceListBookingSyncDegraded"
  | "handleFinanceListExceptions"
  | "handleFinanceListPayments"
  | "handleFinanceListPrepayments"
  | "handleFinanceListRefunds"
  | "handleFinanceListSchedules"
  | "handleFinanceOpenPayments"
  | "handleFinanceOutstandingBalances"
  | "handleFinancePatchScheduleItem"
  | "handleFinancePendingReceipts"
  | "handleFinanceReceiptUpload"
  | "handleFinanceReceiptUrl"
  | "handleFinanceRecordPrepayment"
  | "handleFinanceRejectRefund"
  | "handleFinanceReportByTour"
  | "handleFinanceRequestRefund"
  | "handleFinanceRetryBookingSync"
  | "handleFinanceReviewReceipt"
  | "handleFinanceSetObligationOverride"
  | "handleFinanceSubmitReceipt"
  | "handleFinanceSummary"
  | "handleFinanceTourCollections"
  | "handleGetCertClubCatalog"
  | "handleGetCertClubCatalogTour"
  | "handleGetCertEventsCatalog"
  | "handleGetCertEventsCatalogTour"
  | "handleGetDenaliCatalog"
  | "handleGetDenaliCatalogTour"
  | "handleGetDenaliDashboardTour"
  | "handleGetDenaliRegistration"
  | "handleGetDenaliRegistrationForTour"
  | "handleGetDenaliReminderFeed"
  | "handleGetGuestClubCatalog"
  | "handleGetGuestClubCatalogTour"
  | "handleGetHarborCatalog"
  | "handleGetHarborCatalogTour"
  | "handleGetProfileCertCatalog"
  | "handleGetProfileCertCatalogTour"
  | "handleGetUrbanCatalog"
  | "handleGetUrbanCatalogTour"
  | "handleGetUrbanSettings"
  | "handlePatchDenaliRegistration"
  | "handlePatchUrbanSettings"
  | "handlePostCertClubRegistration"
  | "handlePostCertEventsRegistration"
  | "handlePostDenaliRegistration"
  | "handlePostGuestClubRegistration"
  | "handlePostHarborRegistration"
  | "handlePostProfileCertRegistration"
  | "handlePostUrbanRegistration";

export type WorkspaceHttpStaticRoute = {
  readonly method: WorkspaceHttpMethod;
  readonly path: string;
  readonly handlerKey: WorkspaceHttpHandlerKey;
};

export type WorkspaceHttpParamRoute = {
  readonly method: WorkspaceHttpMethod;
  readonly pathPattern: RegExp;
  readonly handlerKey: WorkspaceHttpHandlerKey;
};

function paramRoutesFromManifest(
  manifest: readonly { readonly method: WorkspaceHttpMethod; readonly path: string }[],
  handlerByRouteKey: Readonly<Record<string, WorkspaceHttpHandlerKey>>
): readonly WorkspaceHttpParamRoute[] {
  const routes: WorkspaceHttpParamRoute[] = [];
  for (const route of manifest) {
    if (!route.path.includes(":")) {
      continue;
    }
    const routeKey = `${route.method} ${route.path}`;
    const handlerKey = handlerByRouteKey[routeKey];
    if (handlerKey === undefined) {
      throw new Error(`workspace http route manifest missing param handler for ${routeKey}`);
    }
    routes.push({
      method: route.method,
      pathPattern: manifestPathToParamRegex(route.path),
      handlerKey,
    });
  }
  return routes;
}

const CERT_CLUB_CERT_CLUB_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS = {
  "GET /cert-club/catalog": "handleGetCertClubCatalog",
  "POST /cert-club/registrations": "handlePostCertClubRegistration"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const CERT_EVENTS_CERT_EVENTS_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS = {
  "GET /cert-events/catalog": "handleGetCertEventsCatalog",
  "POST /cert-events/registrations": "handlePostCertEventsRegistration"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const DENALI_CATALOG_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS = {
  "GET /denali/catalog": "handleGetDenaliCatalog",
  "GET /denali/reminders/feed": "handleGetDenaliReminderFeed",
  "POST /denali/registrations": "handlePostDenaliRegistration"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const DENALI_FINANCE_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS = {
  "GET /finance/reports/summary": "handleFinanceSummary",
  "GET /finance/reports/open-payments": "handleFinanceOpenPayments",
  "GET /finance/reports/ledger-events": "handleFinanceLedgerEvents",
  "GET /finance/reports/by-tour": "handleFinanceReportByTour",
  "GET /finance/reports/outstanding-balances": "handleFinanceOutstandingBalances",
  "GET /finance/reports/tour-collections": "handleFinanceTourCollections",
  "GET /finance/payments": "handleFinanceListPayments",
  "POST /finance/payments/manual": "handleFinanceCreateManualPayment",
  "POST /finance/receipts": "handleFinanceSubmitReceipt",
  "POST /finance/receipts/upload": "handleFinanceReceiptUpload",
  "GET /finance/receipts/pending": "handleFinancePendingReceipts",
  "GET /finance/exceptions": "handleFinanceListExceptions",
  "GET /finance/refunds": "handleFinanceListRefunds",
  "POST /finance/refunds": "handleFinanceRequestRefund",
  "GET /finance/prepayments": "handleFinanceListPrepayments",
  "POST /finance/prepayments": "handleFinanceRecordPrepayment",
  "GET /finance/prepayments/booking-sync-degraded": "handleFinanceListBookingSyncDegraded",
  "POST /finance/prepayments/booking-sync-retry": "handleFinanceRetryBookingSync",
  "GET /finance/schedules": "handleFinanceListSchedules",
  "POST /finance/schedules/generate": "handleFinanceGenerateSchedule",
  "POST /finance/case/commands/review-receipt": "handleFinanceCaseCommandReviewReceipt"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const GUEST_CLUB_GUEST_CLUB_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS = {
  "GET /guest-club/catalog": "handleGetGuestClubCatalog",
  "POST /guest-club/registrations": "handlePostGuestClubRegistration"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const HARBOR_HARBOR_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS = {
  "GET /harbor/catalog": "handleGetHarborCatalog",
  "POST /harbor/registrations": "handlePostHarborRegistration"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const PROFILE_CERT_PROFILE_CERT_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS = {
  "GET /profile-cert/catalog": "handleGetProfileCertCatalog",
  "POST /profile-cert/registrations": "handlePostProfileCertRegistration"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const URBAN_URBAN_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS = {
  "GET /urban/settings": "handleGetUrbanSettings",
  "PATCH /urban/settings": "handlePatchUrbanSettings",
  "GET /urban/catalog": "handleGetUrbanCatalog",
  "POST /urban/registrations": "handlePostUrbanRegistration"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const CERT_CLUB_CERT_CLUB_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS = {
  "GET /cert-club/catalog/:tourId": "handleGetCertClubCatalogTour"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const CERT_EVENTS_CERT_EVENTS_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS = {
  "GET /cert-events/catalog/:tourId": "handleGetCertEventsCatalogTour"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const DENALI_CATALOG_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS = {
  "GET /denali/catalog/:tourId": "handleGetDenaliCatalogTour",
  "GET /denali/dashboard/tours/:tourId": "handleGetDenaliDashboardTour",
  "GET /denali/registrations/for-tour/:tourId": "handleGetDenaliRegistrationForTour",
  "GET /denali/registrations/:registrationId": "handleGetDenaliRegistration",
  "PATCH /denali/registrations/:registrationId": "handlePatchDenaliRegistration"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const DENALI_FINANCE_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS = {
  "POST /finance/payments/:paymentId/cancel": "handleFinanceCancelPendingManualPayment",
  "GET /finance/refunds/:refundId": "handleFinanceGetRefund",
  "POST /finance/refunds/:refundId/approve": "handleFinanceApproveRefund",
  "POST /finance/refunds/:refundId/complete": "handleFinanceCompleteRefund",
  "POST /finance/refunds/:refundId/reject": "handleFinanceRejectRefund",
  "POST /finance/refunds/:refundId/cancel": "handleFinanceCancelRefund",
  "PATCH /finance/receipts/:receiptId/review": "handleFinanceReviewReceipt",
  "GET /finance/receipts/:receiptId/url": "handleFinanceReceiptUrl",
  "GET /finance/invoices/:registrationId": "handleFinanceGetRegistrationInvoice",
  "PUT /finance/registrations/:registrationId/obligation-override": "handleFinanceSetObligationOverride",
  "GET /finance/schedules/:registrationId": "handleFinanceGetSchedule",
  "PATCH /finance/schedules/:registrationId/items/:itemId": "handleFinancePatchScheduleItem",
  "GET /finance/case/encounters/:registrationId": "handleFinanceCaseEncounter"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const GUEST_CLUB_GUEST_CLUB_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS = {
  "GET /guest-club/catalog/:tourId": "handleGetGuestClubCatalogTour"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const HARBOR_HARBOR_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS = {
  "GET /harbor/catalog/:tourId": "handleGetHarborCatalogTour"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const PROFILE_CERT_PROFILE_CERT_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS = {
  "GET /profile-cert/catalog/:tourId": "handleGetProfileCertCatalogTour"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

const URBAN_URBAN_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS = {
  "GET /urban/catalog/:tourId": "handleGetUrbanCatalogTour"
} as const satisfies Record<string, WorkspaceHttpHandlerKey>;

export const WORKSPACE_HTTP_STATIC_ROUTES: readonly WorkspaceHttpStaticRoute[] = [
...staticRoutesFromManifest(CERT_CLUB_HTTP_ROUTE_MANIFEST, CERT_CLUB_CERT_CLUB_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS),
...staticRoutesFromManifest(CERT_EVENTS_HTTP_ROUTE_MANIFEST, CERT_EVENTS_CERT_EVENTS_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS),
...staticRoutesFromManifest(CATALOG_HTTP_ROUTE_MANIFEST, DENALI_CATALOG_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS),
...staticRoutesFromManifest(FINANCE_HTTP_ROUTE_MANIFEST, DENALI_FINANCE_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS),
...staticRoutesFromManifest(GUEST_CLUB_HTTP_ROUTE_MANIFEST, GUEST_CLUB_GUEST_CLUB_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS),
...staticRoutesFromManifest(HARBOR_HTTP_ROUTE_MANIFEST, HARBOR_HARBOR_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS),
...staticRoutesFromManifest(PROFILE_CERT_HTTP_ROUTE_MANIFEST, PROFILE_CERT_PROFILE_CERT_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS),
...staticRoutesFromManifest(URBAN_HTTP_ROUTE_MANIFEST, URBAN_URBAN_HTTP_ROUTE_MANIFEST_STATIC_HANDLERS),
];

export const WORKSPACE_HTTP_PARAM_ROUTES: readonly WorkspaceHttpParamRoute[] = [
...paramRoutesFromManifest(CERT_CLUB_HTTP_ROUTE_MANIFEST, CERT_CLUB_CERT_CLUB_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS),
...paramRoutesFromManifest(CERT_EVENTS_HTTP_ROUTE_MANIFEST, CERT_EVENTS_CERT_EVENTS_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS),
...paramRoutesFromManifest(CATALOG_HTTP_ROUTE_MANIFEST, DENALI_CATALOG_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS),
...paramRoutesFromManifest(FINANCE_HTTP_ROUTE_MANIFEST, DENALI_FINANCE_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS),
...paramRoutesFromManifest(GUEST_CLUB_HTTP_ROUTE_MANIFEST, GUEST_CLUB_GUEST_CLUB_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS),
...paramRoutesFromManifest(HARBOR_HTTP_ROUTE_MANIFEST, HARBOR_HARBOR_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS),
...paramRoutesFromManifest(PROFILE_CERT_HTTP_ROUTE_MANIFEST, PROFILE_CERT_PROFILE_CERT_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS),
...paramRoutesFromManifest(URBAN_HTTP_ROUTE_MANIFEST, URBAN_URBAN_HTTP_ROUTE_MANIFEST_PARAM_HANDLERS),
];
