/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceHttpHandlerFn, WorkspaceRouteHandlers } from "./workspace-route-registrar";

export type WorkspaceHttpPackageHandlerKey =
  | "handleFinanceCreateManualPayment"
  | "handleFinanceGenerateSchedule"
  | "handleFinanceGetRegistrationInvoice"
  | "handleFinanceGetSchedule"
  | "handleFinanceLedgerEvents"
  | "handleFinanceListBookingSyncDegraded"
  | "handleFinanceListPayments"
  | "handleFinanceListPrepayments"
  | "handleFinanceListSchedules"
  | "handleFinanceOpenPayments"
  | "handleFinancePatchScheduleItem"
  | "handleFinancePendingReceipts"
  | "handleFinanceReceiptUpload"
  | "handleFinanceReceiptUrl"
  | "handleFinanceRecordPrepayment"
  | "handleFinanceReportByTour"
  | "handleFinanceRetryBookingSync"
  | "handleFinanceReviewReceipt"
  | "handleFinanceSubmitReceipt"
  | "handleFinanceSummary"
  | "handleGetDenaliCatalog"
  | "handleGetDenaliCatalogTour"
  | "handleGetDenaliDashboardTour"
  | "handleGetDenaliReminderFeed"
  | "handleGetGuestClubCatalog"
  | "handleGetGuestClubCatalogTour"
  | "handleGetHarborCatalog"
  | "handleGetHarborCatalogTour"
  | "handleGetUrbanCatalog"
  | "handleGetUrbanCatalogTour"
  | "handleGetUrbanSettings"
  | "handlePatchUrbanSettings"
  | "handlePostDenaliRegistration"
  | "handlePostGuestClubRegistration"
  | "handlePostHarborRegistration"
  | "handlePostUrbanRegistration";

export type WorkspaceHttpPackageHandlers = Pick<
  WorkspaceRouteHandlers,
  WorkspaceHttpPackageHandlerKey
>;

const WORKSPACE_HTTP_HANDLER_PACKAGE_BY_KEY = Object.freeze({
  handleFinanceCreateManualPayment: "@app-tour/finance-http",
  handleFinanceGenerateSchedule: "@app-tour/finance-http",
  handleFinanceGetRegistrationInvoice: "@app-tour/finance-http",
  handleFinanceGetSchedule: "@app-tour/finance-http",
  handleFinanceLedgerEvents: "@app-tour/finance-http",
  handleFinanceListBookingSyncDegraded: "@app-tour/finance-http",
  handleFinanceListPayments: "@app-tour/finance-http",
  handleFinanceListPrepayments: "@app-tour/finance-http",
  handleFinanceListSchedules: "@app-tour/finance-http",
  handleFinanceOpenPayments: "@app-tour/finance-http",
  handleFinancePatchScheduleItem: "@app-tour/finance-http",
  handleFinancePendingReceipts: "@app-tour/finance-http",
  handleFinanceReceiptUpload: "@app-tour/finance-http",
  handleFinanceReceiptUrl: "@app-tour/finance-http",
  handleFinanceRecordPrepayment: "@app-tour/finance-http",
  handleFinanceReportByTour: "@app-tour/finance-http",
  handleFinanceRetryBookingSync: "@app-tour/finance-http",
  handleFinanceReviewReceipt: "@app-tour/finance-http",
  handleFinanceSubmitReceipt: "@app-tour/finance-http",
  handleFinanceSummary: "@app-tour/finance-http",
  handleGetDenaliCatalog: "@app-tour/workspace-denali/host/http",
  handleGetDenaliCatalogTour: "@app-tour/workspace-denali/host/http",
  handleGetDenaliDashboardTour: "@app-tour/workspace-denali/host/http",
  handleGetDenaliReminderFeed: "@app-tour/workspace-denali/host/http",
  handlePostDenaliRegistration: "@app-tour/workspace-denali/host/http",
  handleGetGuestClubCatalog: "@app-tour/workspace-guest-club/host/http",
  handleGetGuestClubCatalogTour: "@app-tour/workspace-guest-club/host/http",
  handlePostGuestClubRegistration: "@app-tour/workspace-guest-club/host/http",
  handleGetHarborCatalog: "@app-tour/workspace-harbor/host/http",
  handleGetHarborCatalogTour: "@app-tour/workspace-harbor/host/http",
  handlePostHarborRegistration: "@app-tour/workspace-harbor/host/http",
  handleGetUrbanCatalog: "@app-tour/workspace-urban/host/http",
  handleGetUrbanCatalogTour: "@app-tour/workspace-urban/host/http",
  handleGetUrbanSettings: "@app-tour/workspace-urban/host/http",
  handlePatchUrbanSettings: "@app-tour/workspace-urban/host/http",
  handlePostUrbanRegistration: "@app-tour/workspace-urban/host/http",
}) as Readonly<Record<WorkspaceHttpPackageHandlerKey, string>>;

const WORKSPACE_HTTP_HANDLER_PACKAGES = Object.freeze([
  "@app-tour/finance-http",
  "@app-tour/workspace-denali/host/http",
  "@app-tour/workspace-guest-club/host/http",
  "@app-tour/workspace-harbor/host/http",
  "@app-tour/workspace-urban/host/http",
] as const);

/** @type {Map<string, Promise<Partial<WorkspaceRouteHandlers>>>} */
const workspaceHttpHandlerPackageCache = new Map();

/** Wave G.b — load handlers from a single HTTP handler package. */
export async function loadWorkspaceHttpHandlersForPackage(
  pkg: string
): Promise<Partial<WorkspaceRouteHandlers>> {
  switch (pkg) {
    case "@app-tour/finance-http": {
      const mod = await import("@app-tour/finance-http");
      return {
        handleFinanceCreateManualPayment: mod.handleFinanceCreateManualPayment,
        handleFinanceGenerateSchedule: mod.handleFinanceGenerateSchedule,
        handleFinanceGetRegistrationInvoice: mod.handleFinanceGetRegistrationInvoice,
        handleFinanceGetSchedule: mod.handleFinanceGetSchedule,
        handleFinanceLedgerEvents: mod.handleFinanceLedgerEvents,
        handleFinanceListBookingSyncDegraded: mod.handleFinanceListBookingSyncDegraded,
        handleFinanceListPayments: mod.handleFinanceListPayments,
        handleFinanceListPrepayments: mod.handleFinanceListPrepayments,
        handleFinanceListSchedules: mod.handleFinanceListSchedules,
        handleFinanceOpenPayments: mod.handleFinanceOpenPayments,
        handleFinancePatchScheduleItem: mod.handleFinancePatchScheduleItem,
        handleFinancePendingReceipts: mod.handleFinancePendingReceipts,
        handleFinanceReceiptUpload: mod.handleFinanceReceiptUpload,
        handleFinanceReceiptUrl: mod.handleFinanceReceiptUrl,
        handleFinanceRecordPrepayment: mod.handleFinanceRecordPrepayment,
        handleFinanceReportByTour: mod.handleFinanceReportByTour,
        handleFinanceRetryBookingSync: mod.handleFinanceRetryBookingSync,
        handleFinanceReviewReceipt: mod.handleFinanceReviewReceipt,
        handleFinanceSubmitReceipt: mod.handleFinanceSubmitReceipt,
        handleFinanceSummary: mod.handleFinanceSummary,
      };
    }
    case "@app-tour/workspace-denali/host/http": {
      const mod = await import("@app-tour/workspace-denali/host/http");
      return {
        handleGetDenaliCatalog: mod.handleGetDenaliCatalog,
        handleGetDenaliCatalogTour: mod.handleGetDenaliCatalogTour,
        handleGetDenaliDashboardTour: mod.handleGetDenaliDashboardTour,
        handleGetDenaliReminderFeed: mod.handleGetDenaliReminderFeed,
        handlePostDenaliRegistration: mod.handlePostDenaliRegistration,
      };
    }
    case "@app-tour/workspace-guest-club/host/http": {
      const mod = await import("@app-tour/workspace-guest-club/host/http");
      return {
        handleGetGuestClubCatalog: mod.handleGetGuestClubCatalog,
        handleGetGuestClubCatalogTour: mod.handleGetGuestClubCatalogTour,
        handlePostGuestClubRegistration: mod.handlePostGuestClubRegistration,
      };
    }
    case "@app-tour/workspace-harbor/host/http": {
      const mod = await import("@app-tour/workspace-harbor/host/http");
      return {
        handleGetHarborCatalog: mod.handleGetHarborCatalog,
        handleGetHarborCatalogTour: mod.handleGetHarborCatalogTour,
        handlePostHarborRegistration: mod.handlePostHarborRegistration,
      };
    }
    case "@app-tour/workspace-urban/host/http": {
      const mod = await import("@app-tour/workspace-urban/host/http");
      return {
        handleGetUrbanCatalog: mod.handleGetUrbanCatalog,
        handleGetUrbanCatalogTour: mod.handleGetUrbanCatalogTour,
        handleGetUrbanSettings: mod.handleGetUrbanSettings,
        handlePatchUrbanSettings: mod.handlePatchUrbanSettings,
        handlePostUrbanRegistration: mod.handlePostUrbanRegistration,
      };
    }
    default:
      throw new Error(`WORKSPACE_HTTP_HANDLER_PACKAGE_UNKNOWN:${pkg}`);
  }
}

export function resetWorkspaceHttpHandlerPackageCache(): void {
  workspaceHttpHandlerPackageCache.clear();
}

/** Wave G.b — resolve one handler; caches per package (not multi-product eager). */
export async function ensureWorkspaceHttpHandler(
  key: WorkspaceHttpPackageHandlerKey
): Promise<WorkspaceHttpHandlerFn> {
  const pkg = WORKSPACE_HTTP_HANDLER_PACKAGE_BY_KEY[key];
  let pending = workspaceHttpHandlerPackageCache.get(pkg);
  if (pending === undefined) {
    pending = loadWorkspaceHttpHandlersForPackage(pkg);
    workspaceHttpHandlerPackageCache.set(pkg, pending);
  }
  const handlers = await pending;
  const handler = handlers[key];
  if (handler == null) {
    throw new Error(`WORKSPACE_HTTP_HANDLER_MISSING:${key}`);
  }
  return handler;
}

/**
 * Compat — loads **all** HTTP handler packages (tests / ownership proofs).
 * Hot path must use {@link ensureWorkspaceHttpHandler} instead (Wave G.b).
 */
export async function loadWorkspaceHttpPackageHandlers(): Promise<WorkspaceHttpPackageHandlers> {
  /** @type {Partial<WorkspaceRouteHandlers>} */
  const handlers = {};
  for (const pkg of WORKSPACE_HTTP_HANDLER_PACKAGES) {
    Object.assign(handlers, await loadWorkspaceHttpHandlersForPackage(pkg));
  }
  return handlers as WorkspaceHttpPackageHandlers;
}
