/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceRouteHandlers } from "./workspace-route-registrar";

export type WorkspaceHttpPackageHandlerKey =
  | "handleFinanceCreateManualPayment"
  | "handleFinanceGenerateSchedule"
  | "handleFinanceGetRegistrationInvoice"
  | "handleFinanceGetSchedule"
  | "handleFinanceLedgerEvents"
  | "handleFinanceListBookingSyncDegraded"
  | "handleFinanceListPayments"
  | "handleFinanceListPrepayments"
  | "handleFinanceListSchedules"
  | "handleFinanceOpenPayments"
  | "handleFinancePendingReceipts"
  | "handleFinanceReceiptUrl"
  | "handleFinanceRecordPrepayment"
  | "handleFinanceRetryBookingSync"
  | "handleFinanceReviewReceipt"
  | "handleFinanceSubmitReceipt"
  | "handleFinanceSummary"
  | "handleGetDenaliCatalog"
  | "handleGetDenaliCatalogTour"
  | "handleGetDenaliDashboardTour"
  | "handleGetDenaliReminderFeed"
  | "handleGetGuestClubCatalog"
  | "handleGetGuestClubCatalogTour"
  | "handleGetUrbanCatalog"
  | "handleGetUrbanCatalogTour"
  | "handleGetUrbanSettings"
  | "handlePatchUrbanSettings"
  | "handlePostDenaliRegistration"
  | "handlePostGuestClubRegistration"
  | "handlePostUrbanRegistration";

export type WorkspaceHttpPackageHandlers = Pick<
  WorkspaceRouteHandlers,
  WorkspaceHttpPackageHandlerKey
>;

export async function loadWorkspaceHttpPackageHandlers(): Promise<WorkspaceHttpPackageHandlers> {
  /** @type {Partial<WorkspaceRouteHandlers>} */
  const handlers = {};
  const mod0 = await import("@app-tour/workspace-denali/host/http");
  Object.assign(handlers, {
    handleFinanceCreateManualPayment: mod0.handleFinanceCreateManualPayment,
    handleFinanceGenerateSchedule: mod0.handleFinanceGenerateSchedule,
    handleFinanceGetRegistrationInvoice: mod0.handleFinanceGetRegistrationInvoice,
    handleFinanceGetSchedule: mod0.handleFinanceGetSchedule,
    handleFinanceLedgerEvents: mod0.handleFinanceLedgerEvents,
    handleFinanceListBookingSyncDegraded: mod0.handleFinanceListBookingSyncDegraded,
    handleFinanceListPayments: mod0.handleFinanceListPayments,
    handleFinanceListPrepayments: mod0.handleFinanceListPrepayments,
    handleFinanceListSchedules: mod0.handleFinanceListSchedules,
    handleFinanceOpenPayments: mod0.handleFinanceOpenPayments,
    handleFinancePendingReceipts: mod0.handleFinancePendingReceipts,
    handleFinanceReceiptUrl: mod0.handleFinanceReceiptUrl,
    handleFinanceRecordPrepayment: mod0.handleFinanceRecordPrepayment,
    handleFinanceRetryBookingSync: mod0.handleFinanceRetryBookingSync,
    handleFinanceReviewReceipt: mod0.handleFinanceReviewReceipt,
    handleFinanceSubmitReceipt: mod0.handleFinanceSubmitReceipt,
    handleFinanceSummary: mod0.handleFinanceSummary,
    handleGetDenaliCatalog: mod0.handleGetDenaliCatalog,
    handleGetDenaliCatalogTour: mod0.handleGetDenaliCatalogTour,
    handleGetDenaliDashboardTour: mod0.handleGetDenaliDashboardTour,
    handleGetDenaliReminderFeed: mod0.handleGetDenaliReminderFeed,
    handlePostDenaliRegistration: mod0.handlePostDenaliRegistration,
  });
  const mod1 = await import("@app-tour/workspace-guest-club/host/http");
  Object.assign(handlers, {
    handleGetGuestClubCatalog: mod1.handleGetGuestClubCatalog,
    handleGetGuestClubCatalogTour: mod1.handleGetGuestClubCatalogTour,
    handlePostGuestClubRegistration: mod1.handlePostGuestClubRegistration,
  });
  const mod2 = await import("@app-tour/workspace-urban/host/http");
  Object.assign(handlers, {
    handleGetUrbanCatalog: mod2.handleGetUrbanCatalog,
    handleGetUrbanCatalogTour: mod2.handleGetUrbanCatalogTour,
    handleGetUrbanSettings: mod2.handleGetUrbanSettings,
    handlePatchUrbanSettings: mod2.handlePatchUrbanSettings,
    handlePostUrbanRegistration: mod2.handlePostUrbanRegistration,
  });
  return handlers as WorkspaceHttpPackageHandlers;
}
