/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export { configureDenaliProductHttpHost, type BookingPublicPort, type DenaliProductRouteDeps, type DenaliPublicDestinationPort } from "@app-tour/workspace-denali/host/http";
export { configureHarborHttpHost, type HarborHttpHostPorts, type HarborProductRouteDeps } from "@app-tour/workspace-harbor/host/http";
export { configureUrbanHttpHost, type UrbanHttpHostPorts, type UrbanProductRouteDeps } from "@app-tour/workspace-urban/host/http";
