/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceHttpHandlerFn, WorkspaceRouteHandlers } from "./workspace-route-registrar";

export type WorkspaceHttpPackageHandlerKey =
  | "handleFinanceApproveRefund"
  | "handleFinanceCancelPendingManualPayment"
  | "handleFinanceCancelRefund"
  | "handleFinanceCaseCommandReviewReceipt"
  | "handleFinanceCaseEncounter"
  | "handleFinanceCompleteRefund"
  | "handleFinanceCreateManualPayment"
  | "handleFinanceGenerateSchedule"
  | "handleFinanceGetRefund"
  | "handleFinanceGetRegistrationInvoice"
  | "handleFinanceGetSchedule"
  | "handleFinanceLedgerEvents"
  | "handleFinanceListBookingSyncDegraded"
  | "handleFinanceListExceptions"
  | "handleFinanceListPayments"
  | "handleFinanceListPrepayments"
  | "handleFinanceListRefunds"
  | "handleFinanceListSchedules"
  | "handleFinanceOpenPayments"
  | "handleFinanceOutstandingBalances"
  | "handleFinancePatchScheduleItem"
  | "handleFinancePendingReceipts"
  | "handleFinanceReceiptUpload"
  | "handleFinanceReceiptUrl"
  | "handleFinanceRecordPrepayment"
  | "handleFinanceRejectRefund"
  | "handleFinanceReportByTour"
  | "handleFinanceRequestRefund"
  | "handleFinanceRetryBookingSync"
  | "handleFinanceReviewReceipt"
  | "handleFinanceSetObligationOverride"
  | "handleFinanceSubmitReceipt"
  | "handleFinanceSummary"
  | "handleFinanceTourCollections"
  | "handleGetCertClubCatalog"
  | "handleGetCertClubCatalogTour"
  | "handleGetCertEventsCatalog"
  | "handleGetCertEventsCatalogTour"
  | "handleGetDenaliCatalog"
  | "handleGetDenaliCatalogTour"
  | "handleGetDenaliDashboardTour"
  | "handleGetDenaliRegistration"
  | "handleGetDenaliRegistrationForTour"
  | "handleGetDenaliReminderFeed"
  | "handleGetGuestClubCatalog"
  | "handleGetGuestClubCatalogTour"
  | "handleGetHarborCatalog"
  | "handleGetHarborCatalogTour"
  | "handleGetProfileCertCatalog"
  | "handleGetProfileCertCatalogTour"
  | "handleGetUrbanCatalog"
  | "handleGetUrbanCatalogTour"
  | "handleGetUrbanSettings"
  | "handlePatchDenaliRegistration"
  | "handlePatchUrbanSettings"
  | "handlePostCertClubRegistration"
  | "handlePostCertEventsRegistration"
  | "handlePostDenaliRegistration"
  | "handlePostGuestClubRegistration"
  | "handlePostHarborRegistration"
  | "handlePostProfileCertRegistration"
  | "handlePostUrbanRegistration"
  | "handleWalletMemberBalance"
  | "handleWalletMemberOwnBalance"
  | "handleWalletMemberOwnTransactions"
  | "handleWalletMemberTransactions"
  | "handleWalletOperatorAccounts"
  | "handleWalletOperatorCredit"
  | "handleWalletOperatorDebit"
  | "handleWalletOperatorReversal";

export type WorkspaceHttpPackageHandlers = Pick<
  WorkspaceRouteHandlers,
  WorkspaceHttpPackageHandlerKey
>;

const WORKSPACE_HTTP_HANDLER_PACKAGE_BY_KEY = Object.freeze({
  handleFinanceApproveRefund: "@app-tour/finance-http",
  handleFinanceCancelPendingManualPayment: "@app-tour/finance-http",
  handleFinanceCancelRefund: "@app-tour/finance-http",
  handleFinanceCaseCommandReviewReceipt: "@app-tour/finance-http",
  handleFinanceCaseEncounter: "@app-tour/finance-http",
  handleFinanceCompleteRefund: "@app-tour/finance-http",
  handleFinanceCreateManualPayment: "@app-tour/finance-http",
  handleFinanceGenerateSchedule: "@app-tour/finance-http",
  handleFinanceGetRefund: "@app-tour/finance-http",
  handleFinanceGetRegistrationInvoice: "@app-tour/finance-http",
  handleFinanceGetSchedule: "@app-tour/finance-http",
  handleFinanceLedgerEvents: "@app-tour/finance-http",
  handleFinanceListBookingSyncDegraded: "@app-tour/finance-http",
  handleFinanceListExceptions: "@app-tour/finance-http",
  handleFinanceListPayments: "@app-tour/finance-http",
  handleFinanceListPrepayments: "@app-tour/finance-http",
  handleFinanceListRefunds: "@app-tour/finance-http",
  handleFinanceListSchedules: "@app-tour/finance-http",
  handleFinanceOpenPayments: "@app-tour/finance-http",
  handleFinanceOutstandingBalances: "@app-tour/finance-http",
  handleFinancePatchScheduleItem: "@app-tour/finance-http",
  handleFinancePendingReceipts: "@app-tour/finance-http",
  handleFinanceReceiptUpload: "@app-tour/finance-http",
  handleFinanceReceiptUrl: "@app-tour/finance-http",
  handleFinanceRecordPrepayment: "@app-tour/finance-http",
  handleFinanceRejectRefund: "@app-tour/finance-http",
  handleFinanceReportByTour: "@app-tour/finance-http",
  handleFinanceRequestRefund: "@app-tour/finance-http",
  handleFinanceRetryBookingSync: "@app-tour/finance-http",
  handleFinanceReviewReceipt: "@app-tour/finance-http",
  handleFinanceSetObligationOverride: "@app-tour/finance-http",
  handleFinanceSubmitReceipt: "@app-tour/finance-http",
  handleFinanceSummary: "@app-tour/finance-http",
  handleFinanceTourCollections: "@app-tour/finance-http",
  handleWalletMemberBalance: "@app-tour/wallet-http",
  handleWalletMemberOwnBalance: "@app-tour/wallet-http",
  handleWalletMemberOwnTransactions: "@app-tour/wallet-http",
  handleWalletMemberTransactions: "@app-tour/wallet-http",
  handleWalletOperatorAccounts: "@app-tour/wallet-http",
  handleWalletOperatorCredit: "@app-tour/wallet-http",
  handleWalletOperatorDebit: "@app-tour/wallet-http",
  handleWalletOperatorReversal: "@app-tour/wallet-http",
  handleGetCertClubCatalog: "@app-tour/workspace-cert-club/http",
  handleGetCertClubCatalogTour: "@app-tour/workspace-cert-club/http",
  handlePostCertClubRegistration: "@app-tour/workspace-cert-club/http",
  handleGetCertEventsCatalog: "@app-tour/workspace-cert-events/http",
  handleGetCertEventsCatalogTour: "@app-tour/workspace-cert-events/http",
  handlePostCertEventsRegistration: "@app-tour/workspace-cert-events/http",
  handleGetDenaliCatalog: "@app-tour/workspace-denali/host/http",
  handleGetDenaliCatalogTour: "@app-tour/workspace-denali/host/http",
  handleGetDenaliDashboardTour: "@app-tour/workspace-denali/host/http",
  handleGetDenaliRegistration: "@app-tour/workspace-denali/host/http",
  handleGetDenaliRegistrationForTour: "@app-tour/workspace-denali/host/http",
  handleGetDenaliReminderFeed: "@app-tour/workspace-denali/host/http",
  handlePatchDenaliRegistration: "@app-tour/workspace-denali/host/http",
  handlePostDenaliRegistration: "@app-tour/workspace-denali/host/http",
  handleGetGuestClubCatalog: "@app-tour/workspace-guest-club/host/http",
  handleGetGuestClubCatalogTour: "@app-tour/workspace-guest-club/host/http",
  handlePostGuestClubRegistration: "@app-tour/workspace-guest-club/host/http",
  handleGetHarborCatalog: "@app-tour/workspace-harbor/host/http",
  handleGetHarborCatalogTour: "@app-tour/workspace-harbor/host/http",
  handlePostHarborRegistration: "@app-tour/workspace-harbor/host/http",
  handleGetProfileCertCatalog: "@app-tour/workspace-profile-cert/http",
  handleGetProfileCertCatalogTour: "@app-tour/workspace-profile-cert/http",
  handlePostProfileCertRegistration: "@app-tour/workspace-profile-cert/http",
  handleGetUrbanCatalog: "@app-tour/workspace-urban/host/http",
  handleGetUrbanCatalogTour: "@app-tour/workspace-urban/host/http",
  handleGetUrbanSettings: "@app-tour/workspace-urban/host/http",
  handlePatchUrbanSettings: "@app-tour/workspace-urban/host/http",
  handlePostUrbanRegistration: "@app-tour/workspace-urban/host/http",
}) as Readonly<Record<WorkspaceHttpPackageHandlerKey, string>>;

const WORKSPACE_HTTP_HANDLER_PACKAGES = Object.freeze([
  "@app-tour/finance-http",
  "@app-tour/wallet-http",
  "@app-tour/workspace-cert-club/http",
  "@app-tour/workspace-cert-events/http",
  "@app-tour/workspace-denali/host/http",
  "@app-tour/workspace-guest-club/host/http",
  "@app-tour/workspace-harbor/host/http",
  "@app-tour/workspace-profile-cert/http",
  "@app-tour/workspace-urban/host/http",
] as const);

/** @type {Map<string, Promise<Partial<WorkspaceRouteHandlers>>>} */
const workspaceHttpHandlerPackageCache = new Map();

/** Wave G.b — load handlers from a single HTTP handler package. */
export async function loadWorkspaceHttpHandlersForPackage(
  pkg: string
): Promise<Partial<WorkspaceRouteHandlers>> {
  switch (pkg) {
    case "@app-tour/finance-http": {
      const mod = await import("@app-tour/finance-http");
      return {
        handleFinanceApproveRefund: mod.handleFinanceApproveRefund,
        handleFinanceCancelPendingManualPayment: mod.handleFinanceCancelPendingManualPayment,
        handleFinanceCancelRefund: mod.handleFinanceCancelRefund,
        handleFinanceCaseCommandReviewReceipt: mod.handleFinanceCaseCommandReviewReceipt,
        handleFinanceCaseEncounter: mod.handleFinanceCaseEncounter,
        handleFinanceCompleteRefund: mod.handleFinanceCompleteRefund,
        handleFinanceCreateManualPayment: mod.handleFinanceCreateManualPayment,
        handleFinanceGenerateSchedule: mod.handleFinanceGenerateSchedule,
        handleFinanceGetRefund: mod.handleFinanceGetRefund,
        handleFinanceGetRegistrationInvoice: mod.handleFinanceGetRegistrationInvoice,
        handleFinanceGetSchedule: mod.handleFinanceGetSchedule,
        handleFinanceLedgerEvents: mod.handleFinanceLedgerEvents,
        handleFinanceListBookingSyncDegraded: mod.handleFinanceListBookingSyncDegraded,
        handleFinanceListExceptions: mod.handleFinanceListExceptions,
        handleFinanceListPayments: mod.handleFinanceListPayments,
        handleFinanceListPrepayments: mod.handleFinanceListPrepayments,
        handleFinanceListRefunds: mod.handleFinanceListRefunds,
        handleFinanceListSchedules: mod.handleFinanceListSchedules,
        handleFinanceOpenPayments: mod.handleFinanceOpenPayments,
        handleFinanceOutstandingBalances: mod.handleFinanceOutstandingBalances,
        handleFinancePatchScheduleItem: mod.handleFinancePatchScheduleItem,
        handleFinancePendingReceipts: mod.handleFinancePendingReceipts,
        handleFinanceReceiptUpload: mod.handleFinanceReceiptUpload,
        handleFinanceReceiptUrl: mod.handleFinanceReceiptUrl,
        handleFinanceRecordPrepayment: mod.handleFinanceRecordPrepayment,
        handleFinanceRejectRefund: mod.handleFinanceRejectRefund,
        handleFinanceReportByTour: mod.handleFinanceReportByTour,
        handleFinanceRequestRefund: mod.handleFinanceRequestRefund,
        handleFinanceRetryBookingSync: mod.handleFinanceRetryBookingSync,
        handleFinanceReviewReceipt: mod.handleFinanceReviewReceipt,
        handleFinanceSetObligationOverride: mod.handleFinanceSetObligationOverride,
        handleFinanceSubmitReceipt: mod.handleFinanceSubmitReceipt,
        handleFinanceSummary: mod.handleFinanceSummary,
        handleFinanceTourCollections: mod.handleFinanceTourCollections,
      };
    }
    case "@app-tour/wallet-http": {
      const mod = await import("@app-tour/wallet-http");
      return {
        handleWalletMemberBalance: mod.handleWalletMemberBalance,
        handleWalletMemberOwnBalance: mod.handleWalletMemberOwnBalance,
        handleWalletMemberOwnTransactions: mod.handleWalletMemberOwnTransactions,
        handleWalletMemberTransactions: mod.handleWalletMemberTransactions,
        handleWalletOperatorAccounts: mod.handleWalletOperatorAccounts,
        handleWalletOperatorCredit: mod.handleWalletOperatorCredit,
        handleWalletOperatorDebit: mod.handleWalletOperatorDebit,
        handleWalletOperatorReversal: mod.handleWalletOperatorReversal,
      };
    }
    case "@app-tour/workspace-cert-club/http": {
      const mod = await import("@app-tour/workspace-cert-club/http");
      return {
        handleGetCertClubCatalog: mod.handleGetCertClubCatalog,
        handleGetCertClubCatalogTour: mod.handleGetCertClubCatalogTour,
        handlePostCertClubRegistration: mod.handlePostCertClubRegistration,
      };
    }
    case "@app-tour/workspace-cert-events/http": {
      const mod = await import("@app-tour/workspace-cert-events/http");
      return {
        handleGetCertEventsCatalog: mod.handleGetCertEventsCatalog,
        handleGetCertEventsCatalogTour: mod.handleGetCertEventsCatalogTour,
        handlePostCertEventsRegistration: mod.handlePostCertEventsRegistration,
      };
    }
    case "@app-tour/workspace-denali/host/http": {
      const mod = await import("@app-tour/workspace-denali/host/http");
      return {
        handleGetDenaliCatalog: mod.handleGetDenaliCatalog,
        handleGetDenaliCatalogTour: mod.handleGetDenaliCatalogTour,
        handleGetDenaliDashboardTour: mod.handleGetDenaliDashboardTour,
        handleGetDenaliRegistration: mod.handleGetDenaliRegistration,
        handleGetDenaliRegistrationForTour: mod.handleGetDenaliRegistrationForTour,
        handleGetDenaliReminderFeed: mod.handleGetDenaliReminderFeed,
        handlePatchDenaliRegistration: mod.handlePatchDenaliRegistration,
        handlePostDenaliRegistration: mod.handlePostDenaliRegistration,
      };
    }
    case "@app-tour/workspace-guest-club/host/http": {
      const mod = await import("@app-tour/workspace-guest-club/host/http");
      return {
        handleGetGuestClubCatalog: mod.handleGetGuestClubCatalog,
        handleGetGuestClubCatalogTour: mod.handleGetGuestClubCatalogTour,
        handlePostGuestClubRegistration: mod.handlePostGuestClubRegistration,
      };
    }
    case "@app-tour/workspace-harbor/host/http": {
      const mod = await import("@app-tour/workspace-harbor/host/http");
      return {
        handleGetHarborCatalog: mod.handleGetHarborCatalog,
        handleGetHarborCatalogTour: mod.handleGetHarborCatalogTour,
        handlePostHarborRegistration: mod.handlePostHarborRegistration,
      };
    }
    case "@app-tour/workspace-profile-cert/http": {
      const mod = await import("@app-tour/workspace-profile-cert/http");
      return {
        handleGetProfileCertCatalog: mod.handleGetProfileCertCatalog,
        handleGetProfileCertCatalogTour: mod.handleGetProfileCertCatalogTour,
        handlePostProfileCertRegistration: mod.handlePostProfileCertRegistration,
      };
    }
    case "@app-tour/workspace-urban/host/http": {
      const mod = await import("@app-tour/workspace-urban/host/http");
      return {
        handleGetUrbanCatalog: mod.handleGetUrbanCatalog,
        handleGetUrbanCatalogTour: mod.handleGetUrbanCatalogTour,
        handleGetUrbanSettings: mod.handleGetUrbanSettings,
        handlePatchUrbanSettings: mod.handlePatchUrbanSettings,
        handlePostUrbanRegistration: mod.handlePostUrbanRegistration,
      };
    }
    default:
      throw new Error(`WORKSPACE_HTTP_HANDLER_PACKAGE_UNKNOWN:${pkg}`);
  }
}

export function resetWorkspaceHttpHandlerPackageCache(): void {
  workspaceHttpHandlerPackageCache.clear();
}

/** Wave G.b — resolve one handler; caches per package (not multi-product eager). */
export async function ensureWorkspaceHttpHandler(
  key: WorkspaceHttpPackageHandlerKey
): Promise<WorkspaceHttpHandlerFn> {
  const pkg = WORKSPACE_HTTP_HANDLER_PACKAGE_BY_KEY[key];
  let pending = workspaceHttpHandlerPackageCache.get(pkg);
  if (pending === undefined) {
    pending = loadWorkspaceHttpHandlersForPackage(pkg);
    workspaceHttpHandlerPackageCache.set(pkg, pending);
  }
  const handlers = await pending;
  const handler = handlers[key];
  if (handler == null) {
    throw new Error(`WORKSPACE_HTTP_HANDLER_MISSING:${key}`);
  }
  return handler;
}

/**
 * Compat — loads **all** HTTP handler packages (tests / ownership proofs).
 * Hot path must use {@link ensureWorkspaceHttpHandler} instead (Wave G.b).
 */
export async function loadWorkspaceHttpPackageHandlers(): Promise<WorkspaceHttpPackageHandlers> {
  /** @type {Partial<WorkspaceRouteHandlers>} */
  const handlers = {};
  for (const pkg of WORKSPACE_HTTP_HANDLER_PACKAGES) {
    Object.assign(handlers, await loadWorkspaceHttpHandlersForPackage(pkg));
  }
  return handlers as WorkspaceHttpPackageHandlers;
}
