/**
 * AUTO-GENERATED by scripts/generate-denali-settings-modules.mjs — DO NOT EDIT.
 * Source: packages/workspaces/denali/src/settings/denali-settings.manifest.ts
 * Regenerate: pnpm run generate:denali-settings-modules
 */
export const DENALI_BACKEND_REQUIRED_MODULE_IDS = [
  "workspace_branding",
  "integrations",
  "exposure",
  "equipment",
  "guide_languages",
  "tour_themes",
  "locations",
  "tour_presets",
  "tour_wizard_template",
  "wizard_drafts",
  "tour_presets_advanced",
  "audit_trail",
] as const;
