/** 401 — missing or invalid auth ingress (headers / JWT). */
export const UNAUTHORIZED_MISSING_AUTHENTICATED_TENANT =
  "UNAUTHORIZED_MISSING_AUTHENTICATED_TENANT";
export const UNAUTHORIZED_MISSING_USER_ID = "UNAUTHORIZED_MISSING_USER_ID";
export const UNAUTHORIZED_MISSING_ACTOR_ROLE = "UNAUTHORIZED_MISSING_ACTOR_ROLE";
export const UNAUTHORIZED_MISSING_MEMBERSHIP_STATUS = "UNAUTHORIZED_MISSING_MEMBERSHIP_STATUS";
export const UNAUTHORIZED_MISSING_WORKSPACE_ID = "UNAUTHORIZED_MISSING_WORKSPACE_ID";
export const UNAUTHORIZED_INVALID_BEARER_TOKEN = "UNAUTHORIZED_INVALID_BEARER_TOKEN";
export const UNAUTHORIZED_DEV_BEARER_DISABLED = "UNAUTHORIZED_DEV_BEARER_DISABLED";
export const AUTH_DEV_BEARER_FORBIDDEN_OUTSIDE_TEST =
  "AUTH_DEV_BEARER_FORBIDDEN_OUTSIDE_TEST";
