import { BANNER } from "../constants.mjs";
import { importSpecifier, workspaceManifestConstPrefix } from "../utils.mjs";
import { filterManifestsByDeployProfile } from "./deploy-profile.mjs";

/** Portal/runtime banner — product dynamic imports stay runtime-owned (P3.2.b / P5.1 / P5.3). */
export const PORTAL_REGISTER_BANNER = `/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 * Location: packages/guest-workspace-runtime (P5.3) — product dynamic imports stay package-owned.
 */
`;

/** Host ids-only banner (P3.2.b / P5.1). */
export const HOST_REGISTER_BANNER = `/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 *
 * P3.2.b — IDs + revision only. Product registrars live under apps/portal/src/bootstrap/.
 */
`;

/**
 * Portal register membership: registration-flow and/or member portal, plus starter intake baseline.
 * @param {ReturnType<typeof discoverManifests>} manifests
 */
export function selectPortalRegisterManifests(manifests) {
  return manifests
    .filter(
      (m) =>
        m.catalogRegistrationFlow !== undefined ||
        m.memberPortal !== undefined ||
        m.id === "starter"
    )
    .slice()
    .sort((a, b) => a.id.localeCompare(b.id));
}

/** @param {string} workspaceId */
export function portalRegisterOutputKey(workspaceId) {
  return `portalRegister_${workspaceId.replace(/-/g, "_")}`;
}

function namedImportLine(names, specifier) {
  if (names.length <= 1) {
    return `import { ${names.join(", ")} } from "${specifier}";`;
  }
  return `import {
  ${names.join(",\n  ")},
} from "${specifier}";`;
}

function awaitNamedImportLine(names, specifier, indent = "  ") {
  const inlinePattern = `${indent}const { ${names.join(", ")} }`;
  const inlineLine = `${inlinePattern} = await import("${specifier}");`;
  if (inlineLine.length <= 100) {
    return inlineLine;
  }
  if (inlinePattern.length <= 80) {
    return `${inlinePattern} =
${indent}  await import("${specifier}");`;
  }
  return `${indent}const {
${names.map((name) => `${indent}  ${name},`).join("\n")}
${indent}} = await import("${specifier}");`;
}

/**
 * @param {ReturnType<typeof discoverManifests>[number]} manifest
 * @param {ReturnType<typeof discoverManifests>} allManifests
 */
function generatePortalRegistrationFlowBody(manifest, allManifests) {
  const cfg = manifest.catalogRegistrationFlow;
  if (cfg === undefined) {
    return "";
  }
  assertCatalogRegistrationFlowManifest(manifest, allManifests);
  assertCatalogRegistrationTransportInitializerManifest(manifest);

  const surfaceSpec = importSpecifier(manifest.package, "./catalog-registration-flow");
  const reactSpec = importSpecifier(manifest.package, "./catalog-registration-flow/react");
  /** @type {string[]} */
  const lines = [""];

  if (typeof cfg.transportInitializerExport === "string") {
    lines.push(
      awaitNamedImportLine([cfg.transportInitializerExport], surfaceSpec),
      `  ${cfg.transportInitializerExport}();`,
      ""
    );
  }

  if (cfg.steps.mode === "bundle") {
    lines.push(
      awaitNamedImportLine([cfg.surfaceExport], surfaceSpec),
      awaitNamedImportLine([cfg.steps.export], reactSpec),
      `  registerWorkspaceRegistrationFlowPlugin({`,
      `    id: ${JSON.stringify(manifest.id)},`,
      `    catalogRegistrationFlow: ${cfg.surfaceExport},`,
      `  });`,
      `  registerWorkspaceRegistrationFlowSteps(${JSON.stringify(manifest.id)}, ${cfg.steps.export});`
    );
    return lines.join("\n");
  }

  const authSource = cfg.steps.reuseAuthStepsFrom ?? cfg.steps.reuseFrom;
  if (authSource !== "shared") {
    throw new Error(
      `${manifest.id}: portal registrar codegen supports compose reuseAuthStepsFrom "shared" only (got ${JSON.stringify(authSource)})`
    );
  }
  const intake = cfg.steps.components.intake;
  const done = cfg.steps.components.done;
  lines.push(
    awaitNamedImportLine([cfg.surfaceExport], surfaceSpec),
    awaitNamedImportLine([intake, done], reactSpec),
    awaitNamedImportLine(
      [
        "CatalogRegistrationOtpStep",
        "CatalogRegistrationPhoneStep",
        "CatalogRegistrationProfileStep",
      ],
      "@app-tour/catalog-registration-flow-ui/react"
    ),
    `  registerWorkspaceRegistrationFlowPlugin({`,
    `    id: ${JSON.stringify(manifest.id)},`,
    `    catalogRegistrationFlow: ${cfg.surfaceExport},`,
    `  });`,
    `  registerWorkspaceRegistrationFlowSteps(${JSON.stringify(manifest.id)}, {`,
    `    phone: CatalogRegistrationPhoneStep,`,
    `    otp: CatalogRegistrationOtpStep,`,
    `    profile: CatalogRegistrationProfileStep,`,
    `    intake: ${intake},`,
    `    done: ${done},`,
    `  });`
  );
  return lines.join("\n");
}

/**
 * Emit apps/portal/src/bootstrap/register-<id>.generated.ts (dynamic imports only).
 * @param {ReturnType<typeof discoverManifests>[number]} manifest
 * @param {ReturnType<typeof discoverManifests>} allManifests
 */
export function generatePortalPluginRegister(manifest, allManifests) {
  const prefix = workspaceManifestConstPrefix(manifest.id);
  const pluginSpec = importSpecifier(manifest.package, manifest.plugin.entry);
  const pluginExport = manifest.plugin.export;
  const hasFlow = manifest.catalogRegistrationFlow !== undefined;

  const sdkImports = hasFlow
    ? `${namedImportLine(
        [
          "registerWorkspaceIntakePlugin",
          "registerWorkspaceMemberPortalRenderers",
          "registerWorkspaceRegistrationFlowPlugin",
        ],
        "@app-tour/workspace-sdk"
      )}
import { registerWorkspaceRegistrationFlowSteps } from "@app-tour/workspace-plugin-host/registration-flow";`
    : namedImportLine(
        ["registerWorkspaceIntakePlugin", "registerWorkspaceMemberPortalRenderers"],
        "@app-tour/workspace-sdk"
      );

  const intakeBody = `${awaitNamedImportLine([pluginExport], pluginSpec)}
  const plugin = ${pluginExport}();
  if (plugin.catalogIntake !== undefined) {
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
  registerWorkspaceMemberPortalRenderers(plugin.id, plugin.capabilities?.memberPortalRenderers);`;

  const flowBody = generatePortalRegistrationFlowBody(manifest, allManifests);

  return `${PORTAL_REGISTER_BANNER}
${sdkImports}

/** Intake registrar for ${JSON.stringify(manifest.id)} — plugin entry only (no registration-flow UI graph). */
export async function registerWorkspaceIntake${prefix}FromManifest(): Promise<void> {
${intakeBody}
}

/** Full registrar for ${JSON.stringify(manifest.id)} — intake, transport, and registration-flow surfaces. */
export async function registerWorkspacePlugin${prefix}FromManifest(): Promise<void> {
${intakeBody}${flowBody}
}
`;
}

/**
 * @param {ReturnType<typeof discoverManifests>} selected sorted portal-register manifests
 */
export function generatePortalRegisterManifest(selected) {
  const ids = selected.map((m) => m.id);
  const revision = ids.join(",");
  const idLines = ids.map((id) => `  ${JSON.stringify(id)},`).join("\n");

  /** @param {"full" | "intake"} kind */
  function switchCases(kind) {
    return ids
      .map((id) => {
        const prefix = workspaceManifestConstPrefix(id);
        const fn =
          kind === "full"
            ? `registerWorkspacePlugin${prefix}FromManifest`
            : `registerWorkspaceIntake${prefix}FromManifest`;
        return `    case ${JSON.stringify(id)}: {
      const mod = await import("./register-${id}.generated");
      await mod.${fn}();
      return;
    }`;
      })
      .join("\n");
  }

  return `${PORTAL_REGISTER_BANNER}
/** Sorted trunk plugin ids — cache bust when codegen regen changes membership. */
export const WORKSPACE_PLUGIN_REGISTER_REVISION = ${JSON.stringify(revision)};

export const WORKSPACE_PLUGIN_REGISTER_IDS = Object.freeze([
${idLines}
]) as readonly string[];

/** Dynamic per-plugin full registrar — product imports live in register-*.generated.ts. */
export async function invokeWorkspacePluginRegister(pluginId: string): Promise<void> {
  switch (pluginId) {
${switchCases("full")}
    default:
      throw new Error(\`WORKSPACE_PLUGIN_REGISTER_UNKNOWN:\${pluginId}\`);
  }
}

/** Dynamic per-plugin intake registrar — plugin entry only (API dispatch path). */
export async function invokeWorkspaceIntakeRegister(pluginId: string): Promise<void> {
  switch (pluginId) {
${switchCases("intake")}
    default:
      throw new Error(\`WORKSPACE_PLUGIN_REGISTER_UNKNOWN:\${pluginId}\`);
  }
}
`;
}

/**
 * @param {ReturnType<typeof discoverManifests>} selected sorted portal-register manifests
 */
export function generateHostRegisterManifest(selected) {
  const ids = selected.map((m) => m.id);
  const revision = ids.join(",");
  const idLines = ids.map((id) => `  ${JSON.stringify(id)},`).join("\n");

  return `${HOST_REGISTER_BANNER}
/** Sorted trunk plugin ids — cache bust when codegen regen changes membership. */
export const WORKSPACE_PLUGIN_REGISTER_REVISION = ${JSON.stringify(revision)};

export const WORKSPACE_PLUGIN_REGISTER_IDS = Object.freeze([
${idLines}
]) as readonly string[];
`;
}

/**
 * Flat output map for portal/host register artifacts (P5.1).
 * Gap Closure C.3c — when APPLY=1, membership follows deploy profile (asserts still use full trunk).
 * @param {ReturnType<typeof discoverManifests>} manifests
 * @param {NodeJS.ProcessEnv | Record<string, string | undefined>} [env]
 */
export function generatePortalRegisterOutputs(manifests, env = process.env) {
  const selected = filterManifestsByDeployProfile(selectPortalRegisterManifests(manifests), env);
  for (const m of selected) {
    if (m.catalogRegistrationFlow !== undefined) {
      assertCatalogRegistrationFlowManifest(m, manifests);
      assertCatalogRegistrationTransportInitializerManifest(m);
    }
  }
  /** @type {Record<string, string>} */
  const out = {};
  for (const m of selected) {
    out[portalRegisterOutputKey(m.id)] = generatePortalPluginRegister(m, manifests);
  }
  out.portalRegisterManifest = generatePortalRegisterManifest(selected);
  out.hostRegisterManifest = generateHostRegisterManifest(selected);
  return out;
}

/**
 * @param {ReturnType<typeof discoverManifests>[number]} manifest
 * @param {ReturnType<typeof discoverManifests>} allManifests
 */
export function assertCatalogRegistrationFlowManifest(manifest, allManifests) {
  const cfg = manifest.catalogRegistrationFlow;
  if (cfg === undefined) {
    return;
  }
  if (typeof cfg.surfaceExport !== "string" || cfg.surfaceExport.length === 0) {
    throw new Error(`${manifest.id}: catalogRegistrationFlow.surfaceExport is required`);
  }
  const steps = cfg.steps;
  if (steps === undefined || typeof steps !== "object") {
    throw new Error(`${manifest.id}: catalogRegistrationFlow.steps is required`);
  }
  if (steps.mode === "bundle") {
    if (typeof steps.export !== "string" || steps.export.length === 0) {
      throw new Error(
        `${manifest.id}: catalogRegistrationFlow.steps.export is required for bundle mode`
      );
    }
    return;
  }
  if (steps.mode === "compose") {
    const authSource = steps.reuseAuthStepsFrom ?? steps.reuseFrom;
    if (typeof authSource !== "string" || authSource.length === 0) {
      throw new Error(
        `${manifest.id}: catalogRegistrationFlow.steps.reuseAuthStepsFrom or reuseFrom is required for compose mode`
      );
    }
    if (authSource !== "shared") {
      const source = allManifests.find((m) => m.id === authSource);
      if (source === undefined) {
        throw new Error(
          `${manifest.id}: catalogRegistrationFlow.steps reuse source unknown workspace "${authSource}"`
        );
      }
      if (source.catalogRegistrationFlow === undefined) {
        throw new Error(
          `${manifest.id}: catalogRegistrationFlow reuse source "${authSource}" has no catalogRegistrationFlow block`
        );
      }
    }
    const components = steps.components;
    if (components === undefined || typeof components !== "object") {
      throw new Error(
        `${manifest.id}: catalogRegistrationFlow.steps.components is required for compose mode`
      );
    }
    for (const key of ["intake", "done"]) {
      if (typeof components[key] !== "string" || components[key].length === 0) {
        throw new Error(
          `${manifest.id}: catalogRegistrationFlow.steps.components.${key} is required`
        );
      }
    }
    return;
  }
  throw new Error(
    `${manifest.id}: catalogRegistrationFlow.steps.mode must be "bundle" or "compose"`
  );
}

/** @param {ReturnType<typeof discoverManifests>} manifests */
export function generateWorkspaceRegistrationFlowPlugins(manifests) {
  for (const manifest of manifests) {
    assertCatalogRegistrationFlowManifest(manifest, manifests);
  }

  const configured = manifests.filter((m) => m.catalogRegistrationFlow !== undefined);
  /** @type {Set<string>} */
  const importLines = new Set();
  /** @type {string[]} */
  const registerBlocks = [];

  for (const manifest of configured) {
    const cfg = manifest.catalogRegistrationFlow;
    const surfaceSpec = importSpecifier(manifest.package, "./catalog-registration-flow");
    importLines.add(`import { ${cfg.surfaceExport} } from "${surfaceSpec}";`);

    if (cfg.steps.mode === "bundle") {
      const stepsSpec = importSpecifier(manifest.package, "./catalog-registration-flow/react");
      importLines.add(`import { ${cfg.steps.export} } from "${stepsSpec}";`);
      registerBlocks.push(`  registerWorkspaceRegistrationFlowPlugin({
    id: ${JSON.stringify(manifest.id)},
    catalogRegistrationFlow: ${cfg.surfaceExport},
  });
  registerWorkspaceRegistrationFlowSteps(${JSON.stringify(manifest.id)}, ${cfg.steps.export});`);
      continue;
    }

    const authSource = cfg.steps.reuseAuthStepsFrom ?? cfg.steps.reuseFrom;
    const localSpec = importSpecifier(manifest.package, "./catalog-registration-flow/react");
    importLines.add(
      `import { ${cfg.steps.components.intake}, ${cfg.steps.components.done} } from "${localSpec}";`
    );

    if (authSource === "shared") {
      importLines.add(
        `import { CatalogRegistrationOtpStep, CatalogRegistrationPhoneStep, CatalogRegistrationProfileStep } from "@app-tour/catalog-registration-flow-ui/react";`
      );
      registerBlocks.push(`  registerWorkspaceRegistrationFlowPlugin({
    id: ${JSON.stringify(manifest.id)},
    catalogRegistrationFlow: ${cfg.surfaceExport},
  });
  registerWorkspaceRegistrationFlowSteps(${JSON.stringify(manifest.id)}, {
    phone: CatalogRegistrationPhoneStep,
    otp: CatalogRegistrationOtpStep,
    profile: CatalogRegistrationProfileStep,
    intake: ${cfg.steps.components.intake},
    done: ${cfg.steps.components.done},
  });`);
      continue;
    }

    const source = manifests.find((m) => m.id === authSource);
    if (source === undefined) {
      throw new Error(`${manifest.id}: internal error resolving auth step reuse source`);
    }
    const reuseSpec = importSpecifier(source.package, "./catalog-registration-flow/react");
    importLines.add(
      `import { DenaliOtpStep, DenaliPhoneStep, DenaliProfileStep } from "${reuseSpec}";`
    );
    registerBlocks.push(`  registerWorkspaceRegistrationFlowPlugin({
    id: ${JSON.stringify(manifest.id)},
    catalogRegistrationFlow: ${cfg.surfaceExport},
  });
  registerWorkspaceRegistrationFlowSteps(${JSON.stringify(manifest.id)}, {
    phone: DenaliPhoneStep,
    otp: DenaliOtpStep,
    profile: DenaliProfileStep,
    intake: ${cfg.steps.components.intake},
    done: ${cfg.steps.components.done},
  });`);
  }

  return `${BANNER}
import { registerWorkspaceRegistrationFlowPlugin } from "@app-tour/workspace-sdk";
${[...importLines].sort().join("\n")}

import { registerWorkspaceRegistrationFlowSteps } from "./registration-flow";

export function registerWorkspaceRegistrationFlowPluginsFromManifest(): void {
${registerBlocks.join("\n\n")}
}
`;
}

/**
 * @param {ReturnType<typeof discoverManifests>[number]} manifest
 */
export function assertCatalogRegistrationTransportInitializerManifest(manifest) {
  const cfg = manifest.catalogRegistrationFlow;
  if (cfg === undefined || cfg.transportInitializerExport === undefined) {
    return;
  }
  if (
    typeof cfg.transportInitializerExport !== "string" ||
    cfg.transportInitializerExport.length === 0
  ) {
    throw new Error(
      `${manifest.id}: catalogRegistrationFlow.transportInitializerExport must be a non-empty string`
    );
  }
}

/** @param {ReturnType<typeof discoverManifests>} manifests */
export function generateWorkspaceRegistrationTransportInitializers(manifests) {
  for (const manifest of manifests) {
    assertCatalogRegistrationTransportInitializerManifest(manifest);
  }

  /** @type {Set<string>} */
  const importLines = new Set();
  /** @type {string[]} */
  const callLines = [];

  for (const manifest of manifests) {
    const exportName = manifest.catalogRegistrationFlow?.transportInitializerExport;
    if (exportName === undefined) {
      continue;
    }
    const spec = importSpecifier(manifest.package, "./catalog-registration-flow");
    importLines.add(`import { ${exportName} } from "${spec}";`);
    callLines.push(`  ${exportName}();`);
  }

  const body =
    callLines.length > 0
      ? callLines.join("\n")
      : "  // no workspace declares catalogRegistrationFlow.transportInitializerExport";

  return `${BANNER}
${[...importLines].sort().join("\n")}

export function registerWorkspaceRegistrationTransportInitializersFromManifest(): void {
${body}
}
`;
}

export function generateWorkspaceIntakePluginBootstrap(manifests) {
  const importLines = manifests.map((m) => {
    const spec = importSpecifier(m.package, m.plugin.entry);
    return `import { ${m.plugin.export} } from "${spec}";`;
  });

  const pluginCalls = manifests.map((m) => `    ${m.plugin.export}(),`).join("\n");

  return `${BANNER}
import { registerWorkspaceIntakePlugin } from "@app-tour/workspace-sdk";
${importLines.join("\n")}

export function registerWorkspaceIntakePluginsFromManifest(): void {
  for (const plugin of [
${pluginCalls}
  ]) {
    if (plugin.catalogIntake === undefined) {
      continue;
    }
    registerWorkspaceIntakePlugin({
      id: plugin.id,
      catalogIntake: plugin.catalogIntake,
    });
  }
}
`;
}
