/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { MemberProfileFieldId } from "./member-profile-field-id";

export type GeneratedMemberProfileCapabilities = Readonly<{
  readonly editableFields: readonly MemberProfileFieldId[];
  readonly readOnlyFields: readonly MemberProfileFieldId[];
  readonly mobileChangeViaOtp?: boolean;
  readonly sections?: readonly Readonly<{
    readonly id: string;
    readonly fields: readonly MemberProfileFieldId[];
  }>[];
}>;

/** Portal member profile capability rows — derived from workspace.manifest.json memberProfile. */
export const WORKSPACE_MEMBER_PROFILE_CAPABILITIES: Readonly<
  Record<string, GeneratedMemberProfileCapabilities>
> = Object.freeze({
  "cert-club": Object.freeze({
    editableFields: Object.freeze(["displayName"] as const satisfies readonly MemberProfileFieldId[]),
    readOnlyFields: Object.freeze(["email"] as const satisfies readonly MemberProfileFieldId[]),
    sections: Object.freeze([
      Object.freeze({
        id: "identity",
        fields: Object.freeze(["displayName","email"] as const satisfies readonly MemberProfileFieldId[]),
      }),
    ]),
    mobileChangeViaOtp: true
  }),
  "cert-events": Object.freeze({
    editableFields: Object.freeze(["displayName"] as const satisfies readonly MemberProfileFieldId[]),
    readOnlyFields: Object.freeze(["email"] as const satisfies readonly MemberProfileFieldId[]),
    sections: Object.freeze([
      Object.freeze({
        id: "identity",
        fields: Object.freeze(["displayName","email"] as const satisfies readonly MemberProfileFieldId[]),
      }),
    ])
  }),
  "denali": Object.freeze({
    editableFields: Object.freeze(["displayName","email","gender","nationalId","fatherName","birthDate"] as const satisfies readonly MemberProfileFieldId[]),
    readOnlyFields: Object.freeze(["mobile"] as const satisfies readonly MemberProfileFieldId[]),
    sections: Object.freeze([
      Object.freeze({
        id: "identity",
        fields: Object.freeze(["displayName","mobile","email","gender"] as const satisfies readonly MemberProfileFieldId[]),
      }),
      Object.freeze({
        id: "participant",
        fields: Object.freeze(["nationalId","fatherName","birthDate"] as const satisfies readonly MemberProfileFieldId[]),
      }),
    ]),
    mobileChangeViaOtp: true
  }),
  "guest-club": Object.freeze({
    editableFields: Object.freeze(["displayName"] as const satisfies readonly MemberProfileFieldId[]),
    readOnlyFields: Object.freeze(["email"] as const satisfies readonly MemberProfileFieldId[]),
    sections: Object.freeze([
      Object.freeze({
        id: "identity",
        fields: Object.freeze(["displayName","email"] as const satisfies readonly MemberProfileFieldId[]),
      }),
    ])
  }),
  "harbor": Object.freeze({
    editableFields: Object.freeze(["displayName"] as const satisfies readonly MemberProfileFieldId[]),
    readOnlyFields: Object.freeze(["email"] as const satisfies readonly MemberProfileFieldId[]),
    sections: Object.freeze([
      Object.freeze({
        id: "identity",
        fields: Object.freeze(["displayName","email"] as const satisfies readonly MemberProfileFieldId[]),
      }),
    ])
  }),
  "profile-cert": Object.freeze({
    editableFields: Object.freeze(["displayName"] as const satisfies readonly MemberProfileFieldId[]),
    readOnlyFields: Object.freeze(["email","mobile"] as const satisfies readonly MemberProfileFieldId[]),
    sections: Object.freeze([
      Object.freeze({
        id: "identity",
        fields: Object.freeze(["displayName","email"] as const satisfies readonly MemberProfileFieldId[]),
      }),
    ])
  }),
  "urban": Object.freeze({
    editableFields: Object.freeze(["displayName"] as const satisfies readonly MemberProfileFieldId[]),
    readOnlyFields: Object.freeze(["email"] as const satisfies readonly MemberProfileFieldId[]),
    sections: Object.freeze([
      Object.freeze({
        id: "identity",
        fields: Object.freeze(["displayName","email"] as const satisfies readonly MemberProfileFieldId[]),
      }),
    ])
  }),
});
