/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Phase 3 AppShell nav link — href + tours.shell message key (Wave D.c). */
export type OperatorShellNavLink = {
  readonly href: string;
  readonly labelKey: string;
};

/** pluginId → optional Phase 3 header links from operatorShell.phase3NavLinks. */
export const WORKSPACE_OPERATOR_SHELL_NAV: Readonly<
  Record<string, readonly OperatorShellNavLink[]>
> = Object.freeze({
  "urban": Object.freeze([
    Object.freeze({ href: "/catalog", labelKey: "catalog" }),
    Object.freeze({ href: "/settings/workspace-owner", labelKey: "workspaceOwnerSettings" }),
  ]),
});

export function resolveOperatorShellNavLinks(pluginId: string): readonly OperatorShellNavLink[] {
  return WORKSPACE_OPERATOR_SHELL_NAV[pluginId] ?? [];
}
