/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WizardLabelResolver } from "@/wizard/wizard-surface-types";

export const WORKSPACE_WIZARD_I18N_NAMESPACES = ["wizard","denali","urban"] as const;

const LABEL_RESOLVER_LOADERS: Readonly<
  Record<string, () => Promise<WizardLabelResolver>>
> = Object.freeze({
  "denali": async () => {
    const mod = await import("@app-tour/workspace-denali/host/ui/field-label-resolver");
    return mod.createDenaliFieldLabelResolver();
  },
});

const labelResolverCache = new Map<string, WizardLabelResolver>();

/** Warm cache via dynamic import (no static product package fan-in). */
export async function ensureGeneratedLabelResolver(
  surfaceId: string | undefined
): Promise<WizardLabelResolver | null> {
  if (surfaceId == null || surfaceId.trim().length === 0) {
    return null;
  }
  const cached = labelResolverCache.get(surfaceId);
  if (cached != null) {
    return cached;
  }
  const load = LABEL_RESOLVER_LOADERS[surfaceId];
  if (load == null) {
    return null;
  }
  const resolver = await load();
  labelResolverCache.set(surfaceId, resolver);
  return resolver;
}

/** Sync read of warm cache — call ensureGeneratedLabelResolver first for correct labels. */
export function resolveGeneratedLabelResolver(
  surfaceId: string | undefined
): WizardLabelResolver | null {
  if (surfaceId == null || surfaceId.trim().length === 0) {
    return null;
  }
  return labelResolverCache.get(surfaceId) ?? null;
}
