/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Plugin ids that use workspace-specific extended create chrome (Phase 14.3). */
export const WORKSPACE_WIZARD_EXTENDED_CREATE_PLUGIN_IDS = new Set<string>([
  "denali",
]);

/** Plugin-specific tenant brand fallback marks (manifest wizardCreate.customBrandFallbackMark). */
export const WORKSPACE_WIZARD_CUSTOM_BRAND_FALLBACK_MARKS = Object.freeze({

}) as Readonly<Record<string, string>>;
