/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Manifest-driven mediaRouteKey → web BFF path (legacy alias or neutral). */
export const WIZARD_MEDIA_ROUTE_BFF_PATHS = Object.freeze({
  "wizard-photos": "/api/tours/wizard-photos",
}) as Readonly<Record<string, string>>;

export function isKnownWizardMediaRouteBffKey(mediaRouteKey: string): boolean {
  return mediaRouteKey.trim() in WIZARD_MEDIA_ROUTE_BFF_PATHS;
}
