/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

"use client";

import { useTranslations } from "next-intl";
import { useMemo } from "react";

import { WORKSPACE_WIZARD_I18N_NAMESPACES } from "./wizard-label-bindings.generated";

/** Codegen hook map — one useTranslations call per WORKSPACE_WIZARD_I18N_NAMESPACES entry. */
export function useGeneratedWorkspaceWizardTranslators() {
  const t_wizard = useTranslations("wizard");
  const t_urban = useTranslations("urban");
  return useMemo(
    () =>
      ({
      "wizard": t_wizard,
      "urban": t_urban,
      }) as const satisfies Partial<
        Record<(typeof WORKSPACE_WIZARD_I18N_NAMESPACES)[number], ReturnType<typeof useTranslations>>
      >,
    [t_wizard, t_urban]
  );
}
