/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WizardMediaBackendPaths = {
  readonly upload: string;
  readonly signedUrl: string;
};

/** Manifest-driven mediaRouteKey → API backend proxy paths (server-only). */
export const WIZARD_MEDIA_ROUTE_BACKEND_PATHS = Object.freeze({
  "wizard-photos": Object.freeze({
    upload: "/tours/wizard-photos",
    signedUrl: "/tours/wizard-photos/url",
  }),
}) as Readonly<Record<string, WizardMediaBackendPaths>>;

export function isKnownWizardMediaRouteBackendKey(mediaRouteKey: string): boolean {
  return mediaRouteKey.trim() in WIZARD_MEDIA_ROUTE_BACKEND_PATHS;
}
