/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WizardLabelResolver } from "@/wizard/wizard-surface-types";

export const WORKSPACE_WIZARD_I18N_NAMESPACES = ["wizard","urban"] as const;

export function resolveGeneratedLabelResolver(
  _surfaceId: string | undefined
): WizardLabelResolver | null {
  return null;
}
