/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WizardLabelResolver } from "@/wizard/wizard-surface-types";
import { createDenaliFieldLabelResolver as label_denali } from "@app-tour/workspace-denali/host/ui/field-label-resolver";

export const WORKSPACE_WIZARD_I18N_NAMESPACES = ["wizard","denali","urban"] as const;

const LABEL_RESOLVERS: Readonly<Record<string, WizardLabelResolver>> = Object.freeze({
  "denali": label_denali(),
});

export function resolveGeneratedLabelResolver(
  surfaceId: string | undefined
): WizardLabelResolver | null {
  if (surfaceId == null || surfaceId.trim().length === 0) {
    return null;
  }
  return LABEL_RESOLVERS[surfaceId] ?? null;
}
