/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WizardCompositeSurface, WizardReviewSurface } from "@/wizard/wizard-surface-types";

export function resolveGeneratedCompositeSurface(
  _surfaceId: string | undefined
): WizardCompositeSurface | null {
  return null;
}

export function resolveGeneratedReviewSurface(
  _surfaceId: string | undefined
): WizardReviewSurface | null {
  return null;
}
