/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WizardMediaBackendPaths = {
  readonly upload: string;
  readonly signedUrl: string;
};

/** Manifest-driven mediaRouteKey → API backend proxy paths (private; Phase 4f). */
const WIZARD_MEDIA_ROUTE_BACKEND_PATHS = Object.freeze({
  "wizard-photos": Object.freeze({
    upload: "/tours/wizard-photos",
    signedUrl: "/tours/wizard-photos/url",
  }),
}) as Readonly<Record<string, WizardMediaBackendPaths>>;

export function isKnownWizardMediaRouteBackendKey(mediaRouteKey: string): boolean {
  return mediaRouteKey.trim() in WIZARD_MEDIA_ROUTE_BACKEND_PATHS;
}

/** Manifest backend paths for key, if declared. */
export function lookupWizardMediaRouteBackendPaths(
  mediaRouteKey: string
): WizardMediaBackendPaths | undefined {
  return WIZARD_MEDIA_ROUTE_BACKEND_PATHS[mediaRouteKey.trim()];
}
