/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Manifest + platform wizard message namespaces (private; Phase 4i / 4aq; slimmed Phase 4bh). */
const WORKSPACE_WIZARD_I18N_NAMESPACES = ["wizard","denali","urban"] as const;

export type WorkspaceWizardI18nNamespace = (typeof WORKSPACE_WIZARD_I18N_NAMESPACES)[number];

export function isWorkspaceWizardI18nNamespace(
  value: string
): value is WorkspaceWizardI18nNamespace {
  return (WORKSPACE_WIZARD_I18N_NAMESPACES as readonly string[]).includes(value);
}

/** Declared wizard i18n namespaces (tests / label resolvers). */
export function listWorkspaceWizardI18nNamespaces(): readonly WorkspaceWizardI18nNamespace[] {
  return WORKSPACE_WIZARD_I18N_NAMESPACES;
}
