/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspacePlugin } from "@app-tour/workspace-sdk";

const pluginLoadCache = new Map<string, Promise<WorkspacePlugin>>();

export async function loadWorkspacePluginByIdFromRegistry(
  pluginId: string
): Promise<WorkspacePlugin> {
  const cached = pluginLoadCache.get(pluginId);
  if (cached) return cached;

  const loadPromise = (async () => {
    switch (pluginId) {
    case "denali": {
      const mod = await import("@app-tour/workspace-denali/plugin");
      return mod.getDenaliWorkspacePlugin();
    }
    case "starter": {
      const mod = await import("@app-tour/workspace-starter");
      return mod.getStarterWorkspacePlugin();
    }
    case "urban": {
      const mod = await import("@app-tour/workspace-urban/plugin");
      return mod.getUrbanWorkspacePlugin();
    }
      default:
        throw new Error(`WORKSPACE_PLUGIN_NOT_FOUND:${pluginId}`);
    }
  })();

  pluginLoadCache.set(pluginId, loadPromise);
  return loadPromise;
}
