/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { denaliWizardTemplatePresetSurface as wizard_template_preset_denali } from "@app-tour/workspace-denali/settings/wizard-template-preset-surface";

export function loadFullWizardTemplatePreset(
  pluginId: string,
  seedLabel?: string
): Promise<import("@/features/settings/wizard-template-types").WizardTemplatePayload> {
  if (pluginId !== "denali") {
    return Promise.reject(new Error(`No wizard template preset for plugin: ${pluginId}`));
  }
  return Promise.resolve(wizard_template_preset_denali.buildFullTemplatePreset(seedLabel));
}
