/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspacePricingWizardCompositeBinding } from "@app-tour/workspace-sdk/pricing";
import { denaliPricingWizardCompositeBinding as denali_pricing_wizard_composite } from "@app-tour/workspace-denali/host/composites/denali-pricing-composite-binding";

export type WorkspacePricingWizardCompositeBindingEntry = {
  readonly workspaceType: string;
  readonly wizardCompositeBinding: WorkspacePricingWizardCompositeBinding;
};

export const WORKSPACE_PRICING_WIZARD_COMPOSITE_BINDINGS: readonly WorkspacePricingWizardCompositeBindingEntry[] = [
  {
    workspaceType: "denali",
    wizardCompositeBinding: denali_pricing_wizard_composite,
  },
] as const;

export function resolveWorkspacePricingWizardCompositeBinding(
  workspaceType: string
): WorkspacePricingWizardCompositeBinding | undefined {
  const binding = WORKSPACE_PRICING_WIZARD_COMPOSITE_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.wizardCompositeBinding;
}
