/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { ComponentType, ReactNode } from "react";

/** Gap Closure B.10 — shell-local type mirrors (no static product import). */
export type DenaliEditTourRemoteDraftIdentity = {
  readonly namespace: string;
  readonly draftKey: string;
};

export type DenaliFlatEditTourHttpFailure = {
  readonly ok: false;
  readonly kind: "not-found" | "error";
  readonly code: string;
};

export type DenaliWizardCatalogPrefetch = {
  readonly initialLocationsResponse: unknown | null;
};

export type ExposureCatalogFieldForLocalization = {
  readonly id: string;
  readonly canonicalPath: string;
  readonly adminLabel?: string;
};

type DenaliWizardCatalogPrefetchProviderProps = {
  readonly children: ReactNode;
  readonly initialLocationsResponse?: unknown | null;
};

/** Known product clone-support literal (matches workspace-denali draft binding SOT). */
export const DENALI_CREATE_TOUR_SUPPORTS_CLONE = true as const;

type DenaliHostAdaptersSurface = {
  readonly buildDenaliWizardFreshStartMeta: (...args: any[]) => any;
  readonly buildDenaliWizardStepZeroMeta: (...args: any[]) => any;
  readonly buildDenaliCreateTourDiscardRemoteDraftInput: (...args: any[]) => any;
  readonly denaliCreateTourRemoteDraftIdentity: (...args: any[]) => any;
  readonly prepareDenaliCreateTourFreshStartEnvelope: (...args: any[]) => any;
  readonly denaliEditTourRemoteDraftIdentity: (...args: any[]) => DenaliEditTourRemoteDraftIdentity;
  readonly buildDenaliFlatEditTourLoadSuccess: (...args: any[]) => any;
  readonly denaliFlatEditHydratorUnavailableResult: (...args: any[]) => any;
  readonly finalizeDenaliFlatEditTourLoad: (...args: any[]) => any;
  readonly mapDenaliFlatEditTourHttpStatus: (
    status: number
  ) => DenaliFlatEditTourHttpFailure | null;
  readonly DenaliWizardCatalogPrefetchProvider: ComponentType<DenaliWizardCatalogPrefetchProviderProps>;
  readonly useDenaliWizardCatalogPrefetch: () => DenaliWizardCatalogPrefetch;
  readonly readActiveDestinationIds: (...args: any[]) => any;
  readonly readActiveEquipmentIds: (...args: any[]) => any;
  readonly readActiveThemeIds: (...args: any[]) => any;
  readonly localizeExposureCatalogFields: (...args: any[]) => any;
  readonly buildDenaliFlatEditMetaLine: (...args: any[]) => any;
  readonly localizeDenaliValidationIssueMessage: (...args: any[]) => any;
  readonly resolveActiveCatalogIdsFromResourcePayloads: (...args: any[]) => any;
};

let denaliHostAdapters: DenaliHostAdaptersSurface | null = null;

/** Warm full Denali host-adapter surface via dynamic import (Gap Closure B.10). */
export async function ensureDenaliHostAdapters(): Promise<DenaliHostAdaptersSurface> {
  if (denaliHostAdapters != null) {
    return denaliHostAdapters;
  }
  const [
    draftMod,
    loadResultMod,
    httpStatusMod,
    prefetchMod,
    sanitizeMod,
    exposureMod,
    metaMod,
    localizeMod,
    catalogMod,
  ] = await Promise.all([
    import("@app-tour/workspace-denali/host/draft"),
    import("@app-tour/workspace-denali/host/ui/chrome/build-denali-flat-edit-tour-load-result"),
    import("@app-tour/workspace-denali/host/ui/chrome/map-denali-flat-edit-tour-http-status"),
    import("@app-tour/workspace-denali/host/ui/hooks/denali-wizard-catalog-prefetch-context"),
    import("@app-tour/workspace-denali/host/wizard/catalog-sanitize"),
    import("@app-tour/workspace-denali/host/ui/adapters/localize-exposure-catalog-fields"),
    import("@app-tour/workspace-denali/host/ui/chrome/build-denali-flat-edit-meta-line"),
    import("@app-tour/workspace-denali/host/wizard/localize-validation-message"),
    import("@app-tour/workspace-denali/host/ui/adapters/read-active-catalog-ids-from-payload"),
  ]);
  denaliHostAdapters = Object.freeze({
    buildDenaliWizardFreshStartMeta: draftMod.buildDenaliWizardFreshStartMeta,
    buildDenaliWizardStepZeroMeta: draftMod.buildDenaliWizardStepZeroMeta,
    buildDenaliCreateTourDiscardRemoteDraftInput:
      draftMod.buildDenaliCreateTourDiscardRemoteDraftInput,
    denaliCreateTourRemoteDraftIdentity: draftMod.denaliCreateTourRemoteDraftIdentity,
    prepareDenaliCreateTourFreshStartEnvelope: draftMod.prepareDenaliCreateTourFreshStartEnvelope,
    denaliEditTourRemoteDraftIdentity: draftMod.denaliEditTourRemoteDraftIdentity,
    buildDenaliFlatEditTourLoadSuccess: loadResultMod.buildDenaliFlatEditTourLoadSuccess,
    denaliFlatEditHydratorUnavailableResult: loadResultMod.denaliFlatEditHydratorUnavailableResult,
    finalizeDenaliFlatEditTourLoad: loadResultMod.finalizeDenaliFlatEditTourLoad,
    mapDenaliFlatEditTourHttpStatus: httpStatusMod.mapDenaliFlatEditTourHttpStatus,
    DenaliWizardCatalogPrefetchProvider: prefetchMod.DenaliWizardCatalogPrefetchProvider,
    useDenaliWizardCatalogPrefetch: prefetchMod.useDenaliWizardCatalogPrefetch,
    readActiveDestinationIds: sanitizeMod.readActiveDestinationIds,
    readActiveEquipmentIds: sanitizeMod.readActiveEquipmentIds,
    readActiveThemeIds: sanitizeMod.readActiveThemeIds,
    localizeExposureCatalogFields: exposureMod.localizeExposureCatalogFields,
    buildDenaliFlatEditMetaLine: metaMod.buildDenaliFlatEditMetaLine,
    localizeDenaliValidationIssueMessage: localizeMod.localizeDenaliValidationIssueMessage,
    resolveActiveCatalogIdsFromResourcePayloads:
      catalogMod.resolveActiveCatalogIdsFromResourcePayloads,
  });
  return denaliHostAdapters;
}

/** @deprecated Prefer {@link ensureDenaliHostAdapters} (B.10). */
export async function ensureDenaliHostAdapterCountedFns(): Promise<DenaliHostAdaptersSurface> {
  return ensureDenaliHostAdapters();
}

function requireDenaliHostAdapters(): DenaliHostAdaptersSurface {
  if (denaliHostAdapters == null) {
    throw new Error("Denali host adapters cold (call ensureDenaliHostAdapters first)");
  }
  return denaliHostAdapters;
}

/** Sync Provider when warm; null when cold (CatalogShell self-warms). */
export function resolveDenaliWizardCatalogPrefetchProvider(): ComponentType<DenaliWizardCatalogPrefetchProviderProps> | null {
  return denaliHostAdapters?.DenaliWizardCatalogPrefetchProvider ?? null;
}

export function buildDenaliWizardFreshStartMeta(...args: any[]): any {
  return requireDenaliHostAdapters().buildDenaliWizardFreshStartMeta(...args);
}

export function buildDenaliWizardStepZeroMeta(...args: any[]): any {
  return requireDenaliHostAdapters().buildDenaliWizardStepZeroMeta(...args);
}

export function buildDenaliCreateTourDiscardRemoteDraftInput(...args: any[]): any {
  return requireDenaliHostAdapters().buildDenaliCreateTourDiscardRemoteDraftInput(...args);
}

export function denaliCreateTourRemoteDraftIdentity(...args: any[]): any {
  return requireDenaliHostAdapters().denaliCreateTourRemoteDraftIdentity(...args);
}

export function prepareDenaliCreateTourFreshStartEnvelope(...args: any[]): any {
  return requireDenaliHostAdapters().prepareDenaliCreateTourFreshStartEnvelope(...args);
}

export function denaliEditTourRemoteDraftIdentity(...args: any[]): DenaliEditTourRemoteDraftIdentity {
  return requireDenaliHostAdapters().denaliEditTourRemoteDraftIdentity(...args);
}

export function buildDenaliFlatEditTourLoadSuccess(...args: any[]): any {
  return requireDenaliHostAdapters().buildDenaliFlatEditTourLoadSuccess(...args);
}

export function denaliFlatEditHydratorUnavailableResult(...args: any[]): any {
  return requireDenaliHostAdapters().denaliFlatEditHydratorUnavailableResult(...args);
}

export function finalizeDenaliFlatEditTourLoad(...args: any[]): any {
  return requireDenaliHostAdapters().finalizeDenaliFlatEditTourLoad(...args);
}

export function mapDenaliFlatEditTourHttpStatus(
  status: number
): DenaliFlatEditTourHttpFailure | null {
  return requireDenaliHostAdapters().mapDenaliFlatEditTourHttpStatus(status);
}

export function readActiveDestinationIds(...args: any[]): any {
  return requireDenaliHostAdapters().readActiveDestinationIds(...args);
}

export function readActiveEquipmentIds(...args: any[]): any {
  return requireDenaliHostAdapters().readActiveEquipmentIds(...args);
}

export function readActiveThemeIds(...args: any[]): any {
  return requireDenaliHostAdapters().readActiveThemeIds(...args);
}

export function localizeExposureCatalogFields<T extends ExposureCatalogFieldForLocalization>(
  fields: readonly T[],
  translateWizard: (...args: any[]) => any
): readonly T[] {
  return requireDenaliHostAdapters().localizeExposureCatalogFields(fields, translateWizard) as readonly T[];
}

export function buildDenaliFlatEditMetaLine(...args: any[]): any {
  return requireDenaliHostAdapters().buildDenaliFlatEditMetaLine(...args);
}

export function localizeDenaliValidationIssueMessage(...args: any[]): any {
  return requireDenaliHostAdapters().localizeDenaliValidationIssueMessage(...args);
}

export function resolveActiveCatalogIdsFromResourcePayloads(...args: any[]): any {
  return requireDenaliHostAdapters().resolveActiveCatalogIdsFromResourcePayloads(...args);
}

/** Gap Closure B.20 — product-blind aliases for shell facades (token ratchet). */
export const ensureWizardHostAdapters = ensureDenaliHostAdapters;
export const resolveWizardCatalogPrefetchProvider = resolveDenaliWizardCatalogPrefetchProvider;
export const buildWizardFreshStartMeta = buildDenaliWizardFreshStartMeta;
export const buildWizardStepZeroMeta = buildDenaliWizardStepZeroMeta;
export const buildCreateTourDiscardRemoteDraftInput = buildDenaliCreateTourDiscardRemoteDraftInput;
export const CREATE_TOUR_SUPPORTS_CLONE = DENALI_CREATE_TOUR_SUPPORTS_CLONE;
export const createTourRemoteDraftIdentity = denaliCreateTourRemoteDraftIdentity;
export const prepareCreateTourFreshStartEnvelope = prepareDenaliCreateTourFreshStartEnvelope;
export const editTourRemoteDraftIdentity = denaliEditTourRemoteDraftIdentity;
export const buildFlatEditMetaLine = buildDenaliFlatEditMetaLine;
export const finalizeFlatEditTourLoad = finalizeDenaliFlatEditTourLoad;
export const mapFlatEditTourHttpStatus = mapDenaliFlatEditTourHttpStatus;
export const localizeWizardValidationIssueMessage = localizeDenaliValidationIssueMessage;
/** Wire error code value retained; shell imports the neutral constant name only. */
export const WIZARD_RULES_NOT_READY_CODE = "DENALI_RULES_NOT_READY";
