/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { ComponentType } from "react";

export type WizardCreateViewSurface = {
  readonly CreateTourWizardView: ComponentType<any>;
};

const WIZARD_CREATE_VIEW_LOADERS: Readonly<
  Record<string, () => Promise<WizardCreateViewSurface>>
> = Object.freeze({
  "denali": async () => {
    const mod = await import("@app-tour/workspace-denali/host/ui/chrome/wizard-create-view-surface");
    return mod.denaliWizardCreateViewSurface as WizardCreateViewSurface;
  },
});

const wizardCreateViewCache = new Map<string, WizardCreateViewSurface>();

/** Warm create wizard React view via dynamic import (no static product fan-in). */
export async function ensureWizardCreateViewSurface(
  pluginId: string
): Promise<WizardCreateViewSurface | null> {
  if (pluginId.trim().length === 0) {
    return null;
  }
  const cached = wizardCreateViewCache.get(pluginId);
  if (cached != null) {
    return cached;
  }
  const load = WIZARD_CREATE_VIEW_LOADERS[pluginId];
  if (load == null) {
    return null;
  }
  const surface = await load();
  wizardCreateViewCache.set(pluginId, surface);
  return surface;
}

/** Sync read of warm cache — call ensureWizardCreateViewSurface first. */
export function resolveWizardCreateViewSurface(
  pluginId: string
): WizardCreateViewSurface | null {
  return wizardCreateViewCache.get(pluginId) ?? null;
}
