/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { SettingsExposureSurfacesUiSurface } from "@/features/settings/settings-exposure-surfaces-ui-types";

export async function ensureSettingsExposureSurfacesUiSurface(
  _pluginId: string
): Promise<SettingsExposureSurfacesUiSurface | null> {
  return null;
}

export function resolveSettingsExposureSurfacesUiSurface(
  _pluginId: string
): SettingsExposureSurfacesUiSurface | null {
  return null;
}
