/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { SettingsModuleMetadata } from "@/features/settings/settings-module-types";
import { DENALI_BACKEND_REQUIRED_MODULE_IDS } from "@/features/settings/denali-required-settings-modules.generated";
import { DENALI_FALLBACK_SETTINGS_MODULES } from "@/features/settings/denali-fallback-settings-modules";

export type SettingsHubFallbackPolicy = {
  readonly requiredModuleIds: readonly string[];
  readonly fallbackModules: Readonly<Record<string, SettingsModuleMetadata>>;
};

const SETTINGS_HUB_FALLBACK_POLICIES = Object.freeze({
  "denali": Object.freeze({
    requiredModuleIds: DENALI_BACKEND_REQUIRED_MODULE_IDS,
    fallbackModules: DENALI_FALLBACK_SETTINGS_MODULES,
  }),
});

export function resolveSettingsHubFallbackPolicy(pluginId: string): SettingsHubFallbackPolicy | null {
  return SETTINGS_HUB_FALLBACK_POLICIES[pluginId as keyof typeof SETTINGS_HUB_FALLBACK_POLICIES] ?? null;
}

export { DENALI_BACKEND_REQUIRED_MODULE_IDS };
