/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { TourActionSubmitErrorPayload } from "@app-tour/workspace-denali/ui/logic/tour-action-submit-error-codec";
import { denaliTourActionSubmitCodec as codec_denali } from "@app-tour/workspace-denali/ui/logic/tour-action-submit-codec-surface";

const TOUR_ACTION_SUBMIT_CODECS = Object.freeze({
  "denali": codec_denali,
});

export type { TourActionSubmitErrorPayload };

export function encodeTourActionSubmitErrorForPlugin(
  pluginId: string,
  payload: TourActionSubmitErrorPayload
): string {
  const codec = TOUR_ACTION_SUBMIT_CODECS[pluginId as keyof typeof TOUR_ACTION_SUBMIT_CODECS];
  if (codec == null) {
    throw new Error(`No tour action submit codec for plugin: ${pluginId}`);
  }
  return codec.encode(payload);
}

export function decodeTourActionSubmitError(
  raw: string
): TourActionSubmitErrorPayload | null {
  for (const codec of Object.values(TOUR_ACTION_SUBMIT_CODECS)) {
    const decoded = codec.decode(raw);
    if (decoded != null) {
      return decoded;
    }
  }
  return null;
}

/** @deprecated Use encodeTourActionSubmitErrorForPlugin — retained for tests */
export function encodeTourActionSubmitError(
  payload: TourActionSubmitErrorPayload
): string {
  return codec_denali.encode(payload);
}
