/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Shell-local wire payload — do not import product package types (Gap Closure B.4). */
export type TourActionSubmitErrorPayload = {
  readonly status: number;
  readonly code: string;
  readonly message: string;
  readonly correlationId?: string;
};

type TourActionSubmitCodec = {
  readonly encode: (payload: TourActionSubmitErrorPayload) => string;
  readonly decode: (raw: string) => TourActionSubmitErrorPayload | null;
};

const TOUR_ACTION_SUBMIT_CODECS_LOADERS: Readonly<
  Record<string, () => Promise<TourActionSubmitCodec>>
> = Object.freeze({
  "denali": async () => {
    const mod = await import("@app-tour/workspace-denali/host/ui/logic/tour-action-submit-codec-surface");
    return mod.denaliTourActionSubmitCodec;
  },
});

const TOUR_ACTION_SUBMIT_CODECS_CACHE = new Map<string, TourActionSubmitCodec>();

export async function ensureTourActionSubmitCodec(
  pluginId: string
): Promise<TourActionSubmitCodec | null> {
  if (pluginId.trim().length === 0) {
    return null;
  }
  const cached = TOUR_ACTION_SUBMIT_CODECS_CACHE.get(pluginId);
  if (cached != null) {
    return cached;
  }
  const load = TOUR_ACTION_SUBMIT_CODECS_LOADERS[pluginId];
  if (load == null) {
    return null;
  }
  const codec = await load();
  TOUR_ACTION_SUBMIT_CODECS_CACHE.set(pluginId, codec);
  return codec;
}

export async function ensureAllTourActionSubmitCodecs(): Promise<void> {
  await Promise.all(
    ["denali"].map((pluginId) => ensureTourActionSubmitCodec(pluginId))
  );
}

export function encodeTourActionSubmitErrorForPlugin(
  pluginId: string,
  payload: TourActionSubmitErrorPayload
): string {
  const codec = TOUR_ACTION_SUBMIT_CODECS_CACHE.get(pluginId);
  if (codec == null) {
    throw new Error(`No tour action submit codec for plugin: ${pluginId} (call ensureTourActionSubmitCodec first)`);
  }
  return codec.encode(payload);
}

export function decodeTourActionSubmitError(
  raw: string
): TourActionSubmitErrorPayload | null {
  for (const codec of TOUR_ACTION_SUBMIT_CODECS_CACHE.values()) {
    const decoded = codec.decode(raw);
    if (decoded != null) {
      return decoded;
    }
  }
  return null;
}

/** @deprecated Use encodeTourActionSubmitErrorForPlugin after ensureTourActionSubmitCodec. */
export function encodeTourActionSubmitError(
  payload: TourActionSubmitErrorPayload
): string {
  return encodeTourActionSubmitErrorForPlugin("denali", payload);
}
