/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { ComponentType } from "react";

export type OperatorUiComponentsSurface = {
  readonly TimeInput: ComponentType<any>;
  readonly DifficultyRangeSlider: ComponentType<any>;
  readonly LocationPickerMap: ComponentType<any>;
  readonly LocationPickerMapInner: ComponentType<any>;
  readonly ensureLeafletDefaultIcon: () => void;
  readonly WizardDatetimePicker: ComponentType<any>;
};

const OPERATOR_UI_LOADERS: Readonly<
  Record<string, () => Promise<OperatorUiComponentsSurface>>
> = Object.freeze({
  "denali": async () => {
    const mod = await import("@app-tour/workspace-denali/host/ui/operator-ui-components-surface");
    return mod.denaliOperatorUiComponentsSurface as OperatorUiComponentsSurface;
  },
});

const operatorUiCache = new Map<string, OperatorUiComponentsSurface>();

/** Warm operator UI React surface via dynamic import. */
export async function ensureOperatorUiComponentsSurface(
  pluginId: string
): Promise<OperatorUiComponentsSurface | null> {
  if (pluginId.trim().length === 0) {
    return null;
  }
  const cached = operatorUiCache.get(pluginId);
  if (cached != null) {
    return cached;
  }
  const load = OPERATOR_UI_LOADERS[pluginId];
  if (load == null) {
    return null;
  }
  const surface = await load();
  operatorUiCache.set(pluginId, surface);
  return surface;
}

export function resolveOperatorUiComponentsSurface(
  pluginId: string
): OperatorUiComponentsSurface | null {
  return operatorUiCache.get(pluginId) ?? null;
}

function firstWarmOperatorUiSurface(): OperatorUiComponentsSurface | null {
  for (const surface of operatorUiCache.values()) {
    return surface;
  }
  return null;
}

export function ensureLeafletDefaultIcon(): void {
  const surface = firstWarmOperatorUiSurface();
  if (surface == null) {
    throw new Error("ensureLeafletDefaultIcon: operator UI cache cold (call ensureOperatorUiComponentsSurface first)");
  }
  surface.ensureLeafletDefaultIcon();
}
