/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Plugin ids with workspaceFinance.supported — finance hub enablement (Phase 1.2). */
export const WORKSPACE_FINANCE_NAV_PLUGIN_IDS = new Set<string>([
  "denali",
  "finance-ws3",
  "finance-ws4",
  "finance-ws5",
  "finance-ws6",
]);

export function isFinanceNavPlugin(pluginId: string): boolean {
  return WORKSPACE_FINANCE_NAV_PLUGIN_IDS.has(pluginId);
}
