/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WizardTemplateEditorSurface } from "@/wizard/wizard-template-editor-types";
import { denaliWizardTemplateEditor as editor_denali } from "@app-tour/workspace-denali/settings/wizard-template-editor";

const WIZARD_TEMPLATE_EDITORS: Readonly<Record<string, WizardTemplateEditorSurface>> = Object.freeze({
  "denali": editor_denali,
});

export function resolveWizardTemplateEditor(
  pluginId: string
): WizardTemplateEditorSurface | null {
  return WIZARD_TEMPLATE_EDITORS[pluginId] ?? null;
}
