/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { denaliWizardCreateViewSurface as wizard_create_view_denali } from "@app-tour/workspace-denali/host/ui/chrome/wizard-create-view-surface";

export const DenaliCreateTourWizardView = wizard_create_view_denali.CreateTourWizardView;

