/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

type WorkspaceWizardMessageLocale = "fa" | "en";

const WORKSPACE_WIZARD_MESSAGE_LOADERS = {
  "urban": {
    fa: () => import("@app-tour/workspace-urban/messages/fa/wizard.json"),
    en: () => import("@app-tour/workspace-urban/messages/en/wizard.json"),
  },
} as const;

/** Load workspace wizard JSON namespaces for a locale (manifest wizardI18n.messageNamespace). */
export async function loadWorkspaceWizardMessagesForLocale(
  locale: WorkspaceWizardMessageLocale
): Promise<Record<string, unknown>> {
  const entries = await Promise.all(
  Object.entries(WORKSPACE_WIZARD_MESSAGE_LOADERS).map(async ([namespace, loaders]) => {
      const mod = await loaders[locale]();
      return [namespace, mod.default] as const;
    })
  );
  return Object.fromEntries(entries);
}
