/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceEquipmentFieldRegistryFragment } from "@app-tour/workspace-sdk/equipment";
import { denaliEquipmentFieldRegistryFragment as denali_equipment_field_module } from "@app-tour/workspace-denali/host/field-registry/denali-equipment-field-module";

export type WorkspaceEquipmentFieldModuleBinding = {
  readonly workspaceType: string;
  readonly fieldRegistryFragment: WorkspaceEquipmentFieldRegistryFragment;
};

export const WORKSPACE_EQUIPMENT_FIELD_MODULE_BINDINGS: readonly WorkspaceEquipmentFieldModuleBinding[] = [
  {
    workspaceType: "denali",
    fieldRegistryFragment: denali_equipment_field_module,
  },
] as const;

export function resolveWorkspaceEquipmentFieldRegistryFragment(
  workspaceType: string
): WorkspaceEquipmentFieldRegistryFragment | undefined {
  const binding = WORKSPACE_EQUIPMENT_FIELD_MODULE_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.fieldRegistryFragment;
}
