/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { BookingOpsCapability } from "@/features/bookings/booking-ops-capability-contract";

import {
  DEFAULT_BOOKING_OPS_MANIFEST as booking_ws2_bookingOpsDefault,
  resolveBookingOpsManifestFromTheme as booking_ws2_bookingOpsResolveFromTheme,
} from "@app-tour/workspace-booking-ws2/host/bookings";

import {
  DEFAULT_BOOKING_OPS_MANIFEST as denali_bookingOpsDefault,
  resolveBookingOpsManifestFromTheme as denali_bookingOpsResolveFromTheme,
} from "@app-tour/workspace-denali/host/bookings";

export const WORKSPACE_BOOKING_OPS_BINDINGS = {
  "booking-ws2": {
    defaultManifest: booking_ws2_bookingOpsDefault,
    resolveFromTheme: booking_ws2_bookingOpsResolveFromTheme,
  },
  "denali": {
    defaultManifest: denali_bookingOpsDefault,
    resolveFromTheme: denali_bookingOpsResolveFromTheme,
  },
} as const;

export const WORKSPACE_BOOKING_OPS_PLUGIN_IDS = new Set<string>(
  Object.keys(WORKSPACE_BOOKING_OPS_BINDINGS)
);

export function hasBookingOpsManifest(pluginId: string): boolean {
  return pluginId in WORKSPACE_BOOKING_OPS_BINDINGS;
}

export function resolveWorkspaceBookingOpsManifest(
  pluginId: string,
  theme: unknown = null
): BookingOpsCapability {
  const binding = WORKSPACE_BOOKING_OPS_BINDINGS[pluginId as keyof typeof WORKSPACE_BOOKING_OPS_BINDINGS];
  if (binding === undefined) {
    throw new Error(`Booking ops capability not registered for pluginId=${pluginId}`);
  }
  if (theme === null || theme === undefined) {
    return binding.defaultManifest;
  }
  return binding.resolveFromTheme(theme);
}
