/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceTransportFieldRegistryFragment } from "@app-tour/workspace-sdk/transport";
import { denaliTransportFieldRegistryFragment as denali_transport_field_module } from "@app-tour/workspace-denali/host/field-registry/denali-transport-field-module";

export type WorkspaceTransportFieldModuleBinding = {
  readonly workspaceType: string;
  readonly fieldRegistryFragment: WorkspaceTransportFieldRegistryFragment;
};

export const WORKSPACE_TRANSPORT_FIELD_MODULE_BINDINGS: readonly WorkspaceTransportFieldModuleBinding[] = [
  {
    workspaceType: "denali",
    fieldRegistryFragment: denali_transport_field_module,
  },
] as const;

export function resolveWorkspaceTransportFieldRegistryFragment(
  workspaceType: string
): WorkspaceTransportFieldRegistryFragment | undefined {
  const binding = WORKSPACE_TRANSPORT_FIELD_MODULE_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.fieldRegistryFragment;
}
