/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceItineraryWizardCompositeBinding } from "@app-tour/workspace-sdk/itinerary";
import { denaliItineraryWizardCompositeBinding as denali_itinerary_wizard_composite } from "@app-tour/workspace-denali/host/composites/denali-itinerary-composite-binding";

export type WorkspaceItineraryWizardCompositeBindingEntry = {
  readonly workspaceType: string;
  readonly wizardCompositeBinding: WorkspaceItineraryWizardCompositeBinding;
};

export const WORKSPACE_ITINERARY_WIZARD_COMPOSITE_BINDINGS: readonly WorkspaceItineraryWizardCompositeBindingEntry[] = [
  {
    workspaceType: "denali",
    wizardCompositeBinding: denali_itinerary_wizard_composite,
  },
] as const;

export function resolveWorkspaceItineraryWizardCompositeBinding(
  workspaceType: string
): WorkspaceItineraryWizardCompositeBinding | undefined {
  const binding = WORKSPACE_ITINERARY_WIZARD_COMPOSITE_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.wizardCompositeBinding;
}
