/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceItineraryFieldRegistryFragment } from "@app-tour/workspace-sdk/itinerary";
import { denaliItineraryFieldRegistryFragment as denali_itinerary_field_module } from "@app-tour/workspace-denali/host/field-registry/denali-itinerary-field-module";

export type WorkspaceItineraryFieldModuleBinding = {
  readonly workspaceType: string;
  readonly fieldRegistryFragment: WorkspaceItineraryFieldRegistryFragment;
};

export const WORKSPACE_ITINERARY_FIELD_MODULE_BINDINGS: readonly WorkspaceItineraryFieldModuleBinding[] = [
  {
    workspaceType: "denali",
    fieldRegistryFragment: denali_itinerary_field_module,
  },
] as const;

export function resolveWorkspaceItineraryFieldRegistryFragment(
  workspaceType: string
): WorkspaceItineraryFieldRegistryFragment | undefined {
  const binding = WORKSPACE_ITINERARY_FIELD_MODULE_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.fieldRegistryFragment;
}
