/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { SettingsEquipmentUiSurface } from "@/features/settings/settings-equipment-ui-types";
import { denaliSettingsEquipmentUiSurface as equipment_ui_denali } from "@app-tour/workspace-denali/ui/settings/settings-equipment-ui-surface";

const SETTINGS_EQUIPMENT_UI_SURFACES: Readonly<Record<string, SettingsEquipmentUiSurface>> = Object.freeze({
  "denali": equipment_ui_denali,
});

export function resolveSettingsEquipmentUiSurface(
  pluginId: string
): SettingsEquipmentUiSurface | null {
  return SETTINGS_EQUIPMENT_UI_SURFACES[pluginId] ?? null;
}
