/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { denaliWizardDraftUnificationSurface as draft_unification_denali } from "@app-tour/workspace-denali/host/draft/wizard-draft-unification-surface";

export function logWizardDraftTombstoneShadowMismatch(
  ...args: Parameters<typeof draft_unification_denali.logTombstoneShadowMismatch>
): void {
  draft_unification_denali.logTombstoneShadowMismatch(...args);
}

export function resolveWizardDraftCreateTourDraftKey(pluginId: string): string | null {
  if (pluginId === "denali") {
    return draft_unification_denali.createTourDraftKey;
  }
  return null;
}
