/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { denaliWizardDraftShellSurface as wizard_draft_shell_denali } from "@app-tour/workspace-denali/ui/chrome/wizard-draft-shell-surface";

export const createDenaliWizardDraftSessionId = wizard_draft_shell_denali.createWizardDraftSessionId;
export const DENALI_CREATE_TOUR_DRAFT_KEY = wizard_draft_shell_denali.createTourDraftKey;
export const DENALI_OPERATOR_WIZARD_DRAFT_NAMESPACE = wizard_draft_shell_denali.operatorDraftNamespace;
export const createDenaliDraftSchemaGate = wizard_draft_shell_denali.createDraftSchemaGate;
export const denaliHydrateDraftEnvelope = wizard_draft_shell_denali.hydrateDraftEnvelope;
export const denaliPrepareDraftEnvelope = wizard_draft_shell_denali.prepareDraftEnvelope;
export const isDenaliFreshStartEnvelope = wizard_draft_shell_denali.isFreshStartEnvelope;
export const resolveDenaliDraftMerge = wizard_draft_shell_denali.resolveDraftMerge;
export const emptyDenaliTourWizardDraft = wizard_draft_shell_denali.emptyTourWizardDraft;
export const applyDenaliDefaultTourKind = wizard_draft_shell_denali.applyDefaultTourKind;
export const buildDenaliCreatePrefilledFormCore = wizard_draft_shell_denali.buildCreatePrefilledFormCore;
export const getDenaliWorkspacePluginFromDraftShell = wizard_draft_shell_denali.getWorkspacePlugin;
export type { DenaliWizardDraftMeta } from "@app-tour/workspace-denali/draft";

