/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceDifficultyFitnessFieldRegistryFragment } from "../difficulty-fitness/workspace-difficulty-fitness-field-module";
import { denaliDifficultyFitnessFieldRegistryFragment as denali_difficulty_fitness_field_module } from "@app-tour/workspace-denali/field-registry/denali-difficulty-fitness-field-module";

export type WorkspaceDifficultyFitnessFieldModuleBinding = {
  readonly workspaceType: string;
  readonly fieldRegistryFragment: WorkspaceDifficultyFitnessFieldRegistryFragment;
};

export const WORKSPACE_DIFFICULTY_FITNESS_FIELD_MODULE_BINDINGS: readonly WorkspaceDifficultyFitnessFieldModuleBinding[] = [
  {
    workspaceType: "denali",
    fieldRegistryFragment: denali_difficulty_fitness_field_module,
  },
] as const;

export function resolveWorkspaceDifficultyFitnessFieldRegistryFragment(
  workspaceType: string
): WorkspaceDifficultyFitnessFieldRegistryFragment | undefined {
  const binding = WORKSPACE_DIFFICULTY_FITNESS_FIELD_MODULE_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.fieldRegistryFragment;
}
