/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { denaliOperatorUiComponentsSurface as ui_denali } from "@app-tour/workspace-denali/host/ui/operator-ui-components-surface";
import type { ComponentProps } from "react";

const OPERATOR_UI_COMPONENTS = Object.freeze({
  "denali": ui_denali,
});

export function resolveOperatorUiComponentsSurface(pluginId: string) {
  return OPERATOR_UI_COMPONENTS[pluginId as keyof typeof OPERATOR_UI_COMPONENTS] ?? null;
}

export const DenaliTimeInput = ui_denali.TimeInput;
export type DenaliTimeInputProps = ComponentProps<typeof DenaliTimeInput>;
export type DenaliTimeInputAppearance = DenaliTimeInputProps["appearance"];

export const DenaliDifficultyRangeSlider = ui_denali.DifficultyRangeSlider;
export type DenaliDifficultyRangeSliderProps = ComponentProps<typeof DenaliDifficultyRangeSlider>;

export const DenaliLocationPickerMap = ui_denali.LocationPickerMap;
export const DenaliLocationPickerMapInner = ui_denali.LocationPickerMapInner;
export const ensureLeafletDefaultIcon = ui_denali.ensureLeafletDefaultIcon;
export type {
  DenaliMapCoordinates,
  DenaliLocationPickerMapInnerProps,
} from "@app-tour/workspace-denali/host/ui/components/location-picker-map";

export const DenaliWizardDatetimePicker = ui_denali.WizardDatetimePicker;
