/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { denaliWizardFlatEditChromeSurface as wizard_flat_edit_chrome_denali } from "@app-tour/workspace-denali/host/ui/chrome/wizard-flat-edit-chrome-surface";

export const useDenaliFlatEditPageCore = wizard_flat_edit_chrome_denali.useFlatEditPageCore;
export const loadDenaliSubmitCatalogIds = wizard_flat_edit_chrome_denali.loadSubmitCatalog;
export type {
  DenaliFlatEditTourDetail,
  DenaliFlatEditTourLoadResult,
} from "@app-tour/workspace-denali/host/ui/chrome/wizard-flat-edit-chrome-surface";

