/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { denaliPhotoUploadErrorsSurface as photo_errors_denali } from "@app-tour/workspace-denali/ui/adapters/photo-upload-errors-surface";

export const PHOTO_UPLOAD_ERROR_MESSAGE_KEYS = photo_errors_denali.messageKeys;

export const extractPhotoApiErrorCode = photo_errors_denali.extractApiErrorCode;
export const normalizePhotoErrorCode = photo_errors_denali.normalizeErrorCode;
export const parsePhotoApiErrorCode = photo_errors_denali.parseApiErrorCode;

export function resolvePhotoUploadError(
  t: (key: string, values?: Record<string, string | number>) => string,
  code: string | null | undefined
): string | null {
  return photo_errors_denali.resolvePhotoUploadError(t, code);
}
