/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

type WizardTemplateFieldOverlaysAugment = <
  T extends { readonly canonicalPath: string; readonly hidden?: boolean; readonly defaultValue?: string },
>(
  templateSteps: readonly { readonly enabled?: boolean; readonly fields: readonly T[] }[],
  baseOverlays: ReadonlyMap<string, T>,
) => ReadonlyMap<string, T>;

const FIELD_OVERLAYS_AUGMENT_LOADERS: Readonly<
  Record<string, () => Promise<WizardTemplateFieldOverlaysAugment>>
> = Object.freeze({
  "denali": async () => {
    const mod = await import("@app-tour/workspace-denali/host/wizard/template-field-overlays");
    return mod.augmentDenaliWizardTemplateFieldOverlays;
  },
});

const fieldOverlaysAugmentCache = new Map<string, WizardTemplateFieldOverlaysAugment>();

export async function ensureWizardTemplateFieldOverlaysAugment(
  pluginId: string
): Promise<WizardTemplateFieldOverlaysAugment | null> {
  if (pluginId.trim().length === 0) {
    return null;
  }
  const cached = fieldOverlaysAugmentCache.get(pluginId);
  if (cached != null) {
    return cached;
  }
  const load = FIELD_OVERLAYS_AUGMENT_LOADERS[pluginId];
  if (load == null) {
    return null;
  }
  const augment = await load();
  fieldOverlaysAugmentCache.set(pluginId, augment);
  return augment;
}

/** Manifest-derived default step id when publishing an empty wizard template. */
export const WORKSPACE_WIZARD_TEMPLATE_GATE_DEFAULT_STEP_ID: Readonly<
  Record<string, string>
> = Object.freeze({
  "booking-ws2": "basics",
  "denali": "denali_basic",
  "finance-ws2": "basics",
  "finance-ws3": "basics",
  "finance-ws4": "basics",
  "finance-ws5": "basics",
  "finance-ws6": "basics",
  "guest-club": "basics",
  "starter": "basics",
  "urban": "basics",
});

export function resolveWizardTemplateGateDefaultPublishedStepId(pluginId: string): string {
  return WORKSPACE_WIZARD_TEMPLATE_GATE_DEFAULT_STEP_ID[pluginId] ?? "basics";
}

/** Manifest-bound workspace augment — uses warm cache (call ensureWizardTemplateFieldOverlaysAugment first). */
export function augmentWizardTemplateFieldOverlays<
  T extends { readonly canonicalPath: string; readonly hidden?: boolean; readonly defaultValue?: string },
>(
  pluginId: string,
  templateSteps: readonly { readonly enabled?: boolean; readonly fields: readonly T[] }[],
  baseOverlays: ReadonlyMap<string, T>,
): ReadonlyMap<string, T> {
  const augment = fieldOverlaysAugmentCache.get(pluginId);
  if (augment == null) {
    return baseOverlays;
  }
  return augment(templateSteps, baseOverlays);
}

const WIZARD_TEMPLATE_PREFER_TEMPLATE_DEFAULTS = new Set<string>(
  ["denali"],
);

export function resolveWizardTemplatePreferTemplateDefaults(pluginId: string): boolean {
  return WIZARD_TEMPLATE_PREFER_TEMPLATE_DEFAULTS.has(pluginId);
}
