/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { denaliWizardCompositeRegistrySurface as wizard_composite_registry_denali } from "@app-tour/workspace-denali/host/composites/wizard-composite-registry-surface";

export const DENALI_COMPOSITE_BY_CANONICAL_PATH = wizard_composite_registry_denali.compositeByCanonicalPath;

