/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { denaliWizardRulesSurface as wizard_rules_denali } from "@app-tour/workspace-denali/wizard/wizard-rules-surface";

export type WizardRulesModule = {
  readonly evaluateFormFieldRule: typeof wizard_rules_denali.evaluateFormFieldRule;
  readonly applyDenaliInvariantState: typeof wizard_rules_denali.applyDenaliInvariantState;
  readonly resolveDenaliRuleSetFromTemplate: typeof wizard_rules_denali.resolveDenaliRuleSetFromTemplate;
  readonly buildDefaultForm: () => Record<string, unknown>;
  readonly readCanonicalBasics: typeof wizard_rules_denali.readDenaliCanonicalBasics;
  readonly canonicalToFormPathMap: typeof wizard_rules_denali.canonicalToFormPathMap;
  readonly tourKindValues: typeof wizard_rules_denali.tourKindValues;
};

let wizardRulesModule: WizardRulesModule | null = null;

export function getWizardRulesModuleSync(pluginId: string): WizardRulesModule {
  if (pluginId !== "denali") {
    throw new Error(`No wizard rules surface for plugin: ${pluginId}`);
  }
  wizardRulesModule ??= Object.freeze({
    evaluateFormFieldRule: wizard_rules_denali.evaluateFormFieldRule,
    applyDenaliInvariantState: wizard_rules_denali.applyDenaliInvariantState,
    resolveDenaliRuleSetFromTemplate: wizard_rules_denali.resolveDenaliRuleSetFromTemplate,
    buildDefaultForm: wizard_rules_denali.buildDenaliTourCreateDefaultValues,
    readCanonicalBasics: wizard_rules_denali.readDenaliCanonicalBasics,
    canonicalToFormPathMap: wizard_rules_denali.canonicalToFormPathMap,
    tourKindValues: wizard_rules_denali.tourKindValues,
  }) as WizardRulesModule;
  return wizardRulesModule;
}

export function loadWizardRulesModule(pluginId: string): Promise<WizardRulesModule> {
  return Promise.resolve(getWizardRulesModuleSync(pluginId));
}
