/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Manifest-derived default step id when publishing an empty wizard template. */
export const WORKSPACE_WIZARD_TEMPLATE_GATE_DEFAULT_STEP_ID: Readonly<
  Record<string, string>
> = Object.freeze({
  "denali": "denali_basic",
  "guest-club": "basics",
  "starter": "basics",
  "urban": "basics",
});

export function resolveWizardTemplateGateDefaultPublishedStepId(pluginId: string): string {
  return WORKSPACE_WIZARD_TEMPLATE_GATE_DEFAULT_STEP_ID[pluginId] ?? "basics";
}
