/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { FinanceOpsManifest } from "@/finance/finance-ops-manifest-contract";

import {
  DEFAULT_FINANCE_OPS_MANIFEST as denali_opsDefault,
  resolveFinanceOpsManifestFromTheme as denali_opsResolveFromTheme,
} from "@app-tour/workspace-denali/host/finance/manifest";

export const WORKSPACE_FINANCE_OPS_BINDINGS = {
  "denali": {
    defaultManifest: denali_opsDefault,
    resolveFromTheme: denali_opsResolveFromTheme,
  },
} as const;

export const WORKSPACE_FINANCE_OPS_PLUGIN_IDS = new Set<string>(
  Object.keys(WORKSPACE_FINANCE_OPS_BINDINGS)
);

export function hasFinanceOpsManifest(pluginId: string): boolean {
  return pluginId in WORKSPACE_FINANCE_OPS_BINDINGS;
}

export function resolveWorkspaceFinanceOpsManifest(
  pluginId: string,
  theme: unknown = null
): FinanceOpsManifest {
  const binding = WORKSPACE_FINANCE_OPS_BINDINGS[pluginId as keyof typeof WORKSPACE_FINANCE_OPS_BINDINGS];
  if (binding === undefined) {
    throw new Error(`Finance ops manifest not registered for pluginId=${pluginId}`);
  }
  if (theme === null || theme === undefined) {
    return binding.defaultManifest;
  }
  return binding.resolveFromTheme(theme);
}
