/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { SettingsExposureSurfacesUiSurface } from "@/features/settings/settings-exposure-surfaces-ui-types";

const SETTINGS_EXPOSURE_SURFACES_UI_SURFACES_LOADERS: Readonly<
  Record<string, () => Promise<SettingsExposureSurfacesUiSurface>>
> = Object.freeze({
  "denali": async () => {
    const mod = await import("@app-tour/workspace-denali/host/ui/settings/settings-exposure-surfaces-ui-surface");
    return mod.denaliSettingsExposureSurfacesUiSurface;
  },
});

const SETTINGS_EXPOSURE_SURFACES_UI_SURFACES_CACHE = new Map<string, SettingsExposureSurfacesUiSurface>();

/** Warm product surface via dynamic import (no static @app-tour/workspace-* fan-in). */
export async function ensureSettingsExposureSurfacesUiSurface(
  pluginId: string
): Promise<SettingsExposureSurfacesUiSurface | null> {
  if (pluginId.trim().length === 0) {
    return null;
  }
  const cached = SETTINGS_EXPOSURE_SURFACES_UI_SURFACES_CACHE.get(pluginId);
  if (cached != null) {
    return cached;
  }
  const load = SETTINGS_EXPOSURE_SURFACES_UI_SURFACES_LOADERS[pluginId];
  if (load == null) {
    return null;
  }
  const surface = await load();
  SETTINGS_EXPOSURE_SURFACES_UI_SURFACES_CACHE.set(pluginId, surface);
  return surface;
}

/** Sync read of warm cache — call ensureSettingsExposureSurfacesUiSurface first for product surfaces. */
export function resolveSettingsExposureSurfacesUiSurface(
  pluginId: string
): SettingsExposureSurfacesUiSurface | null {
  return SETTINGS_EXPOSURE_SURFACES_UI_SURFACES_CACHE.get(pluginId) ?? null;
}
