/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { TourListCategorySurface } from "@/features/tours/tour-list-category-surface-types";
import { denaliTourListCategorySurface as tour_list_category_denali } from "@app-tour/workspace-denali/tours/tour-list-category-surface";

const TOUR_LIST_CATEGORY_SURFACES: Readonly<Record<string, TourListCategorySurface>> = Object.freeze({
  "denali": tour_list_category_denali,
});

export function resolveTourListCategorySurface(
  pluginId: string
): TourListCategorySurface | null {
  return TOUR_LIST_CATEGORY_SURFACES[pluginId] ?? null;
}
