/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { denaliWizardFlatEditFormSurface as wizard_flat_edit_form_denali } from "@app-tour/workspace-denali/ui/chrome/wizard-flat-edit-form-surface";

export const DenaliFlatEditForm = wizard_flat_edit_form_denali.FlatEditForm;
export const DENALI_FLAT_EDIT_TEST_IDS = wizard_flat_edit_form_denali.testIds;
export type {
  DenaliFlatEditFormProps,
  DenaliTourWizardDraft,
} from "@app-tour/workspace-denali/ui/chrome/wizard-flat-edit-form-surface";

