/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { SettingsEquipmentUiSurface } from "@/features/settings/settings-equipment-ui-types";

const SETTINGS_EQUIPMENT_UI_SURFACES_LOADERS: Readonly<
  Record<string, () => Promise<SettingsEquipmentUiSurface>>
> = Object.freeze({
  "denali": async () => {
    const mod = await import("@app-tour/workspace-denali/host/ui/settings/settings-equipment-ui-surface");
    return mod.denaliSettingsEquipmentUiSurface;
  },
});

const SETTINGS_EQUIPMENT_UI_SURFACES_CACHE = new Map<string, SettingsEquipmentUiSurface>();

/** Warm product surface via dynamic import (no static @app-tour/workspace-* fan-in). */
export async function ensureSettingsEquipmentUiSurface(
  pluginId: string
): Promise<SettingsEquipmentUiSurface | null> {
  if (pluginId.trim().length === 0) {
    return null;
  }
  const cached = SETTINGS_EQUIPMENT_UI_SURFACES_CACHE.get(pluginId);
  if (cached != null) {
    return cached;
  }
  const load = SETTINGS_EQUIPMENT_UI_SURFACES_LOADERS[pluginId];
  if (load == null) {
    return null;
  }
  const surface = await load();
  SETTINGS_EQUIPMENT_UI_SURFACES_CACHE.set(pluginId, surface);
  return surface;
}

/** Sync read of warm cache — call ensureSettingsEquipmentUiSurface first for product surfaces. */
export function resolveSettingsEquipmentUiSurface(
  pluginId: string
): SettingsEquipmentUiSurface | null {
  return SETTINGS_EQUIPMENT_UI_SURFACES_CACHE.get(pluginId) ?? null;
}
