/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export async function loadFullWizardTemplatePreset(
  pluginId: string,
  seedLabel?: string
): Promise<import("@/features/settings/wizard-template-types").WizardTemplatePayload> {
  if (pluginId === "denali") {
    const mod = await import("@app-tour/workspace-denali/settings/wizard-template-preset-surface");
    return mod.denaliWizardTemplatePresetSurface.buildFullTemplatePreset(seedLabel);
  }
  throw new Error(`No wizard template preset for plugin: ${pluginId}`);
}
