/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { DestinationSettingsSurface } from "@/features/settings/destination-settings-surface-types";
import { denaliDestinationSettingsSurface as destination_surface_denali } from "@app-tour/workspace-denali/settings/destination-settings-surface";

const SETTINGS_DESTINATION_SURFACES: Readonly<Record<string, DestinationSettingsSurface>> = Object.freeze({
  "denali": destination_surface_denali,
});

export function resolveSettingsDestinationSurface(
  pluginId: string
): DestinationSettingsSurface | null {
  return SETTINGS_DESTINATION_SURFACES[pluginId] ?? null;
}
