/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { ReactNode } from "react";

/** Host props injected by apps/web workspace-owner settings page (Wave I.1). */
export type WorkspaceOwnerSettingsPanelHostProps = {
  readonly apiBaseUrl: string;
  readonly headers: Readonly<Record<string, string>>;
  readonly labels: {
    readonly title: string;
    readonly loadError: (status: number) => string;
    readonly catalogEnabled: string;
    readonly catalogSlug: string;
    readonly registrationPolicy: string;
    readonly yes: string;
    readonly no: string;
    readonly viewCatalog: string;
  };
};

/** Async RSC or sync panel accepted by the workspace-owner host page. */
export type WorkspaceOwnerSettingsPanelComponent = (
  props: WorkspaceOwnerSettingsPanelHostProps
) => ReactNode | Promise<ReactNode>;

/**
 * Lazy-load workspace-owner settings panel for a pluginId.
 * Returns null when the workspace does not declare operatorShell.ownerSettingsPanel.
 */
export async function loadWorkspaceOwnerSettingsPanel(
  pluginId: string
): Promise<WorkspaceOwnerSettingsPanelComponent | null> {
  switch (pluginId) {

    default:
      return null;
  }
}
