/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { FinanceOpsCapability } from "@/finance/finance-ops-capability-contract";

export const WORKSPACE_FINANCE_OPS_BINDINGS = {
  "denali": {
    loadManifest: async (theme: unknown = null) => {
      const mod = await import("@app-tour/workspace-denali/host/finance/manifest");
      if (theme === null || theme === undefined) {
        return mod.DEFAULT_FINANCE_OPS_MANIFEST;
      }
      return mod.resolveFinanceOpsManifestFromTheme(theme);
    },
  },
  "finance-ws5": {
    loadManifest: async (theme: unknown = null) => {
      const mod = await import("@app-tour/workspace-finance-ws5/host/finance/manifest");
      if (theme === null || theme === undefined) {
        return mod.DEFAULT_FINANCE_OPS_MANIFEST;
      }
      return mod.resolveFinanceOpsManifestFromTheme(theme);
    },
  },
} as const;

export const WORKSPACE_FINANCE_OPS_PLUGIN_IDS = new Set<string>(
  Object.keys(WORKSPACE_FINANCE_OPS_BINDINGS)
);

export function hasFinanceOpsManifest(pluginId: string): boolean {
  return pluginId in WORKSPACE_FINANCE_OPS_BINDINGS;
}

export async function resolveWorkspaceFinanceOpsManifest(
  pluginId: string,
  theme: unknown = null
): Promise<FinanceOpsCapability> {
  const binding = WORKSPACE_FINANCE_OPS_BINDINGS[pluginId as keyof typeof WORKSPACE_FINANCE_OPS_BINDINGS];
  if (binding === undefined) {
    throw new Error(`Finance ops capability not registered for pluginId=${pluginId}`);
  }
  return binding.loadManifest(theme);
}
