/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Manifest paths per workspace plugin (private; Phase 4h). */
const WORKSPACE_ADMIN_THEME_REGISTRY = Object.freeze({
  "cert-club": Object.freeze(["theme/tokens.css"]),
  "cert-events": Object.freeze(["theme/tokens.css"]),
  denali: Object.freeze(["theme/denali-admin.css"]),
  "guest-club": Object.freeze(["theme/tokens.css"]),
  "profile-cert": Object.freeze(["theme/tokens.css"]),
  starter: Object.freeze(["theme/tokens.css"]),
  urban: Object.freeze(["theme/tokens.css"]),
  "wallet-ws1": Object.freeze(["theme/tokens.css"]),
}) as Readonly<Record<string, readonly string[]>>;

/** Stylesheet path list for pluginId, if declared in manifest themeStylesheets. */
export function resolveAdminThemeStylesheets(pluginId: string): readonly string[] | undefined {
  const id = pluginId.trim();
  if (id.length === 0) {
    return undefined;
  }
  return WORKSPACE_ADMIN_THEME_REGISTRY[id];
}

/** Plugin ids that declare admin themeStylesheets (tests / admission). */
export function listAdminThemeRegistryPluginIds(): readonly string[] {
  return Object.freeze(Object.keys(WORKSPACE_ADMIN_THEME_REGISTRY));
}

/** Load workspace admin skin CSS for the active plugin only (dynamic import). */
export async function importAdminThemeForPlugin(pluginId: string): Promise<void> {
  switch (pluginId) {
    case "cert-club":
      await import("@app-tour/workspace-cert-club/theme/tokens.css");
      return;

    case "cert-events":
      await import("@app-tour/workspace-cert-events/theme/tokens.css");
      return;

    case "denali":
      await import("@app-tour/workspace-denali/theme/denali-admin.css");
      return;

    case "guest-club":
      await import("@app-tour/workspace-guest-club/theme/tokens.css");
      return;

    case "profile-cert":
      await import("@app-tour/workspace-profile-cert/theme/tokens.css");
      return;

    case "starter":
      await import("@app-tour/workspace-starter/theme/tokens.css");
      return;

    case "urban":
      await import("@app-tour/workspace-urban/theme/tokens.css");
      return;

    case "wallet-ws1":
      await import("@app-tour/workspace-wallet-ws1/theme/tokens.css");
      return;
    default:
      return;
  }
}
