/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspacePlugin } from "@app-tour/workspace-sdk";
import {
  getOrCreateWorkspacePluginLoad,
  invalidateWorkspacePluginLoadCache,
} from "./workspace-plugin-load-cache";
import { assertWorkspacePluginClientBundleEnabled } from "./workspace-plugin-client-bundle-gate";

/** Sorted product trunk plugin ids — cache bust when codegen regen changes membership. */
export const WORKSPACE_PLUGIN_REGISTRY_REVISION =
  "acme,booking-ws2,denali,finance-ws5,guest-club,harbor,starter,urban";

/** Upper bound for per-process plugin load cache (= product trunk plugin count). */
export const WORKSPACE_PLUGIN_LOAD_CACHE_MAX_ENTRIES = 8;

export { invalidateWorkspacePluginLoadCache };

export async function loadWorkspacePluginByIdFromRegistry(
  pluginId: string
): Promise<WorkspacePlugin> {
  return getOrCreateWorkspacePluginLoad(
    pluginId,
    async () => {
      switch (pluginId) {
        case "acme": {
          const mod = await import("@app-tour/workspace-acme/plugin");
          return mod.getWorkspacePlugin();
        }
        case "booking-ws2": {
          const mod = await import("@app-tour/workspace-booking-ws2/plugin");
          return mod.getWorkspacePlugin();
        }
        case "denali": {
          assertWorkspacePluginClientBundleEnabled(
            "denali",
            "ALLOW_DENALI_WEB_PLUGIN",
            process.env.ALLOW_DENALI_WEB_PLUGIN === "true"
          );
          const mod = await import("@app-tour/workspace-denali/plugin");
          return mod.getWorkspacePlugin();
        }
        case "finance-ws5": {
          const mod = await import("@app-tour/workspace-finance-ws5/plugin");
          return mod.getWorkspacePlugin();
        }
        case "guest-club": {
          const mod = await import("@app-tour/workspace-guest-club/plugin");
          return mod.getWorkspacePlugin();
        }
        case "harbor": {
          const mod = await import("@app-tour/workspace-harbor/plugin");
          return mod.getWorkspacePlugin();
        }
        case "starter": {
          const mod = await import("@app-tour/workspace-starter");
          return mod.getWorkspacePlugin();
        }
        case "urban": {
          assertWorkspacePluginClientBundleEnabled(
            "urban",
            "ALLOW_URBAN_WEB_PLUGIN",
            process.env.ALLOW_URBAN_WEB_PLUGIN === "true"
          );
          const mod = await import("@app-tour/workspace-urban/plugin");
          return mod.getWorkspacePlugin();
        }
        default:
          throw new Error(`WORKSPACE_PLUGIN_NOT_FOUND:${pluginId}`);
      }
    },
    {
      registryRevision: WORKSPACE_PLUGIN_REGISTRY_REVISION,
      maxEntries: WORKSPACE_PLUGIN_LOAD_CACHE_MAX_ENTRIES,
    }
  );
}
