/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/**
 * Gap Closure B.5 — empty shell stub.
 * Canonical map: `@app-tour/workspace-denali` composites package (not static shell fan-in).
 */
export const DENALI_COMPOSITE_BY_CANONICAL_PATH: Readonly<Record<string, string>> = Object.freeze({});
