/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WizardRulesModule = {
  readonly evaluateFormFieldRule: (...args: never[]) => unknown;
  readonly applyDenaliInvariantState: (...args: never[]) => unknown;
  readonly resolveDenaliRuleSetFromTemplate: (...args: never[]) => unknown;
  readonly buildDefaultForm: (...args: never[]) => unknown;
  readonly readCanonicalBasics: (...args: never[]) => unknown;
  readonly canonicalToFormPathMap: unknown;
  readonly tourKindValues: unknown;
};

const WIZARD_RULES_LOADERS: Readonly<
  Record<string, () => Promise<WizardRulesModule>>
> = Object.freeze({
  "denali": async () => {
    const mod = await import("@app-tour/workspace-denali/host/wizard/wizard-rules-surface");
    const surface = mod.denaliWizardRulesSurface;
    return Object.freeze({
      evaluateFormFieldRule: surface.evaluateFormFieldRule,
      applyDenaliInvariantState: surface.applyDenaliInvariantState,
      resolveDenaliRuleSetFromTemplate: surface.resolveDenaliRuleSetFromTemplate,
      buildDefaultForm: surface.buildDenaliTourCreateDefaultValues,
      readCanonicalBasics: surface.readDenaliCanonicalBasics,
      canonicalToFormPathMap: surface.canonicalToFormPathMap,
      tourKindValues: surface.tourKindValues,
    });
  },
});

const wizardRulesCache = new Map<string, WizardRulesModule>();

export async function loadWizardRulesModule(pluginId: string): Promise<WizardRulesModule> {
  const cached = wizardRulesCache.get(pluginId);
  if (cached != null) {
    return cached;
  }
  const load = WIZARD_RULES_LOADERS[pluginId];
  if (load == null) {
    throw new Error(`No wizard rules surface for plugin: ${pluginId}`);
  }
  const module = await load();
  wizardRulesCache.set(pluginId, module);
  return module;
}

/** Sync read of warm cache — call loadWizardRulesModule first. */
export function getWizardRulesModuleSync(pluginId: string): WizardRulesModule {
  const cached = wizardRulesCache.get(pluginId);
  if (cached == null) {
    throw new Error(`No wizard rules surface for plugin: ${pluginId} (call loadWizardRulesModule first)`);
  }
  return cached;
}
