/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspacePricingFieldRegistryFragment } from "@app-tour/workspace-sdk/pricing";
import { denaliPricingFieldRegistryFragment as denali_pricing_field_module } from "@app-tour/workspace-denali/host/field-registry/denali-pricing-field-module";

export type WorkspacePricingFieldModuleBinding = {
  readonly workspaceType: string;
  readonly fieldRegistryFragment: WorkspacePricingFieldRegistryFragment;
};

export const WORKSPACE_PRICING_FIELD_MODULE_BINDINGS: readonly WorkspacePricingFieldModuleBinding[] = [
  {
    workspaceType: "denali",
    fieldRegistryFragment: denali_pricing_field_module,
  },
] as const;

export function resolveWorkspacePricingFieldRegistryFragment(
  workspaceType: string
): WorkspacePricingFieldRegistryFragment | undefined {
  const binding = WORKSPACE_PRICING_FIELD_MODULE_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.fieldRegistryFragment;
}
