/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceTransportWizardCompositeBinding } from "@app-tour/workspace-sdk/transport";
import { denaliTransportModeCompositeBinding as denali_transport_wizard_composite } from "@app-tour/workspace-denali/host/composites/denali-transport-composite-binding";

export type WorkspaceTransportWizardCompositeBindingEntry = {
  readonly workspaceType: string;
  readonly wizardCompositeBinding: WorkspaceTransportWizardCompositeBinding;
};

export const WORKSPACE_TRANSPORT_WIZARD_COMPOSITE_BINDINGS: readonly WorkspaceTransportWizardCompositeBindingEntry[] = [
  {
    workspaceType: "denali",
    wizardCompositeBinding: denali_transport_wizard_composite,
  },
] as const;

export function resolveWorkspaceTransportWizardCompositeBinding(
  workspaceType: string
): WorkspaceTransportWizardCompositeBinding | undefined {
  const binding = WORKSPACE_TRANSPORT_WIZARD_COMPOSITE_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.wizardCompositeBinding;
}
