/**
 * Product-facing copy for `/tours/[id]/workspace` (Phase 16.4).
 */
export const TOUR_WORKSPACE_COPY = {
  metadata: {
    title: "ورک‌اسپیس ثبت‌نام تور",
    description: "مدیریت درخواست‌ها و لیست انتظار برای یک تور.",
  },
  page: {
    documentTitle: "ورک‌اسپیس ثبت‌نام",
    title: "ورک‌اسپیس ثبت‌نام",
    breadcrumbHome: "خانه",
    breadcrumbDashboard: "داشبورد",
    breadcrumbTours: "تورها",
    breadcrumbWorkspace: "ثبت‌نام‌ها",
    tourFallback: "تور",
    description: (title: string, accepted: number, capacity: number) =>
      `${title} · ${accepted} از ${capacity} پذیرفته‌شده`,
    tourDetails: "جزئیات تور",
    loadingSession: "در حال بارگذاری نشست…",
    signInTitle: "ورود لازم است",
    signInDescription: "نشست شما منقضی شده است. برای ادامه وارد شوید.",
    signInButton: "ورود",
    leaderRequiredTitle: "دسترسی رهبر لازم است",
    leaderRequiredDescription: "فقط کاربران با نقش رهبر می‌توانند ورک‌اسپیس ثبت‌نام را باز کنند.",
    backToTours: "بازگشت به تورها",
    tenantUnavailableTitle: "ورک‌اسپیس در دسترس نیست",
    tenantUnavailableDescription: "زمینه tenant در نشست نیست. دوباره وارد شوید.",
    signInAgain: "ورود مجدد",
    apiNotConfiguredTitle: "API پیکربندی نشده",
    apiNotConfiguredDescription: "هاست ورک‌اسپیس و API را فعال کنید.",
    backToDashboard: "بازگشت به داشبورد",
    loadingTour: "در حال بارگذاری تور…",
    loadTourErrorTitle: "بارگذاری تور ناموفق بود",
    loadTourNotFound: "توری با این شناسه یافت نشد.",
    loadTourFallback: "جزئیات تور بارگذاری نشد.",
    tourNotFoundTitle: "تور یافت نشد",
    tourNotFoundDescription: "توری با این شناسه وجود ندارد.",
    updatingLive: "در حال بروزرسانی داده‌های ورک‌اسپیس",
    overviewTitle: "خلاصه",
    pendingReview: "در انتظار بررسی",
    totalRegistrations: "کل ثبت‌نام‌ها در فهرست",
    waitlistEntries: "لیست انتظار",
    reconciliationHint:
      "هماهنگ‌سازی بین تورها: داشبورد → صف بررسی متقاضیان → خروجی CSV.",
    mutationErrorFallback: "درخواست انجام نشد.",
  },
  subnav: {
    ariaLabel: "بخش‌های ورک‌اسپیس تور",
    registrations: "ثبت‌نام‌ها",
    waitlist: "لیست انتظار",
    transport: "حمل‌ونقل",
  },
  transport: {
    title: "داشبورد حمل‌ونقل",
    description: "نمای حمل‌ونقل (اتوبوس، خودروی شخصی و ظرفیت) به‌زودی در این بخش قرار می‌گیرد.",
    loading: "در حال بارگذاری داده‌های حمل‌ونقل…",
    deficitTitle: "کسری ظرفیت خودرو",
    deficitMessage:
      "Transport Deficit: More passengers needing a car than available seats!",
    deficitMessageFa:
      "کسری حمل‌ونقل: تعداد مسافران بدون خودرو بیشتر از صندلی‌های اعلام‌شده توسط رانندگان است!",
    metrics: {
      busHeadcount: "مسافران حمل‌ونقل گروهی",
      busHeadcountHint: "ثبت‌نام پذیرفته با خودروی گروهی",
      carDrivers: "رانندگان",
      carDriversHint: "خودروی شخصی — راننده",
      carSeats: "صندلی‌های آزاد خودرو",
      carSeatsHint: "مجموع صندلی اضافه اعلام‌شده",
      carPassengers: "مسافران بدون خودرو",
      carPassengersHint: "خودروی شخصی — بدون رانندگی",
      balance: "تراز ظرفیت خودرو",
      balanceHint: "صندلی آزاد منهای مسافران",
    },
    gauge: {
      title: "بار حمل‌ونقل سازمان‌یافته",
      caption: "نسبت مسافران اتوبوس/گروهی به ظرفیت کل تور",
      ofCapacity: "از ظرفیت",
      acceptedTotal: "پذیرفته‌شده (کل)",
      busOnly: "فقط گروهی",
    },
    metadataGap:
      "برخی ثبت‌نام‌های خودروی شخصی فاقد پرچم راننده/مسافر هستند و در شمارش راننده/مسافر لحاظ نشده‌اند.",
    actionCenter: {
      title: "مرکز عملیات حمل‌ونقل",
      hint: "برنامه سفر خودروها را نهایی کنید و برای رانندگان ارسال کنید.",
      exportSendPlan: "خروجی / ارسال برنامه حمل‌ونقل",
      addManualVehicle: "افزودن خودرو دستی",
      manualModalTitle: "افزودن خودرو (ثبت‌نام نشده)",
      manualModalDescription:
        "وقتی راننده در فرم ثبت‌نام خودرو را وارد نکرده، می‌توانید او را اینجا اضافه کنید.",
      driverNameLabel: "نام راننده",
      driverNamePlaceholder: "نام و نام خانوادگی",
      seatsLabel: "صندلی‌های آزاد (۰–۳)",
      addVehicleConfirm: "افزودن",
      cancel: "انصراف",
      notifySuccess: (count: number) =>
        `برنامه حمل‌ونقل برای ${count} راننده ارسال شد (پیامک/اعلان — شبیه‌سازی).`,
      notifyError: "ارسال برنامه حمل‌ونقل انجام نشد.",
    },
    driversTable: {
      title: "مدیریت رانندگان",
      emptyTitle: "راننده‌ای ثبت نشده",
      emptyDescription: "رانندگان با ثبت‌نام «خودروی شخصی — راننده» یا «افزودن خودرو دستی» اینجا نمایش داده می‌شوند.",
      colDriverName: "نام راننده",
      colAvailableSeats: "صندلی آزاد",
      colPassengersAssigned: "مسافران اختصاص‌یافته",
      colStatus: "وضعیت",
      colAction: "عملیات",
      statusFull: "تکمیل",
      statusHasCapacity: "ظرفیت باقی",
      assign: "اختصاص",
      manualBadge: "دستی",
      unassignedCount: "مسافران بدون خودرو",
      assignModalTitle: "اختصاص مسافر به راننده",
      assignModalDescription: (driverName: string) => `انتخاب مسافر برای ${driverName}`,
      selectPassenger: "مسافر",
      confirmAssign: "اختصاص",
      noUnassigned: "مسافر بدون اختصاصی باقی نمانده است.",
    },
  },
  readOnly: {
    cancelled: "این تور لغو شده است؛ ثبت‌نام‌ها فقط خواندنی هستند.",
    draft: "این تور پیش‌نویس است؛ تا باز شدن تور، ثبت‌نام‌ها فقط خواندنی هستند.",
    closed: "این تور بسته شده است؛ ثبت‌نام‌ها فقط خواندنی هستند.",
  },
  registrations: {
    title: "ثبت‌نام‌ها",
    filterAll: "همه",
    filterPending: "در انتظار بررسی",
    loading: "در حال بارگذاری ثبت‌نام‌ها…",
    loadErrorTitle: "بارگذاری ثبت‌نام‌ها ناموفق بود",
    emptyPendingTitle: "ثبت‌نامی در انتظار بررسی نیست",
    emptyPendingDescription: "برای این تور درخواستی در صف بررسی نیست.",
    emptyAllTitle: "هنوز ثبت‌نامی نیست",
    emptyAllDescription: "پس از ثبت‌نام شرکت‌کنندگان، اینجا نمایش داده می‌شوند.",
    colParticipant: "متقاضی",
    colTransportNotes: "وسیله نقلیه / توضیحات",
    colStatuses: "وضعیت‌ها",
    colUpdateStatus: "تغییر وضعیت",
    colPaymentOps: "عملیات پرداخت",
    apply: "اعمال",
    savePayment: "ذخیره پرداخت",
    paidAmountPlaceholder: "مبلغ پرداخت‌شده",
  },
  waitlist: {
    title: "لیست انتظار",
    colParticipant: "متقاضی",
    colStatus: "وضعیت",
    colConvert: "تبدیل",
    loading: "در حال بارگذاری لیست انتظار…",
    loadErrorTitle: "بارگذاری لیست انتظار ناموفق بود",
    emptyTitle: "لیست انتظار خالی است",
    emptyDescription: "وقتی ظرفیت پر باشد، متقاضیان اینجا قرار می‌گیرند.",
    fifoTooltip: "فقط قدیمی‌ترین مورد در انتظار قابل تبدیل است (قانون FIFO).",
    convert: "تبدیل به ثبت‌نام",
    converting: "در حال تبدیل…",
    convertFailed: "تبدیل انجام نشد.",
    notAllowed: "این تبدیل مجاز نیست.",
  },
} as const;
