/**
 * Product-facing copy for `/tours/[id]/workspace` (Phase 16.4).
 */
export const TOUR_WORKSPACE_COPY = {
  metadata: {
    title: "ورک‌اسپیس ثبت‌نام تور",
    description: "مدیریت درخواست‌ها و لیست انتظار برای یک تور.",
  },
  page: {
    documentTitle: "ورک‌اسپیس ثبت‌نام",
    title: "ورک‌اسپیس ثبت‌نام",
    breadcrumbHome: "خانه",
    breadcrumbDashboard: "داشبورد",
    breadcrumbTours: "تورها",
    breadcrumbWorkspace: "ثبت‌نام‌ها",
    tourFallback: "تور",
    description: (title: string, accepted: number, capacity: number) =>
      `${title} · ${accepted} از ${capacity} پذیرفته‌شده`,
    tourDetails: "جزئیات تور",
    loadingSession: "در حال بارگذاری نشست…",
    signInTitle: "ورود لازم است",
    signInDescription: "نشست شما منقضی شده است. برای ادامه وارد شوید.",
    signInButton: "ورود",
    leaderRequiredTitle: "دسترسی رهبر لازم است",
    leaderRequiredDescription: "فقط کاربران با نقش رهبر می‌توانند ورک‌اسپیس ثبت‌نام را باز کنند.",
    backToTours: "بازگشت به تورها",
    tenantUnavailableTitle: "ورک‌اسپیس در دسترس نیست",
    tenantUnavailableDescription: "زمینه tenant در نشست نیست. دوباره وارد شوید.",
    signInAgain: "ورود مجدد",
    apiNotConfiguredTitle: "API پیکربندی نشده",
    apiNotConfiguredDescription: "هاست ورک‌اسپیس و API را فعال کنید.",
    backToDashboard: "بازگشت به داشبورد",
    loadingTour: "در حال بارگذاری تور…",
    loadTourErrorTitle: "بارگذاری تور ناموفق بود",
    loadTourNotFound: "توری با این شناسه یافت نشد.",
    loadTourFallback: "جزئیات تور بارگذاری نشد.",
    tourNotFoundTitle: "تور یافت نشد",
    tourNotFoundDescription: "توری با این شناسه وجود ندارد.",
    updatingLive: "در حال بروزرسانی داده‌های ورک‌اسپیس",
    overviewTitle: "خلاصه",
    pendingReview: "در انتظار بررسی",
    totalRegistrations: "کل ثبت‌نام‌ها در فهرست",
    waitlistEntries: "لیست انتظار",
    reconciliationHint:
      "هماهنگ‌سازی بین تورها: داشبورد → صف بررسی متقاضیان → خروجی CSV.",
    mutationErrorFallback: "درخواست انجام نشد.",
  },
  readOnly: {
    cancelled: "این تور لغو شده است؛ ثبت‌نام‌ها فقط خواندنی هستند.",
    draft: "این تور پیش‌نویس است؛ تا باز شدن تور، ثبت‌نام‌ها فقط خواندنی هستند.",
    closed: "این تور بسته شده است؛ ثبت‌نام‌ها فقط خواندنی هستند.",
  },
  registrations: {
    title: "ثبت‌نام‌ها",
    filterAll: "همه",
    filterPending: "در انتظار بررسی",
    loading: "در حال بارگذاری ثبت‌نام‌ها…",
    loadErrorTitle: "بارگذاری ثبت‌نام‌ها ناموفق بود",
    emptyPendingTitle: "ثبت‌نامی در انتظار بررسی نیست",
    emptyPendingDescription: "برای این تور درخواستی در صف بررسی نیست.",
    emptyAllTitle: "هنوز ثبت‌نامی نیست",
    emptyAllDescription: "پس از ثبت‌نام شرکت‌کنندگان، اینجا نمایش داده می‌شوند.",
    colParticipant: "متقاضی",
    colTransportNotes: "وسیله نقلیه / توضیحات",
    colStatuses: "وضعیت‌ها",
    colUpdateStatus: "تغییر وضعیت",
    colPaymentOps: "عملیات پرداخت",
    apply: "اعمال",
    savePayment: "ذخیره پرداخت",
    paidAmountPlaceholder: "مبلغ پرداخت‌شده",
  },
  waitlist: {
    title: "لیست انتظار",
    colParticipant: "متقاضی",
    colStatus: "وضعیت",
    colConvert: "تبدیل",
    loading: "در حال بارگذاری لیست انتظار…",
    loadErrorTitle: "بارگذاری لیست انتظار ناموفق بود",
    emptyTitle: "لیست انتظار خالی است",
    emptyDescription: "وقتی ظرفیت پر باشد، متقاضیان اینجا قرار می‌گیرند.",
    fifoTooltip: "فقط قدیمی‌ترین مورد در انتظار قابل تبدیل است (قانون FIFO).",
    convert: "تبدیل به ثبت‌نام",
    converting: "در حال تبدیل…",
    convertFailed: "تبدیل انجام نشد.",
    notAllowed: "این تبدیل مجاز نیست.",
  },
} as const;
