const TELEGRAM_EVENT_LABEL_KEYS: Readonly<Record<string, string>> = {
  TourCreated: "tourCreated",
  "tour.created": "tourCreated",
  TourPublished: "tourPublished",
  "tour.published": "tourPublished",
  "Member registered": "memberRegistered",
  "member.registered": "memberRegistered",
  "Receipt submitted": "receiptSubmitted",
  "receipt.submitted": "receiptSubmitted",
  "Registration created": "registrationCreated",
  "registration.created": "registrationCreated",
  "Registration waitlisted": "registrationWaitlisted",
  "registration.waitlisted": "registrationWaitlisted",
  RegistrationApproved: "registrationApproved",
  "Registration approved": "registrationApproved",
  "registration.approved": "registrationApproved",
  RegistrationWaitlisted: "registrationWaitlisted",
  "Receipt approved": "receiptApproved",
  receiptApproved: "receiptApproved",
  "receipt.approved": "receiptApproved",
  ReceiptApproved: "receiptApproved",
  "Receipt rejected": "receiptRejected",
  ReceiptRejected: "receiptRejected",
  "receipt.rejected": "receiptRejected",
  "Ticket assigned": "ticketAssigned",
  "ticket.assigned": "ticketAssigned",
  "Ticket closed": "ticketClosed",
  "ticket.closed": "ticketClosed",
  "Ticket created": "ticketCreated",
  "ticket.created": "ticketCreated",
  "Ticket internal note created": "ticketInternalNoteCreated",
  "ticket.internal_note.created": "ticketInternalNoteCreated",
  "Ticket message posted": "ticketMessagePosted",
  "ticket.message.posted": "ticketMessagePosted",
  "Ticket priority changed": "ticketPriorityChanged",
  "ticket.priority.changed": "ticketPriorityChanged",
  "Ticket reopened": "ticketReopened",
  "ticket.reopened": "ticketReopened",
  "Ticket resolved": "ticketResolved",
  "ticket.resolved": "ticketResolved",
  "Ticket status changed": "ticketStatusChanged",
  "ticket.status.changed": "ticketStatusChanged",
};

export function telegramEventLabelKey(eventType: string): string | undefined {
  return TELEGRAM_EVENT_LABEL_KEYS[eventType];
}
