/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export { DENALI_REMINDER_OFFSETS, mapDenaliExposureSurfaceToFieldPolicySurface, resolveDenaliSurfaceDefaultFieldIds, type DenaliExposureCoordinate } from "@app-tour/workspace-denali/host/exposure";
export { mapUrbanExposureSurfaceToFieldPolicySurface, resolveUrbanSurfaceDefaultFieldIds, type UrbanExposureCoordinate } from "@app-tour/workspace-urban/host/exposure";
