/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export const WORKSPACE_WALLET_BINDINGS = [] as const;

export function isWalletSupportedWorkspace(_workspaceType: string): boolean {
  return false;
}

export function isWalletDefaultEnabledWhenModulesUnset(_workspaceType: string): boolean {
  return false;
}
