/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import "@app-tour/workspace-denali/theme/denali-marketing.css";
import "@app-tour/workspace-guest-club/theme/marketing.css";
import "@app-tour/workspace-urban/theme/urban-marketing.css";
