/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { MarketingCatalogSurface } from "@/catalog/marketing-catalog-surface-types";
import { denaliMarketingCatalogSurface as catalog_denali } from "@app-tour/workspace-denali/marketing/marketing-catalog-surface";

const MARKETING_CATALOG_SURFACES: Readonly<Record<string, MarketingCatalogSurface>> = Object.freeze({
  "denali": catalog_denali,
});

export function resolveMarketingCatalogSurface(
  pluginId: string
): MarketingCatalogSurface | null {
  return MARKETING_CATALOG_SURFACES[pluginId] ?? null;
}
