/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceManifestTheme } from "@app-tour/workspace-sdk/workspace-registry";

export const WORKSPACE_GUEST_MANIFEST_THEMES = Object.freeze({
  denali: Object.freeze({
    "--ws-color-primary": "#059669",
    "--ws-color-primary-fg": "#ffffff",
    "--ws-color-primary-hover": "#047857",
    "--ws-color-accent": "#e8efe8",
    "--ws-color-bg-page": "#f4f7f4",
    "--ws-color-bg-surface": "#ffffff",
    "--ws-color-bg-muted": "#e8efe8",
    "--ws-color-text-primary": "#1a1f26",
    "--ws-color-text-secondary": "#4a5244",
    "--ws-color-text-muted": "#6f7768",
    "--ws-color-border-default": "#dce5dc",
    "--ws-color-border-subtle": "#e8efe8",
    "--ws-sidebar": "#ffffff",
    "--ws-sidebar-border": "#dce5dc",
    "--ws-sidebar-foreground": "#1a1f26",
    "--ws-sidebar-primary": "#059669",
    "--ws-sidebar-accent": "#e8efe8",
    "--ws-radius": "0.625rem",
  }),
  "guest-club": undefined,
  starter: undefined,
  urban: undefined,
}) as Readonly<Record<string, WorkspaceManifestTheme | undefined>>;

/** Resolve codegen manifest `theme` for a workspace plugin id (no runtime filesystem registry). */
export function resolveGuestManifestThemeForPlugin(
  pluginId: string
): WorkspaceManifestTheme | undefined {
  return WORKSPACE_GUEST_MANIFEST_THEMES[pluginId];
}
