import type { TourCreateFormValues } from "@/components/tours/wizard/schemas/tourCreateSchema";

import { wizardDefaultDaySegment } from "./tourCreateWizardMerge";

/** Canonical empty wizard shape (create flow). Used by the wizard UI and Phase 4 profile strip. */
export function buildTourCreateFormDefaultValues(): TourCreateFormValues {
  return {
    autoAcceptRegistrations: true,
    overview: {
      title: "",
      shortDescription: "",
      longDescription: "",
      tourType: undefined,
      mainTourThemeId: undefined,
      secondaryTourThemeIds: [],
      tripStyles: [],
      highlights: [],
      communicationLink: "",
    },
    pricing: {
      basePrice: 0,
      currency: "TOMAN",
      discountNotes: "",
    },
    schedule: {
      startDate: "",
      endDate: "",
      departureMeetingTime: "",
      returnMeetingTime: "",
    },
    location: {
      regionId: "",
      mainDestinationId: "",
      secondaryDestinationIds: [],
      meetingPoint: "",
      returnPoint: "",
      displayLocation: "",
    },
    itinerary: {
      days: [
        {
          dayNumber: 1,
          title: "",
          description: "",
          segments: [{ ...wizardDefaultDaySegment }],
        },
      ],
    },
    participation: {
      requiredExperienceLevel: "",
      requiredFitnessLevel: "",
      minimumAge: undefined,
      maximumAge: undefined,
      genderRestriction: "",
      technicalSkillRequired: "",
      medicalRestrictions: "",
      requirements: "",
      skillsRequired: [],
      gearRequiredIds: [],
      gearOptionalIds: [],
      documentsRequired: [],
      suitableFor: [],
      notSuitableFor: [],
      minParticipants: undefined,
      sportsInsuranceRequired: false,
      registrationNationalIdRequired: false,
    },
    logistics: {
      primaryTransportMode: undefined,
      supplementalPrivateCar: false,
      fuelShareToman: undefined,
      includedServices: "",
      excludedServices: "",
      meetingPointDetails: "",
      transportationDetails: "",
      transportationNotes: "",
      accommodationDetails: "",
      accommodationTypes: [],
      accommodationNotes: "",
      mealPlan: "",
      mealNotes: "",
      supportServices: [],
      optionalServices: [],
      leaderProvidesInsurance: false,
      leaderInsuranceNotes: "",
      guideLanguageIds: [],
      groupSizeMin: undefined,
      groupSizeMax: undefined,
    },
    policies: {
      cancellationPolicy: "",
      refundPolicy: "",
      safetyNotes: "",
      riskDisclaimer: "",
      attendanceRules: "",
      lateArrivalPolicy: "",
      noShowPolicy: "",
      confirmationPolicy: "",
      capacityPolicy: "",
      safetyPolicy: "",
      weatherPolicy: "",
      reservationRules: "",
    },
  };
}
