/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceCatalogIntakeTransportSurface } from "./catalog-intake-transport-surface";

export type CatalogIntakeTransportSurfaceBinding = {
  readonly workspaceType: string;
  readonly transportIntakeSurface: WorkspaceCatalogIntakeTransportSurface;
};

export const CATALOG_INTAKE_TRANSPORT_INTAKE_WORKSPACE_TYPES = new Set<string>([
  "denali"
]);

/** Lazy workspace-owned catalog intake transport surfaces — dynamic import only (CW7 closure). */
export async function resolveCatalogIntakeTransportSurface(
  workspaceType: string
): Promise<WorkspaceCatalogIntakeTransportSurface | undefined> {
  if (!CATALOG_INTAKE_TRANSPORT_INTAKE_WORKSPACE_TYPES.has(workspaceType)) {
    return undefined;
  }
  switch (workspaceType) {
    case "denali": {
      const mod = await import("@app-tour/workspace-denali/catalog/denali-catalog-transport-intake");
      return mod.denaliCatalogTransportIntakeSurface;
    }
    default:
      return undefined;
  }
}
