/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { PublicCatalogTransportSnapshot } from "../tour/public-catalog-transport";

export type CatalogTransportSnapshotReaderBinding = {
  readonly workspaceType: string;
  readonly readCatalogTransportSnapshot: (
    data: Record<string, unknown>
  ) => PublicCatalogTransportSnapshot | undefined;
};

export const CATALOG_TRANSPORT_SNAPSHOT_READER_WORKSPACE_TYPES = new Set<string>([
  "cert-club",
  "denali"
]);

/** Lazy workspace-owned catalog transport snapshot readers — dynamic import only (CW9 closure). */
export async function resolveCatalogTransportSnapshotReader(
  workspaceType: string
): Promise<
  CatalogTransportSnapshotReaderBinding["readCatalogTransportSnapshot"] | undefined
> {
  if (!CATALOG_TRANSPORT_SNAPSHOT_READER_WORKSPACE_TYPES.has(workspaceType)) {
    return undefined;
  }
  switch (workspaceType) {
    case "cert-club": {
      const mod = await import("@app-tour/workspace-cert-club/host/transport/catalog-transport-snapshot");
      return mod.readCertClubCatalogTransportSnapshot;
    }
    case "denali": {
      const mod = await import("@app-tour/workspace-denali/catalog/read-denali-catalog-transport");
      return mod.readDenaliCatalogTransportSnapshot;
    }
    default:
      return undefined;
  }
}
