/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { PublicCatalogTransportSnapshot } from "../tour/public-catalog-transport";
import { readDenaliCatalogTransportSnapshot as denali_transport_snapshot_reader } from "@app-tour/workspace-denali/host/catalog/read-denali-catalog-transport";

export type CatalogTransportSnapshotReaderBinding = {
  readonly workspaceType: string;
  readonly readCatalogTransportSnapshot: (
    data: Record<string, unknown>
  ) => PublicCatalogTransportSnapshot | undefined;
};

export const CATALOG_TRANSPORT_SNAPSHOT_READER_BINDINGS: readonly CatalogTransportSnapshotReaderBinding[] = [
  {
    workspaceType: "denali",
    readCatalogTransportSnapshot: denali_transport_snapshot_reader,
  },
] as const;

export function resolveCatalogTransportSnapshotReader(
  workspaceType: string
): CatalogTransportSnapshotReaderBinding["readCatalogTransportSnapshot"] | undefined {
  const binding = CATALOG_TRANSPORT_SNAPSHOT_READER_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.readCatalogTransportSnapshot;
}
