/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceCatalogIntakeTransportSurface } from "./catalog-intake-transport-surface";
import { denaliCatalogTransportIntakeSurface as denali_transport_intake_surface } from "@app-tour/workspace-denali/catalog/denali-catalog-transport-intake";

export type CatalogIntakeTransportSurfaceBinding = {
  readonly workspaceType: string;
  readonly transportIntakeSurface: WorkspaceCatalogIntakeTransportSurface;
};

export const CATALOG_INTAKE_TRANSPORT_SURFACE_BINDINGS: readonly CatalogIntakeTransportSurfaceBinding[] = [
  {
    workspaceType: "denali",
    transportIntakeSurface: denali_transport_intake_surface,
  },
] as const;

export function resolveCatalogIntakeTransportSurface(
  workspaceType: string
): WorkspaceCatalogIntakeTransportSurface | undefined {
  const binding = CATALOG_INTAKE_TRANSPORT_SURFACE_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.transportIntakeSurface;
}
