/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Member for-tour registration API bases — derived from workspace.manifest.json httpRoutes. */
export const WORKSPACE_REGISTRATION_FOR_TOUR_API_PATHS: Readonly<Record<string, string>> = Object.freeze({
  "denali": "/denali/registrations",
});
