/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type GuestLandingVariant = "full" | "minimal";

export type GuestLandingFeatures = Readonly<{
  readonly variant: GuestLandingVariant;
  readonly whySectionAnchor: string;
  readonly destinationSlugs: readonly string[];
  readonly destinationImageStems: Readonly<Record<string, string>>;
  readonly sections: Readonly<{
    readonly hero: boolean;
    readonly latestTours: boolean;
    readonly latestToursLimit: number;
    readonly trust: boolean;
    readonly finalCta: boolean;
    readonly faq: boolean;
    readonly footer: boolean;
    readonly whyDenali: boolean;
    readonly journey: boolean;
    readonly testimonials: boolean;
    readonly featuredTours: boolean;
    readonly featuredToursLimit: number;
    readonly categories: boolean;
    readonly destinations: boolean;
    readonly heroSearch: boolean;
    readonly gallery: boolean;
    readonly equipment: boolean;
    readonly blogTeaser: boolean;
  }>;
  readonly i18nProfile: "full" | "minimal";
  readonly shellChrome: Readonly<{
    readonly localeSwitcher: boolean;
    readonly headerToursCta: boolean;
  }>;
}>;

/** Guest marketing landing gates — derived from workspace.manifest.json guestLanding. */
export const WORKSPACE_GUEST_LANDING: Readonly<
  Record<string, GuestLandingFeatures>
> = Object.freeze({
  "denali": Object.freeze({
    variant: "full",
    whySectionAnchor: "why-us",
    destinationSlugs: Object.freeze(["alborz","damavand","zardkuh"]),
    destinationImageStems: Object.freeze({"zardkuh":"zardkooh"}),
    sections: Object.freeze({
      hero: true,
      latestTours: true,
      latestToursLimit: 6,
      trust: true,
      finalCta: true,
      faq: true,
      footer: true,
      whyDenali: true,
      journey: true,
      testimonials: true,
      featuredTours: true,
      featuredToursLimit: 3,
      categories: true,
      destinations: true,
      heroSearch: true,
      gallery: true,
      equipment: true,
      blogTeaser: false,
    }),
    i18nProfile: "full",
    shellChrome: Object.freeze({
      localeSwitcher: false,
      headerToursCta: false,
    }),
  }),
  "guest-club": Object.freeze({
    variant: "minimal",
    whySectionAnchor: "why-us",
    destinationSlugs: Object.freeze([]),
    destinationImageStems: Object.freeze({}),
    sections: Object.freeze({
      hero: false,
      latestTours: false,
      latestToursLimit: 0,
      trust: false,
      finalCta: false,
      faq: false,
      footer: false,
      whyDenali: false,
      journey: false,
      testimonials: false,
      featuredTours: false,
      featuredToursLimit: 0,
      categories: false,
      destinations: false,
      heroSearch: false,
      gallery: false,
      equipment: false,
      blogTeaser: false,
    }),
    i18nProfile: "minimal",
    shellChrome: Object.freeze({
      localeSwitcher: false,
      headerToursCta: false,
    }),
  }),
  "harbor": Object.freeze({
    variant: "minimal",
    whySectionAnchor: "why-us",
    destinationSlugs: Object.freeze([]),
    destinationImageStems: Object.freeze({}),
    sections: Object.freeze({
      hero: false,
      latestTours: false,
      latestToursLimit: 0,
      trust: false,
      finalCta: false,
      faq: false,
      footer: false,
      whyDenali: false,
      journey: false,
      testimonials: false,
      featuredTours: false,
      featuredToursLimit: 0,
      categories: false,
      destinations: false,
      heroSearch: false,
      gallery: false,
      equipment: false,
      blogTeaser: false,
    }),
    i18nProfile: "minimal",
    shellChrome: Object.freeze({
      localeSwitcher: false,
      headerToursCta: false,
    }),
  }),
  "urban": Object.freeze({
    variant: "minimal",
    whySectionAnchor: "why-us",
    destinationSlugs: Object.freeze([]),
    destinationImageStems: Object.freeze({}),
    sections: Object.freeze({
      hero: false,
      latestTours: false,
      latestToursLimit: 0,
      trust: false,
      finalCta: false,
      faq: false,
      footer: false,
      whyDenali: false,
      journey: false,
      testimonials: false,
      featuredTours: false,
      featuredToursLimit: 0,
      categories: false,
      destinations: false,
      heroSearch: false,
      gallery: false,
      equipment: false,
      blogTeaser: false,
    }),
    i18nProfile: "minimal",
    shellChrome: Object.freeze({
      localeSwitcher: false,
      headerToursCta: false,
    }),
  }),
});
