/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Marketing catalog price display — derived from workspace.manifest.json catalogPresentation.priceDisplay. */
export const WORKSPACE_CATALOG_PRICE_DISPLAY: Readonly<
  Record<string, Readonly<{ readonly irrDisplayUnit?: "toman" }>>
> = Object.freeze({
  "cert-club": Object.freeze({}),
  "cert-events": Object.freeze({}),
  "denali": Object.freeze({ irrDisplayUnit: "toman" }),
  "guest-club": Object.freeze({}),
  "harbor": Object.freeze({}),
  "profile-cert": Object.freeze({}),
  "urban": Object.freeze({}),
});
