/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceDifficultyFitnessCapabilities = {
  readonly supported: true;
  readonly wizardTourField: boolean;
  readonly catalogDetailSection: boolean;
  readonly catalogListFilters: boolean;
  readonly catalogMarketingFilters: boolean;
};

export const WORKSPACE_DIFFICULTY_FITNESS_CAPABILITIES = {
  "denali": {
    supported: true as const,
    wizardTourField: true as const,
    catalogDetailSection: true as const,
    catalogListFilters: true as const,
    catalogMarketingFilters: true as const,
  },
} as const satisfies Record<string, WorkspaceDifficultyFitnessCapabilities>;

export function getWorkspaceDifficultyFitnessCapabilities(
  workspaceType: string
): WorkspaceDifficultyFitnessCapabilities | null {
  return (
  WORKSPACE_DIFFICULTY_FITNESS_CAPABILITIES[
    workspaceType as keyof typeof WORKSPACE_DIFFICULTY_FITNESS_CAPABILITIES
  ] ?? null
  );
}
