/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceDifficultyFitnessFilterPresentation } from "../tour/public-catalog-difficulty-fitness";

const MARKETING_DIFFICULTY_FITNESS_WORKSPACE_TYPES = new Set<string>([
  "denali"
]);

/** Lazy workspace-owned filter vocab — dynamic import only (CW7-09). */
export async function resolveWorkspaceDifficultyFitnessFilterPresentation(
  workspaceType: string
): Promise<WorkspaceDifficultyFitnessFilterPresentation | undefined> {
  if (!MARKETING_DIFFICULTY_FITNESS_WORKSPACE_TYPES.has(workspaceType)) {
    return undefined;
  }
  switch (workspaceType) {
    case "denali": {
      const mod = await import("@app-tour/workspace-denali/host/marketing/denali-difficulty-fitness-filter-presentation");
      return mod.denaliDifficultyFitnessFilterPresentation;
    }
    default:
      return undefined;
  }
}
