/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspacePricingCapabilities = {
  readonly supported: true;
  readonly wizardTourField: boolean;
  readonly allowMembershipDiscount: boolean;
};

export const WORKSPACE_PRICING_CAPABILITIES = {
  "denali": {
    supported: true as const,
    wizardTourField: true as const,
    allowMembershipDiscount: true as const,
  },
} as const satisfies Record<string, WorkspacePricingCapabilities>;

export function getWorkspacePricingCapabilities(
  workspaceType: string
): WorkspacePricingCapabilities | null {
  return (
    WORKSPACE_PRICING_CAPABILITIES[
      workspaceType as keyof typeof WORKSPACE_PRICING_CAPABILITIES
    ] ?? null
  );
}
