/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceWalletCapabilities = {
  readonly supported: true;
  readonly defaultModuleEnabledWhenUnset: boolean;
  readonly memberAccounts: boolean;
  readonly ops: boolean;
  readonly gatewayTopUp: boolean;
  readonly withdrawals: boolean;
};

/**
 * Capability matrix — product gate (`supported`) vs wallet surface flags.
 * Keys are literal workspaceType strings from workspace.manifest.json.
 */
export const WORKSPACE_WALLET_CAPABILITIES = {
  "denali": {
    supported: true as const,
    defaultModuleEnabledWhenUnset: false as const,
    memberAccounts: true as const,
    ops: true as const,
    gatewayTopUp: false as const,
    withdrawals: false as const,
  },
  "wallet-ws1": {
    supported: true as const,
    defaultModuleEnabledWhenUnset: true as const,
    memberAccounts: true as const,
    ops: true as const,
    gatewayTopUp: false as const,
    withdrawals: false as const,
  },
} as const satisfies Record<string, WorkspaceWalletCapabilities>;

export function getWorkspaceWalletCapabilities(
  workspaceType: string
): WorkspaceWalletCapabilities | null {
  const key = workspaceType.trim().toLowerCase();
  if (key.length === 0) {
    return null;
  }
  const caps = (WORKSPACE_WALLET_CAPABILITIES as Record<string, WorkspaceWalletCapabilities>)[key];
  return caps ?? null;
}

export function listWalletCapableWorkspaceTypes(): readonly string[] {
  return Object.keys(WORKSPACE_WALLET_CAPABILITIES).sort();
}

export function walletWorkspaceHasCapability(
  workspaceType: string,
  capability: "memberAccounts" | "ops" | "gatewayTopUp" | "withdrawals"
): boolean {
  const caps = getWorkspaceWalletCapabilities(workspaceType);
  if (caps === null) {
    return false;
  }
  return caps[capability] === true;
}
