/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { GuestCrossSurfaceNavLink, GuestCrossSurfaceNavSurface } from "./guest-cross-surface-nav";

/** Guest cross-surface nav rows — derived from workspace.manifest.json guestCrossSurfaceNav. */
export const WORKSPACE_GUEST_CROSS_SURFACE_NAV: Readonly<
  Record<string, GuestCrossSurfaceNavSurface>
> = Object.freeze({
  "denali": Object.freeze({
    version: 1 as const,
    links: Object.freeze([
      Object.freeze({
        id: "home",
        labelKey: "nav.home",
        surface: "marketing",
        path: "/",
        visibleWhen: "club",
      }),
      Object.freeze({
        id: "tours",
        labelKey: "nav.tours",
        surface: "marketing",
        path: "/tours",
        visibleWhen: "club",
      }),
      Object.freeze({
        id: "my-trips",
        labelKey: "nav.myTrips",
        surface: "portal_egress",
        egress: "member_module",
        memberModuleId: "trips",
        visibleWhen: "always",
      }),
    ] as const satisfies readonly GuestCrossSurfaceNavLink[]),
  }),
});
