/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceTransportCapabilities = {
  readonly supported: true;
  readonly wizardTourField: boolean;
  readonly catalogSnapshot: boolean;
  readonly catalogDetailSection: boolean;
  readonly registrationIntake: boolean;
  readonly registrationInitializer: boolean;
  readonly listProjection: boolean;
  readonly registrationNormalize: boolean;
};

export const WORKSPACE_TRANSPORT_CAPABILITIES = {
  "denali": {
    supported: true as const,
    wizardTourField: false as const,
    catalogSnapshot: true as const,
    catalogDetailSection: true as const,
    registrationIntake: true as const,
    registrationInitializer: true as const,
    listProjection: true as const,
    registrationNormalize: true as const,
  },
} as const satisfies Record<string, WorkspaceTransportCapabilities>;

export function getWorkspaceTransportCapabilities(
  workspaceType: string
): WorkspaceTransportCapabilities | null {
  return (
    WORKSPACE_TRANSPORT_CAPABILITIES[
      workspaceType as keyof typeof WORKSPACE_TRANSPORT_CAPABILITIES
    ] ?? null
  );
}
