/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceItineraryCapabilities = {
  readonly supported: true;
  readonly wizardTourField: boolean;
  readonly catalogDetailSection: boolean;
};

export const WORKSPACE_ITINERARY_CAPABILITIES = {
  "denali": {
    supported: true as const,
    wizardTourField: true as const,
    catalogDetailSection: true as const,
  },
} as const satisfies Record<string, WorkspaceItineraryCapabilities>;

export function getWorkspaceItineraryCapabilities(
  workspaceType: string
): WorkspaceItineraryCapabilities | null {
  return (
    WORKSPACE_ITINERARY_CAPABILITIES[
      workspaceType as keyof typeof WORKSPACE_ITINERARY_CAPABILITIES
    ] ?? null
  );
}
