/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceGuestSeoJsonLd = Readonly<{
  readonly required: boolean;
  readonly schemaTypes: readonly string[];
  readonly builderExport: string;
  readonly richResultsProfile?: string;
}>;

export type WorkspaceGuestSeoMarketing = Readonly<{
  readonly listTitleKey?: string;
  readonly listDescriptionKey?: string;
  readonly detailTitleTemplate?: string;
  readonly jsonLd: WorkspaceGuestSeoJsonLd;
  readonly openGraph?: Readonly<{
    readonly type?: string;
    readonly twitterCard?: "summary" | "summary_large_image";
  }>;
  readonly sitemap?: Readonly<{
    readonly changefreq?:
      | "always"
      | "hourly"
      | "daily"
      | "weekly"
      | "monthly"
      | "yearly"
      | "never";
    readonly priority?: number;
    readonly includeImages?: boolean;
  }>;
  readonly pagination?: Readonly<{
    readonly noindexQueryParams?: readonly string[];
  }>;
}>;

export type WorkspaceGuestSeoConfig = Readonly<{
  readonly marketing: WorkspaceGuestSeoMarketing;
}>;

/** Guest marketing SEO policy — derived from workspace.manifest.json guestSeo. */
export const WORKSPACE_GUEST_SEO: Readonly<Record<string, WorkspaceGuestSeoConfig>> = Object.freeze({
  "denali": Object.freeze({
    marketing: Object.freeze({
      listTitleKey: "seo.toursTitle",
      listDescriptionKey: "seo.toursDescription",
      jsonLd: Object.freeze({
        required: true,
        schemaTypes: Object.freeze(["TouristTrip"]),
        builderExport: "buildDenaliTouristTripJsonLd",
        richResultsProfile: "tourist-trip-v1",
      }),
      sitemap: Object.freeze({
        changefreq: "weekly",
        priority: 0.8,
        includeImages: true,
      }),
      pagination: Object.freeze({
        noindexQueryParams: Object.freeze(["cursor","city"]),
      }),
    }),
  }),
  "guest-club": Object.freeze({
    marketing: Object.freeze({
      listTitleKey: "seo.toursTitle",
      listDescriptionKey: "seo.toursDescription",
      jsonLd: Object.freeze({
        required: true,
        schemaTypes: Object.freeze(["Event"]),
        builderExport: "buildGuestClubEventJsonLd",
        richResultsProfile: "event-stub-v1",
      }),
      sitemap: Object.freeze({
        changefreq: "weekly",
        priority: 0.8,
        includeImages: false,
      }),
      pagination: Object.freeze({
        noindexQueryParams: Object.freeze(["cursor"]),
      }),
    }),
  }),
  "urban": Object.freeze({
    marketing: Object.freeze({
      listTitleKey: "seo.toursTitle",
      listDescriptionKey: "seo.toursDescription",
      jsonLd: Object.freeze({
        required: true,
        schemaTypes: Object.freeze(["Event"]),
        builderExport: "buildUrbanEventJsonLd",
        richResultsProfile: "event-v1",
      }),
      sitemap: Object.freeze({
        changefreq: "weekly",
        priority: 0.8,
        includeImages: true,
      }),
      pagination: Object.freeze({
        noindexQueryParams: Object.freeze(["cursor","city"]),
      }),
    }),
  }),
});
