/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Marketing catalog list features — derived from workspace.manifest.json catalogPresentation. */
export const WORKSPACE_CATALOG_LIST_FEATURES: Readonly<
  Record<string, Readonly<{ readonly cityFilter: boolean }>>
> = Object.freeze({
  "denali": Object.freeze({ cityFilter: false }),
  "guest-club": Object.freeze({ cityFilter: false }),
  "urban": Object.freeze({ cityFilter: true }),
});
