/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Guest surface conformance level (PF-0.5 stub — manifest-derived only). */
export const WORKSPACE_GUEST_CONFORMANCE_LEVELS: Readonly<
  Record<string, "L0" | "L1" | "L2" | "L3">
> = Object.freeze({
  "denali": "L3",
  "guest-club": "L3",
  "starter": "L0",
  "urban": "L3",
});

export type WorkspaceGuestConformanceLevel = "L0" | "L1" | "L2" | "L3";
