/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceMarketingPagesCapabilities = {
  readonly supported: true;
  readonly defaultModuleEnabledWhenUnset: boolean;
  readonly operatorEditor: boolean;
  readonly allowedPageKeys: readonly string[];
};

export const WORKSPACE_MARKETING_PAGES_CAPABILITIES = {
  "denali": {
    supported: true as const,
    defaultModuleEnabledWhenUnset: true as const,
    operatorEditor: true as const,
    allowedPageKeys: Object.freeze(["home-hero"]),
  },
} as const;

export function getWorkspaceMarketingPagesCapabilities(
  workspaceType: string,
): WorkspaceMarketingPagesCapabilities | null {
  const key = workspaceType.trim().toLowerCase();
  return (WORKSPACE_MARKETING_PAGES_CAPABILITIES as Record<string, WorkspaceMarketingPagesCapabilities>)[key] ?? null;
}
