/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceEquipmentCapabilities = {
  readonly supported: true;
  readonly defaultModuleEnabledWhenUnset: boolean;
  readonly operatorSettings: boolean;
  readonly wizardTourField: boolean;
  readonly catalogDetailSection: boolean;
  readonly guestLandingSection: boolean;
  readonly registrationSnapshot: boolean;
};

export const WORKSPACE_EQUIPMENT_CAPABILITIES = {
  "denali": {
    supported: true as const,
    defaultModuleEnabledWhenUnset: true as const,
    operatorSettings: true as const,
    wizardTourField: true as const,
    catalogDetailSection: true as const,
    guestLandingSection: false as const,
    registrationSnapshot: true as const,
  },
} as const satisfies Record<string, WorkspaceEquipmentCapabilities>;

export function getWorkspaceEquipmentCapabilities(
  workspaceType: string
): WorkspaceEquipmentCapabilities | null {
  return (
  WORKSPACE_EQUIPMENT_CAPABILITIES[
    workspaceType as keyof typeof WORKSPACE_EQUIPMENT_CAPABILITIES
  ] ?? null
  );
}
