/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceWalletCapabilities = {
  readonly supported: true;
  readonly defaultModuleEnabledWhenUnset: boolean;
  readonly memberAccounts: boolean;
  readonly ops: boolean;
  readonly gatewayTopUp: boolean;
  readonly withdrawals: boolean;
};

export const WORKSPACE_WALLET_CAPABILITIES = {} as const;

export function getWorkspaceWalletCapabilities(
  _workspaceType: string
): WorkspaceWalletCapabilities | null {
  return null;
}

export function listWalletCapableWorkspaceTypes(): readonly string[] {
  return [];
}

export function walletWorkspaceHasCapability(
  _workspaceType: string,
  _capability: "memberAccounts" | "ops" | "gatewayTopUp" | "withdrawals"
): boolean {
  return false;
}
