/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Production onboarding tier (Phase H — manifest-derived only). */
export const WORKSPACE_PRODUCTION_CERTIFICATION: Readonly<
  Record<string, "stub" | "certified">
> = Object.freeze({
  "booking-ws2": "stub",
  "denali": "certified",
  "finance-ws2": "stub",
  "finance-ws3": "stub",
  "finance-ws4": "stub",
  "finance-ws5": "stub",
  "finance-ws6": "stub",
  "guest-club": "stub",
  "starter": "stub",
  "urban": "stub",
});

export type WorkspaceProductionCertificationTier = "stub" | "certified";
