/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Marketing catalog list features — derived from workspace.manifest.json catalogPresentation. */
export const WORKSPACE_CATALOG_LIST_FEATURES: Readonly<
  Record<
    string,
    Readonly<{ readonly cityFilter: boolean; readonly serverListFilters: readonly string[] }>
  >
> = Object.freeze({
  "cert-club": Object.freeze({ cityFilter: false, serverListFilters: Object.freeze([]) }),
  "cert-events": Object.freeze({ cityFilter: false, serverListFilters: Object.freeze([]) }),
  "denali": Object.freeze({ cityFilter: false, serverListFilters: Object.freeze(["availability", "category", "difficulty", "fitness", "q", "sort"]) }),
  "guest-club": Object.freeze({ cityFilter: false, serverListFilters: Object.freeze([]) }),
  "harbor": Object.freeze({ cityFilter: true, serverListFilters: Object.freeze([]) }),
  "profile-cert": Object.freeze({ cityFilter: true, serverListFilters: Object.freeze([]) }),
  "urban": Object.freeze({ cityFilter: true, serverListFilters: Object.freeze([]) }),
});
