/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Marketing catalog detail section gates — derived from workspace.manifest.json catalogPresentation. */
export const WORKSPACE_CATALOG_DETAIL_SECTIONS: Readonly<
  Record<
    string,
    Readonly<{
      readonly difficulty: boolean;
      readonly fitness: boolean;
      readonly itinerary: boolean;
      readonly policies: boolean;
    }>
  >
> = Object.freeze({
  "denali": Object.freeze({
    difficulty: true,
    fitness: true,
    itinerary: true,
    policies: true,
  }),
  "guest-club": Object.freeze({
    difficulty: false,
    fitness: false,
    itinerary: false,
    policies: false,
  }),
  "harbor": Object.freeze({
    difficulty: false,
    fitness: false,
    itinerary: false,
    policies: true,
  }),
  "profile-cert": Object.freeze({
    difficulty: false,
    fitness: false,
    itinerary: true,
    policies: true,
  }),
  "urban": Object.freeze({
    difficulty: false,
    fitness: false,
    itinerary: false,
    policies: false,
  }),
});
