/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceTicketingCategoryDefinition = {
  readonly code: string;
  readonly labelKey: string;
  readonly description?: string;
  readonly icon?: string;
  readonly sortOrder: number;
  readonly defaultPriority?: string;
};

export type WorkspaceTicketingCapabilities = {
  readonly supported: true;
  readonly defaultModuleEnabledWhenUnset: boolean;
  readonly memberCreate: boolean;
  readonly operatorInbox: boolean;
  readonly tags: boolean;
  readonly queues: boolean;
  readonly teams: boolean;
  readonly attachments: boolean;
  readonly defaultCategoryCode: string;
  readonly allowedPriorities: readonly string[];
  readonly maxAttachmentSizeBytes: number;
  readonly categories: readonly WorkspaceTicketingCategoryDefinition[];
};

export const WORKSPACE_TICKETING_CAPABILITIES = {
  "denali": {
    supported: true as const,
    defaultModuleEnabledWhenUnset: false as const,
    memberCreate: true as const,
    operatorInbox: true as const,
    tags: true as const,
    queues: true as const,
    teams: true as const,
    attachments: true as const,
    defaultCategoryCode: "general",
    allowedPriorities: ["low","normal","high","urgent"] as const,
    maxAttachmentSizeBytes: 10485760,
    categories: [
      {
        code: "general",
        labelKey: "ticketing.category.general",
        description: "General support requests",
        
        sortOrder: 0,
        defaultPriority: "normal",
      },
      {
        code: "billing",
        labelKey: "ticketing.category.billing",
        description: "Payments, invoices, and refunds",
        
        sortOrder: 10,
        
      },
      {
        code: "tour",
        labelKey: "ticketing.category.tour",
        description: "Tour and registration questions",
        
        sortOrder: 20,
        
      },
      {
        code: "technical",
        labelKey: "ticketing.category.technical",
        description: "Technical issues and account access",
        
        sortOrder: 30,
        
      }
    ] as const,
  },
} as const satisfies Record<string, WorkspaceTicketingCapabilities>;

export function getWorkspaceTicketingCapabilities(
  workspaceType: string,
): WorkspaceTicketingCapabilities | null {
  const key = workspaceType.trim().toLowerCase();
  if (key.length === 0) {
    return null;
  }
  const caps = (WORKSPACE_TICKETING_CAPABILITIES as Record<string, WorkspaceTicketingCapabilities>)[key];
  return caps ?? null;
}

export function listTicketingCapableWorkspaceTypes(): readonly string[] {
  return Object.keys(WORKSPACE_TICKETING_CAPABILITIES).sort();
}
