/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceEngagementCapabilities = {
  readonly supported: true;
  readonly defaultModuleEnabledWhenUnset: boolean;
  readonly memberDashboard: boolean;
  readonly operatorOverview: boolean;
};

export const WORKSPACE_ENGAGEMENT_CAPABILITIES = {
  "denali": {
    supported: true as const,
    defaultModuleEnabledWhenUnset: true as const,
    memberDashboard: true as const,
    operatorOverview: true as const,
  },
} as const;

export function getWorkspaceEngagementCapabilities(
  workspaceType: string,
): WorkspaceEngagementCapabilities | null {
  const key = workspaceType.trim().toLowerCase();
  return (WORKSPACE_ENGAGEMENT_CAPABILITIES as Record<string, WorkspaceEngagementCapabilities>)[key] ?? null;
}
