/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspacePluginId } from "./workspace-plugin-id";
import type { WorkspaceTypeId } from "./workspace-type";

export const WORKSPACE_MANIFEST_BINDINGS: readonly {
  readonly workspaceType: WorkspaceTypeId;
  readonly pluginId: WorkspacePluginId;
}[] = [
  { workspaceType: "denali", pluginId: "denali" },
  { workspaceType: "starter", pluginId: "starter" },
  { workspaceType: "urban", pluginId: "urban" },
];
