/**
 * Product-facing copy for `/users` directory. Keeps titles, empty states,
 * and actions aligned with workspace member management language (Persian).
 */

export const USERS_ROUTE_COPY = {
  list: {
    documentTitle: "کاربران",
    pageTitle: "کاربران",
    pageDescription: "مدیریت اعضای ورک‌اسپیس، نقش‌ها و سطوح وفاداری.",
    breadcrumbHome: "خانه",
    breadcrumbUsers: "کاربران",
    loadingSession: "در حال بارگذاری نشست…",
    loadingMembers: "در حال بارگذاری اعضا…",
    signInTitle: "ورود لازم است",
    signInDescription: "نشست شما منقضی شده یا از حساب خارج شده‌اید. برای ادامه وارد شوید.",
    signInButton: "ورود",
    dashboardButton: "داشبورد",
    apiNotConfiguredTitle: "ورک‌اسپیس متصل نیست",
    apiNotConfiguredDescription:
      "این برنامه هنوز به ورک‌اسپیس شما متصل نشده است. از مدیر سیستم بخواهید راه‌اندازی را تکمیل کند تا بتوانید اعضا را مدیریت کنید.",
    loadErrorTitle: "بارگذاری اعضا ناموفق بود",
    loadErrorAccessTitle: "دسترسی محدود است",
    loadErrorFallback: "فهرست اعضا بارگذاری نشد.",
    loadError403: "مجوز مشاهدهٔ اعضا در این ورک‌اسپیس را ندارید.",
    emptyListTitle: "هنوز عضوی نیست",
    emptyListDescription:
      "وقتی افراد به این ورک‌اسپیس بپیوندند، اینجا نمایش داده می‌شوند. دعوت مستقیم از همین صفحه در دسترس است.",
    roleUpdatedToast: "نقش کاربر با موفقیت تغییر یافت",
    roleUpdateErrorToast: "تغییر نقش انجام نشد.",
    selectableLeaderEnabledToast: "قابل انتخاب به‌عنوان لیدر تور فعال شد.",
    selectableLeaderDisabledToast: "قابل انتخاب به‌عنوان لیدر تور غیرفعال شد.",
    selectableLeaderUpdateErrorToast: "به‌روزرسانی وضعیت لیدر انتخابی انجام نشد.",
    searchLabel: "جستجو",
    searchHint: "نام یا ایمیل",
    searchPlaceholder: "جستجو بر اساس نام یا ایمیل…",
    filterRoleLabel: "نقش",
    filterRoleDescription: "فهرست را بر اساس نقش محدود کنید.",
    membersToolbarAriaLabel: "جستجو و فیلتر اعضا",
    tableAriaLabel: "اعضای ورک‌اسپیس",
    columnUser: "کاربر",
    columnSystemRole: "نقش سیستمی",
    columnFinancialsAnalytics: "امور مالی و رتبه‌بندی",
    columnActions: "عملیات",
    neverActiveLabel: "بدون فعالیت اخیر",
    copyEmailSuccessToast: "ایمیل کپی شد",
    copyPhoneSuccessToast: "شماره تماس کپی شد",
    discountMicroBadge: "{n}% تخفیف",
    vipMicroBadge: "عضو VIP",
    goldMicroBadge: "طلایی",
    columnPermanentDiscount: "درصد تخفیف",
    columnRewardBadges: "نشان‌های وفاداری",
    emptyDiscountCell: "—",
    emptyRewardBadgesCell: "—",
    emptyPrivilegesCell: "—",
    phoneVerifiedAria: "شماره تأیید شده",
    phoneUnverifiedAria: "شماره تأیید نشده",
    manageRewardsButton: "مدیریت امتیازات",
    exportCsvAriaLabel: "خروجی CSV اعضا",
    exportCsvButton: "خروجی CSV",
    exportCsvSuccessToast: "خروجی {n} عضو صادر شد",
    exportCsvHeaders: ["نام", "ایمیل", "نقش", "وضعیت", "برچسب‌ها", "تلگرام"] as const,
    exportCsvYes: "بله",
    exportCsvNo: "خیر",
    inviteUserButton: "دعوت کاربر جدید",
    directoryTabActive: "اعضای ورک‌اسپیس",
    directoryTabPending: "دعوت‌نامه‌های در انتظار",
    pendingInvitesTableAria: "دعوت‌نامه‌های در انتظار",
    pendingColumnPhoneNote: "شماره / یادداشت",
    pendingColumnRole: "نقش",
    pendingColumnExpires: "انقضا",
    pendingEmptyTitle: "دعوت در انتظاری نیست",
    pendingEmptyDescription: "دعوت‌های صادرشده که هنوز پذیرفته نشده‌اند اینجا نمایش داده می‌شوند.",
    pendingLoading: "در حال بارگذاری دعوت‌ها…",
    pendingLoadError: "بارگذاری دعوت‌نامه‌ها ناموفق بود.",
    pendingResendSms: "ارسال مجدد پیامک",
    pendingCancelInvite: "لغو دعوت",
    pendingResendSuccessToast: "پیامک دعوت مجدداً ارسال شد",
    pendingCancelSuccessToast: "دعوت لغو شد",
    pendingActionErrorFallback: "عملیات روی دعوت انجام نشد",
    roleFilterAll: "همهٔ نقش‌ها",
    roleFilterOwner: "مالک",
    roleFilterLeader: "راهبر",
    roleFilterAdmin: "مدیر",
    roleFilterMember: "عضو عادی",
    roleFilterViewer: "بیننده",
    inviteModal: {
      title: "دعوت عضو جدید",
      phoneLabel: "شماره موبایل",
      phonePlaceholder: "مثلاً ۰۹۱۲۱۲۳۴۵۶۷",
      nameNoteLabel: "یادداشت نام (اختیاری)",
      nameNoteHint: "فقط در این مرورگر ذخیره می‌شود تا در فهرست دعوت‌ها ببینید.",
      nameNotePlaceholder: "مثلاً علی — مهمان آژانس",
      roleLabel: "نقش سازمانی",
      roleAdmin: "مدیر",
      roleMember: "عضو عادی",
      roleViewer: "بیننده",
      cancelButton: "انصراف",
      submitButton: "ارسال دعوت",
      submittingButton: "در حال ارسال…",
      successToast: "دعوت‌نامه با موفقیت صادر و پیامک شد",
      submitErrorFallback: "صدور دعوت‌نامه انجام نشد"
    },
    rowActionsMenuAriaLabel: "عملیات برای {name}",
    rowActionsPlaceholder: "—",
    menuChangeRole: "تغییر نقش",
    menuCurrentRole: "فعلی",
    menuManageRewards: "مدیریت امتیازات",
    menuPrivilegesSection: "امتیازات",
    menuToggleSelectableLeaderOn: "فعال‌سازی لیدر انتخابی (فرم تور)",
    menuToggleSelectableLeaderOff: "غیرفعال‌سازی لیدر انتخابی (فرم تور)",
    selectableLeaderBadge: "لیدر انتخابی",
    menuRemoveUser: "حذف از ورک‌اسپیس",
    menuRemovingUser: "در حال حذف…",
    menuSuspendUser: "تعلیق عضو",
    menuReactivateUser: "فعال‌سازی مجدد",
    menuResendInvite: "ارسال مجدد دعوت",
    removeUserSuccessToast: "عضو از ورک‌اسپیس حذف شد.",
    removeUserErrorToast: "حذف عضو انجام نشد.",
    telegramLinkedAria: "حساب تلگرام متصل است",
    emptyLabelsCell: "—",
    rewardsModal: {
      title: "مدیریت عضو",
      tabPrivileges: "امتیازات و تگ‌ها",
      tabTripHistory: "سابقه سفرها",
      description: "امتیازات و برچسب‌های CRM برای {name} در این فضای کاری.",
      discountLabel: "تخفیف دائمی (٪)",
      discountHint: "عدد صحیح ۰ تا ۱۰۰. خالی بگذارید تا تخفیف حذف شود.",
      discountPlaceholder: "مثلاً ۱۰",
      discountValidationError: "تخفیف باید عدد صحیح بین ۰ و ۱۰۰ باشد.",
      discountSliderAriaLabel: "تنظیم درصد تخفیف دائمی",
      selectableLeaderLabel: "قابل انتخاب به‌عنوان لیدر تور",
      selectableLeaderHint: "این عضو در انتخابگر لیدر تور دنالی نمایش داده می‌شود.",
      loyaltyClubLabel: "سطح باشگاه وفاداری",
      loyaltyClubNone: "عضو عادی",
      loyaltyClubVip: "عضو VIP",
      loyaltyClubGold: "طلایی",
      loyaltyClubHint: "حداکثر یک سطح باشگاه برای هر عضو ذخیره می‌شود.",
      labelsLabel: "برچسب‌های CRM",
      labelsHint: "برچسب‌های نمایشی در فهرست اعضا (حداکثر ۳۲ برچسب).",
      labelsInputPlaceholder: "برچسب جدید…",
      labelsAddButton: "افزودن",
      labelsRemoveAria: "حذف برچسب {label}",
      cancelButton: "انصراف",
      saveButton: "ذخیره",
      savingButton: "در حال ذخیره…",
      savedToast: "امتیازات و برچسب‌های عضو با موفقیت بروزرسانی شد",
      saveErrorFallback: "ذخیره امتیازات عضو انجام نشد.",
      tripHistoryLoading: "در حال بارگذاری سفرها…",
      tripHistoryError: "بارگذاری سابقه سفر ناموفق بود.",
      tripHistoryEmpty: "هیچ سفری با این آژانس ثبت نشده است",
      tripColumnTour: "تور",
      tripColumnDeparture: "تاریخ حرکت",
      tripColumnRegistration: "وضعیت ثبت‌نام",
      tripColumnPayment: "وضعیت پرداخت"
    },
    paginationNavAriaLabel: "صفحه‌بندی فهرست اعضا",
    paginationPrevAriaLabel: "صفحهٔ قبلی اعضا",
    paginationNextAriaLabel: "صفحهٔ بعدی اعضا",
    noResultsTitle: "نتیجه‌ای یافت نشد",
    noResultsDescription: "عبارت جستجو یا فیلتر نقش را تغییر دهید.",
    clearFiltersButton: "پاک کردن فیلترها",
    roleSelectHintSelf: "نقش خودتان از اینجا قابل تغییر نیست.",
    roleSelectHintOwnerTarget: "نقش مالک ورک‌اسپیس از این فهرست قابل ویرایش نیست.",
    roleSelectHintUnknownRole:
      "این عضویت نقشی دارد که از این فهرست قابل ویرایش نیست. در صورت نیاز صفحه را تازه کنید.",
    roleSelectHintInsufficientRank:
      "نمی‌توانید نقش افرادی در سطح دسترسی شما یا بالاتر را تغییر دهید.",
    roleSelectHintNoAlternative: "با سطح دسترسی فعلی شما نقش دیگری برای این عضو در دسترس نیست.",
    roleSelectHintSaving: "در حال ذخیرهٔ نقش…",
    deleteUserButton: "حذف",
    deleteUserUnavailableHint: "حذف کاربر از این صفحه هنوز در دسترس نیست.",
    bulkActionsAriaLabel: "عملیات گروهی روی اعضای انتخاب‌شده",
    bulkSelectedCountSuffix: "عضو انتخاب شده",
    bulkChangeRoleLabel: "تغییر نقش",
    bulkChangeRoleAriaLabel: "تغییر نقش اعضای انتخاب‌شده",
    bulkChangeRolePlaceholder: "انتخاب نقش",
    bulkClearSelectionButton: "لغو انتخاب",
    bulkApplyRoleButton: "اعمال",
    bulkSuspendUsersButton: "تعلیق اعضا",
    bulkReactivateUsersButton: "فعال‌سازی مجدد",
    bulkRemoveUsersButton: "حذف اعضا",
    refreshingLabel: "در حال به‌روزرسانی…",
    loadingMoreUsersLabel: "در حال بارگذاری اعضای بیشتر…",
    directoryMembersWord: "عضو",
    directoryMoreAvailableHint: "با اسکرول، اعضای بیشتری بارگذاری می‌شود.",
    directoryLoadMoreButton: "بارگذاری بیشتر"
  },
  metadata: {
    listTitle: "کاربران",
    listDescription: "اعضا و نقش‌ها در ورک‌اسپیس شما."
  }
} as const;
