/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceUpgradePreflightInput } from "../manifest/workspace-versioning";
import { runWorkspaceUpgradePreflight } from "../manifest/workspace-versioning";

export const WORKSPACE_PROFILE_VERSION_CATALOG = Object.freeze({
    "starter-outdoor": Object.freeze([1]),
});

export const WORKSPACE_CAPABILITY_VERSION_CATALOG = Object.freeze({
    "alpine": Object.freeze({
      "workspaceFinance": Object.freeze([1]),
    }),
    "booking-ws2": Object.freeze({
      "workspaceBooking": Object.freeze([1]),
    }),
    "cert-club": Object.freeze({
      "workspaceEquipment": Object.freeze([1]),
      "workspaceTransport": Object.freeze([1]),
    }),
    "denali": Object.freeze({
      "workspaceBooking": Object.freeze([1]),
      "workspaceDifficultyFitness": Object.freeze([1]),
      "workspaceEquipment": Object.freeze([1]),
      "workspaceFinance": Object.freeze([1]),
      "workspaceItinerary": Object.freeze([1]),
      "workspacePricing": Object.freeze([1]),
      "workspaceTransport": Object.freeze([1]),
    }),
    "finance-ws5": Object.freeze({
      "workspaceFinance": Object.freeze([1]),
    }),
});

export function createWorkspaceUpgradePreflightInput(
  workspaceType: string,
  currentPins: WorkspaceUpgradePreflightInput["currentPins"],
  targetPins: WorkspaceUpgradePreflightInput["targetPins"]
): WorkspaceUpgradePreflightInput {
  return {
    workspaceType,
    currentPins,
    targetPins,
    profileCatalog: WORKSPACE_PROFILE_VERSION_CATALOG,
    capabilityCatalog: WORKSPACE_CAPABILITY_VERSION_CATALOG,
  };
}

export { runWorkspaceUpgradePreflight };
