/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceProfileVersionRegistry = Readonly<Record<string, readonly number[]>>;

/** Profile catalog versions — monotonic integers per profile id (MAT-001). */
export const WORKSPACE_PROFILE_VERSION_REGISTRY: WorkspaceProfileVersionRegistry = Object.freeze({
  "starter-outdoor": Object.freeze([1]),
});

export function listSupportedProfileVersions(profileId: string): readonly number[] | null {
  return WORKSPACE_PROFILE_VERSION_REGISTRY[profileId] ?? null;
}
