/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceProfileExpansionAuditEntry = {
  readonly profileId: string;
  readonly overriddenPaths: readonly string[];
};

export const WORKSPACE_PROFILE_EXPANSION_AUDIT = {
  "acme": null,
  "alpine": null,
  "booking-ws2": null,
  "denali": null,
  "finance-ws2": null,
  "finance-ws3": null,
  "finance-ws4": null,
  "finance-ws5": null,
  "finance-ws6": null,
  "guest-club": null,
  "harbor": null,
  "policy-cert": null,
  "starter": null,
  "urban": null,
} as const satisfies Record<string, WorkspaceProfileExpansionAuditEntry | null>;
