/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceWizardResumeAuditEntry =
  | { readonly mode: "noop" }
  | { readonly mode: "generic" }
  | { readonly mode: "module"; readonly module: string; readonly export: string };

/** Manifest-declared wizard resume placement — DEC-CW-05 Option C inspectability. */
export const WORKSPACE_WIZARD_RESUME_AUDIT = {
  "acme": null,
  "alpine": null,
  "booking-ws2": null,
  "cert-club": { mode: "noop" },
  "cert-events": null,
  "denali": {
    mode: "module",
    module: "./wizard/resolve-initial-step-index",
    export: "resolveDenaliInitialStepIndexFromHostInput",
  },
  "finance-ws2": null,
  "finance-ws3": null,
  "finance-ws4": null,
  "finance-ws5": null,
  "finance-ws6": null,
  "guest-club": null,
  "harbor": null,
  "policy-cert": null,
  "profile-cert": { mode: "noop" },
  "starter": null,
  "urban": null,
  "wallet-ws1": null,
} as const satisfies Record<string, WorkspaceWizardResumeAuditEntry | null>;
