/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceCapabilityRevisionRegistry = Readonly<
  Record<string, Readonly<Record<string, number>>>
>;

/** Manifest-declared capability revisions — default 1 when omitted (MAT-001). */
export const WORKSPACE_CAPABILITY_REVISION_REGISTRY: WorkspaceCapabilityRevisionRegistry = Object.freeze({
  "alpine": Object.freeze({
    "workspaceFinance": 1,
  }),
  "booking-ws2": Object.freeze({
    "workspaceBooking": 1,
  }),
  "cert-club": Object.freeze({
    "workspaceEquipment": 1,
    "workspaceTransport": 1,
  }),
  "denali": Object.freeze({
    "workspaceBooking": 1,
    "workspaceDifficultyFitness": 1,
    "workspaceEquipment": 1,
    "workspaceFinance": 1,
    "workspaceItinerary": 1,
    "workspacePricing": 1,
    "workspaceTransport": 1,
  }),
  "finance-ws5": Object.freeze({
    "workspaceFinance": 1,
  }),
});

export function listWorkspaceCapabilityRevisions(
  workspaceType: string
): Readonly<Record<string, number>> | null {
  return WORKSPACE_CAPABILITY_REVISION_REGISTRY[workspaceType] ?? null;
}

export function resolveRegisteredCapabilityRevision(
  workspaceType: string,
  capabilityId: string
): number | null {
  const row = listWorkspaceCapabilityRevisions(workspaceType);
  if (row === null) {
    return null;
  }
  return row[capabilityId] ?? null;
}
