/**
 * Content-quality weights for Denali wizard fields (canonical path → points).
 * Higher weight = more impact on the completion progress indicator.
 */
export const DENALI_FIELD_COMPLETION_WEIGHTS: Readonly<Record<string, number>> = {
  title: 5,
  publishStatus: 0,
  category: 4,
  eventVariant: 0,
  destinationId: 5,
  startDateTime: 5,
  endDateTime: 4,
  capacityMax: 4,
  capacityMin: 2,
  meetingPoint: 1,
  startPointLocationText: 2,
  approximateReturnTime: 2,
  leaderUserIds: 2,
  requiresLocalGuide: 1,
  localGuideName: 1,
  requiresManualAdminApproval: 1,
  socialMediaLink: 2,
  "program.themeIds": 3,
  "program.shortDescription": 6,
  "program.longDescription": 4,
  "program.difficultyLevel": 3,
  "program.hikingHoursApprox": 3,
  "program.hikingGoHours": 2,
  "program.hikingReturnHours": 2,
  "tripDetails.overview.peakHeight": 3,
  "tripDetails.metrics.elevationGain": 2,
  "program.itinerary": 5,
  gatheringPoints: 4,
  startPoint: 3,
  summitPoint: 3,
  campPoint: 3,
  endPoint: 3,
  "participants.gearItems": 4,
  "tripDetails.overview.customServiceLabels": 2,
  "transport.mode": 4,
  "transport.transportCost": 2,
  "transport.allowPersonalCar": 1,
  "transport.dongAmount": 3,
  "transport.adminCapacityApproval": 1,
  photos: 10,
  "pricing.requiresPayment": 2,
  "pricing.basePricePerPerson": 4,
  "pricing.paymentMode": 2,
  "pricing.includesTourInsurance": 1,
  "participants.nationalIdRequired": 2,
  "policies.cancellationDeadlineHours": 2,
  "policies.cancellationPenaltyPercentage": 2,
  "policies.policiesText": 3,
  "participants.minimumAge": 3,
  "participants.maximumAge": 2,
  "participants.fitnessLevel": 3,
  "participants.sportsInsuranceRequired": 3,
  "participants.fitnessPrerequisiteText": 2,
  "participants.minRequiredPeaks": 0,
};

export function getDenaliFieldCompletionWeight(canonicalPath: string): number {
  return DENALI_FIELD_COMPLETION_WEIGHTS[canonicalPath] ?? 1;
}
