/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { CanonicalDocument, TourListProjectionFields } from "@app-tour/workspace-sdk";
import { extractDenaliTourListProjection } from "@app-tour/workspace-denali/host/list/tour-list-projection";
import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";
import { extractUrbanTourListProjection } from "@app-tour/workspace-urban/host/list/tour-list-projection";
import { URBAN_WORKSPACE_TYPE } from "@app-tour/workspace-urban";

const WORKSPACE_TOUR_LIST_PROJECTION_BINDINGS = [
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    extractTourListProjection: extractDenaliTourListProjection,
  },
  {
    workspaceType: URBAN_WORKSPACE_TYPE,
    extractTourListProjection: extractUrbanTourListProjection,
  },
] as const;

const bindingsByWorkspaceType = Object.freeze(
  Object.fromEntries(
    WORKSPACE_TOUR_LIST_PROJECTION_BINDINGS.map((binding) => [
      binding.workspaceType as string,
      binding,
    ])
  )
) as Readonly<Record<string, (typeof WORKSPACE_TOUR_LIST_PROJECTION_BINDINGS)[number]>>;

function defaultExtractTourListProjection(_canonical: CanonicalDocument): TourListProjectionFields {
  return Object.freeze({
    title: "Untitled tour",
    shortDescription: null,
    listStatus: "draft",
    uiStatus: "draft",
    priceAmount: null,
    priceCurrency: null,
    totalCapacity: null,
    acceptedCount: 0,
    category: null,
    coverImageUrl: null,
    coverImageStorageKey: null,
    departureAt: null,
  });
}

/** CW3-07 — manifest-bound operator tour list projection dispatch for web surfaces. */
export function extractTourListProjectionForWorkspace(
  workspaceType: string | undefined,
  canonical: CanonicalDocument,
): TourListProjectionFields {
  if (workspaceType === undefined) {
    return defaultExtractTourListProjection(canonical);
  }
  const binding = bindingsByWorkspaceType[workspaceType];
  if (binding === undefined) {
    return defaultExtractTourListProjection(canonical);
  }
  return binding.extractTourListProjection(canonical);
}
