export const FINANCE_ROUTE_COPY = {
  metadata: {
    title: "مرکز امور مالی",
    description: "مدیریت فیش‌های واریزی و پرداخت‌های دستی ورک‌اسپیس.",
  },
  page: {
    documentTitle: "مرکز امور مالی",
    breadcrumbHome: "خانه",
    breadcrumbFinance: "امور مالی",
    title: "مرکز امور مالی",
    description: "مدیریت فیش‌های واریزی و پرداخت‌های دستی ورک‌اسپیس.",
    moduleDisabledTitle: "ماژول امور مالی فعال نیست",
    moduleDisabledDescription:
      "این ورک‌اسپیس ماژول امور مالی را فعال نکرده است. برای دسترسی با مدیر تماس بگیرید.",
    reviewSectionTitle: "بررسی فیش‌های در انتظار",
    uploadSectionTitle: "بارگذاری فیش واریزی",
  },
  review: {
    lead: "فیش‌های واریزی بارگذاری‌شده را بررسی و تایید یا رد کنید.",
    reviewNoteLabel: "یادداشت و توضیحات حسابداری",
    reviewNotePlaceholder: "برای سوابق مالی و حسابرسی (اختیاری)",
    loadingQueue: "در حال بارگذاری صف بررسی…",
    emptyQueue: "فیشی در انتظار بررسی نیست.",
    receiptRow: (shortId: string, statusLabel: string) => `فیش ${shortId} — ${statusLabel}`,
    paymentRow: (amountLabel: string, shortId: string) => `پرداخت ${amountLabel} (${shortId})`,
    notePrefix: "یادداشت:",
    preview: "مشاهده فیش",
    approve: "تایید فیش واریزی",
    reject: "عدم تایید و رد فیش",
    toastApproved: "فیش واریزی تایید شد.",
    toastRejected: "فیش واریزی رد شد.",
  },
  upload: {
    lead: "بارگذاری فیش واریز نقدی/بانکی",
    description: "برای پرداخت دستی در انتظار، فیش واریز را بارگذاری کنید تا مدیر بررسی کند.",
    loadingPayments: "در حال بارگذاری پرداخت‌ها…",
    pendingPaymentsLabel: "پرداخت‌های دستی در انتظار:",
    paymentIdLabel: "شناسه پرداخت",
    paymentIdPlaceholder: "شناسه UUID پرداخت دستی",
    receiptFileLabel: "فایل فیش",
    noteLabel: "یادداشت (اختیاری)",
    notePlaceholder: "شماره پیگیری یا مرجع واریز",
    submit: "بارگذاری فیش",
    submitting: "در حال بارگذاری…",
    toastUploaded: "فیش با موفقیت بارگذاری شد.",
    errors: {
      paymentIdRequired: "شناسه پرداخت الزامی است.",
      fileRequired: "فایل فیش الزامی است.",
    },
  },
} as const;
