/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import {
  DenaliFinanceLedgerPolicyAdapter as denali_LedgerPolicy,
  DenaliFinanceReceiptDefaultsAdapter as denali_ReceiptDefaults,
} from "@app-tour/workspace-denali/host/finance";

import {
  FinanceWs2LedgerPolicyAdapter as finance_ws2_LedgerPolicy,
  FinanceWs2ReceiptDefaultsAdapter as finance_ws2_ReceiptDefaults,
} from "@app-tour/workspace-finance-ws2/host/finance";

export const WORKSPACE_FINANCE_DEPENDENCY_BINDINGS = {
  "denali": {
    createLedgerPolicy: () => new denali_LedgerPolicy(),
    createReceiptDefaults: () => new denali_ReceiptDefaults(),
  },
  "finance-ws2": {
    createLedgerPolicy: () => new finance_ws2_LedgerPolicy(),
    createReceiptDefaults: () => new finance_ws2_ReceiptDefaults(),
  },
} as const;

export function isFinanceDependencyBindingRegistered(workspaceType: string): boolean {
  return workspaceType.trim().toLowerCase() in WORKSPACE_FINANCE_DEPENDENCY_BINDINGS;
}

export function listFinanceDependencyWorkspaceTypes(): readonly string[] {
  return Object.keys(WORKSPACE_FINANCE_DEPENDENCY_BINDINGS).sort();
}
