/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";
import { FINANCE_WS3_WORKSPACE_TYPE } from "@app-tour/workspace-finance-ws3";
import { FINANCE_WS4_WORKSPACE_TYPE } from "@app-tour/workspace-finance-ws4";
import { FINANCE_WS5_WORKSPACE_TYPE } from "@app-tour/workspace-finance-ws5";
import { FINANCE_WS6_WORKSPACE_TYPE } from "@app-tour/workspace-finance-ws6";

export const WORKSPACE_FINANCE_BINDINGS = [
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    defaultModuleEnabledWhenUnset: true as const,
  },
  {
    workspaceType: FINANCE_WS3_WORKSPACE_TYPE,
    defaultModuleEnabledWhenUnset: true as const,
  },
  {
    workspaceType: FINANCE_WS4_WORKSPACE_TYPE,
    defaultModuleEnabledWhenUnset: true as const,
  },
  {
    workspaceType: FINANCE_WS5_WORKSPACE_TYPE,
    defaultModuleEnabledWhenUnset: true as const,
  },
  {
    workspaceType: FINANCE_WS6_WORKSPACE_TYPE,
    defaultModuleEnabledWhenUnset: true as const,
  },
] as const;

const supportedWorkspaceTypes = new Set(
  WORKSPACE_FINANCE_BINDINGS.map((binding) => binding.workspaceType as string)
);

const defaultEnabledWhenUnset = new Set(
  WORKSPACE_FINANCE_BINDINGS.filter(
    (binding) => "defaultModuleEnabledWhenUnset" in binding && binding.defaultModuleEnabledWhenUnset === true
  ).map((binding) => binding.workspaceType as string)
);

export function isFinanceSupportedWorkspace(workspaceType: string): boolean {
  return supportedWorkspaceTypes.has(workspaceType);
}

export function isFinanceDefaultEnabledWhenModulesUnset(workspaceType: string): boolean {
  return defaultEnabledWhenUnset.has(workspaceType);
}
