/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export const WORKSPACE_FINANCE_OBLIGATION_BINDINGS = {} as const;

export function isFinanceObligationBindingRegistered(_workspaceType: string): boolean {
  return false;
}

export function listFinanceObligationWorkspaceTypes(): readonly string[] {
  return [];
}
