/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export const WORKSPACE_FINANCE_OBLIGATION_BINDINGS = {
  "denali": {
    loadResolve: async () => {
      const mod = await import("@app-tour/workspace-denali/host/finance");
      return mod.resolveDenaliRegistrationObligationMinor;
    },
    loadPaymentCollection: async () => {
      const mod = await import("@app-tour/workspace-denali/host/finance");
      return mod.resolveDenaliPaymentCollectionMode;
    },
    loadGrossResolve: async () => {
      const mod = await import("@app-tour/workspace-denali/host/finance");
      return mod.resolveDenaliRegistrationGrossObligationMinor;
    },
  },
} as const;

export function isFinanceObligationBindingRegistered(workspaceType: string): boolean {
  return workspaceType.trim().toLowerCase() in WORKSPACE_FINANCE_OBLIGATION_BINDINGS;
}

export function listFinanceObligationWorkspaceTypes(): readonly string[] {
  return Object.keys(WORKSPACE_FINANCE_OBLIGATION_BINDINGS).sort();
}
