/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { DenaliTourCreatedFinanceReactionAdapter as denali_EventReaction } from "@app-tour/workspace-denali/host/finance";

import { FinanceWs5TourCreatedFinanceReactionAdapter as finance_ws5_EventReaction } from "@app-tour/workspace-finance-ws5/host/finance";

export const WORKSPACE_FINANCE_EVENT_REACTION_BINDINGS = {
  "denali": {
    requiresHostIo: true as const,
    create: (hostIo: ConstructorParameters<typeof denali_EventReaction>[0]) => new denali_EventReaction(hostIo),
  },
  "finance-ws5": {
    requiresHostIo: false as const,
    create: () => new finance_ws5_EventReaction(),
  },
} as const;

export function isFinanceEventReactionBindingRegistered(workspaceType: string): boolean {
  return workspaceType.trim().toLowerCase() in WORKSPACE_FINANCE_EVENT_REACTION_BINDINGS;
}
