/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";
import { FINANCE_WS5_WORKSPACE_TYPE } from "@app-tour/workspace-finance-ws5";

export type FinanceEventReactionCapability = "durable-outbox" | "ack-only" | "none";

export type FinanceWorkspaceCapabilities = {
  readonly supported: true;
  readonly ledgerCapture: boolean;
  readonly eventReactions: FinanceEventReactionCapability;
  readonly ops: boolean;
};

/**
 * Capability matrix — product gate (`supported`) vs money-path grades.
 * Denali: durable-outbox TourCreated. finance-ws5: ack-only TourCreated.
 * Both may claim ledgerCapture for HTTP receipt/payment journals.
 */
export const WORKSPACE_FINANCE_CAPABILITIES = {
  [DENALI_WORKSPACE_TYPE]: {
    supported: true as const,
    ledgerCapture: true as const,
    eventReactions: "durable-outbox" as const,
    ops: true as const,
  },
  [FINANCE_WS5_WORKSPACE_TYPE]: {
    supported: true as const,
    ledgerCapture: true as const,
    eventReactions: "ack-only" as const,
    ops: true as const,
  },
} as const satisfies Record<string, FinanceWorkspaceCapabilities>;

export function getFinanceWorkspaceCapabilities(
  workspaceType: string
): FinanceWorkspaceCapabilities | null {
  const key = workspaceType.trim();
  if (key.length === 0) {
    return null;
  }
  const caps = (WORKSPACE_FINANCE_CAPABILITIES as Record<string, FinanceWorkspaceCapabilities>)[key];
  return caps ?? null;
}

export function listFinanceCapableWorkspaceTypes(): readonly string[] {
  return Object.keys(WORKSPACE_FINANCE_CAPABILITIES).sort();
}

export function financeWorkspaceHasCapability(
  workspaceType: string,
  capability: "ledgerCapture" | "ops"
): boolean {
  const caps = getFinanceWorkspaceCapabilities(workspaceType);
  if (caps === null) {
    return false;
  }
  return caps[capability] === true;
}

export function financeWorkspaceEventReactionCapability(
  workspaceType: string
): FinanceEventReactionCapability | null {
  return getFinanceWorkspaceCapabilities(workspaceType)?.eventReactions ?? null;
}
