/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export const WORKSPACE_FINANCE_CHART_OF_ACCOUNTS_BINDINGS = {
  "denali": {
    loadAccounts: async () => {
      const mod = await import("@app-tour/workspace-denali/host/finance");
      return mod.LEDGER_ACCOUNTS;
    },
  },
  "finance-ws2": {
    loadAccounts: async () => {
      const mod = await import("@app-tour/workspace-finance-ws2/host/finance");
      return mod.FINANCE_WS2_LEDGER_ACCOUNTS;
    },
  },
  "finance-ws3": {
    loadAccounts: async () => {
      const mod = await import("@app-tour/workspace-finance-ws3/host/finance");
      return mod.FINANCE_WS3_LEDGER_ACCOUNTS;
    },
  },
  "finance-ws4": {
    loadAccounts: async () => {
      const mod = await import("@app-tour/workspace-finance-ws4/host/finance");
      return mod.FINANCE_WS4_LEDGER_ACCOUNTS;
    },
  },
  "finance-ws5": {
    loadAccounts: async () => {
      const mod = await import("@app-tour/workspace-finance-ws5/host/finance");
      return mod.FINANCE_WS5_LEDGER_ACCOUNTS;
    },
  },
  "finance-ws6": {
    loadAccounts: async () => {
      const mod = await import("@app-tour/workspace-finance-ws6/host/finance");
      return mod.FINANCE_WS6_LEDGER_ACCOUNTS;
    },
  },
} as const;

export function isFinanceChartOfAccountsBindingRegistered(workspaceType: string): boolean {
  return workspaceType.trim().toLowerCase() in WORKSPACE_FINANCE_CHART_OF_ACCOUNTS_BINDINGS;
}

export function listFinanceChartOfAccountsWorkspaceTypes(): readonly string[] {
  return Object.keys(WORKSPACE_FINANCE_CHART_OF_ACCOUNTS_BINDINGS).sort();
}
