/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { LEDGER_ACCOUNTS as denali_ChartOfAccounts } from "@app-tour/workspace-denali/host/finance";

import { FINANCE_WS2_LEDGER_ACCOUNTS as finance_ws2_ChartOfAccounts } from "@app-tour/workspace-finance-ws2/host/finance";

export const WORKSPACE_FINANCE_CHART_OF_ACCOUNTS_BINDINGS = {
  "denali": {
    getAccounts: () => denali_ChartOfAccounts,
  },
  "finance-ws2": {
    getAccounts: () => finance_ws2_ChartOfAccounts,
  },
} as const;

export function isFinanceChartOfAccountsBindingRegistered(workspaceType: string): boolean {
  return workspaceType.trim().toLowerCase() in WORKSPACE_FINANCE_CHART_OF_ACCOUNTS_BINDINGS;
}

export function listFinanceChartOfAccountsWorkspaceTypes(): readonly string[] {
  return Object.keys(WORKSPACE_FINANCE_CHART_OF_ACCOUNTS_BINDINGS).sort();
}
