/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export const WORKSPACE_FINANCE_DEPENDENCY_BINDINGS = {
  "denali": {
    createLedgerPolicy: async () => {
      const mod = await import("@app-tour/workspace-denali/host/finance");
      return new mod.DenaliFinanceLedgerPolicyAdapter();
    },
    createReceiptDefaults: async () => {
      const mod = await import("@app-tour/workspace-denali/host/finance");
      return new mod.DenaliFinanceReceiptDefaultsAdapter();
    },
  },
  "finance-ws2": {
    createLedgerPolicy: async () => {
      const mod = await import("@app-tour/workspace-finance-ws2/host/finance");
      return new mod.FinanceWs2LedgerPolicyAdapter();
    },
    createReceiptDefaults: async () => {
      const mod = await import("@app-tour/workspace-finance-ws2/host/finance");
      return new mod.FinanceWs2ReceiptDefaultsAdapter();
    },
  },
  "finance-ws3": {
    createLedgerPolicy: async () => {
      const mod = await import("@app-tour/workspace-finance-ws3/host/finance");
      return new mod.FinanceWs3LedgerPolicyAdapter();
    },
    createReceiptDefaults: async () => {
      const mod = await import("@app-tour/workspace-finance-ws3/host/finance");
      return new mod.FinanceWs3ReceiptDefaultsAdapter();
    },
  },
  "finance-ws4": {
    createLedgerPolicy: async () => {
      const mod = await import("@app-tour/workspace-finance-ws4/host/finance");
      return new mod.FinanceWs4LedgerPolicyAdapter();
    },
    createReceiptDefaults: async () => {
      const mod = await import("@app-tour/workspace-finance-ws4/host/finance");
      return new mod.FinanceWs4ReceiptDefaultsAdapter();
    },
  },
  "finance-ws5": {
    createLedgerPolicy: async () => {
      const mod = await import("@app-tour/workspace-finance-ws5/host/finance");
      return new mod.FinanceWs5LedgerPolicyAdapter();
    },
    createReceiptDefaults: async () => {
      const mod = await import("@app-tour/workspace-finance-ws5/host/finance");
      return new mod.FinanceWs5ReceiptDefaultsAdapter();
    },
  },
  "finance-ws6": {
    createLedgerPolicy: async () => {
      const mod = await import("@app-tour/workspace-finance-ws6/host/finance");
      return new mod.FinanceWs6LedgerPolicyAdapter();
    },
    createReceiptDefaults: async () => {
      const mod = await import("@app-tour/workspace-finance-ws6/host/finance");
      return new mod.FinanceWs6ReceiptDefaultsAdapter();
    },
  },
} as const;

export function isFinanceDependencyBindingRegistered(workspaceType: string): boolean {
  return workspaceType.trim().toLowerCase() in WORKSPACE_FINANCE_DEPENDENCY_BINDINGS;
}

export function listFinanceDependencyWorkspaceTypes(): readonly string[] {
  return Object.keys(WORKSPACE_FINANCE_DEPENDENCY_BINDINGS).sort();
}
