/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

/** Operator API capabilities — derived from workspace.manifest.json operatorCapabilities. */
export const WORKSPACE_OPERATOR_CAPABILITIES: Readonly<
  Record<
    string,
    Readonly<{
      readonly usersDirectory: boolean;
      readonly reconciliationTriage: boolean;
      readonly fieldExposureSurfaces: boolean;
    }>
  >
> = Object.freeze({
  "denali": Object.freeze({ usersDirectory: true, reconciliationTriage: true, fieldExposureSurfaces: true }),
  "guest-club": Object.freeze({ usersDirectory: false, reconciliationTriage: false, fieldExposureSurfaces: false }),
  "harbor": Object.freeze({ usersDirectory: false, reconciliationTriage: false, fieldExposureSurfaces: false }),
  "urban": Object.freeze({ usersDirectory: false, reconciliationTriage: false, fieldExposureSurfaces: false }),
});
