/**
 * HTTP route inventory — single SoT for OpenAPI generation and shadow-API guards (DEC-099).
 * @see docs/phase-5/appendices/openapi-dispatch-contract.md
 */
export type DispatchRoute = {
  readonly method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
  readonly path: string;
  readonly summary: string;
  readonly internal?: boolean;
  readonly operationId: string;
};

export const DISPATCH_ROUTES: readonly DispatchRoute[] = [
  {
    method: "GET",
    path: "/health",
    summary: "Liveness probe",
    operationId: "getHealth",
  },
  {
    method: "GET",
    path: "/internal/metrics",
    summary: "Prometheus metrics (dev/test)",
    internal: true,
    operationId: "getInternalMetrics",
  },
  {
    method: "POST",
    path: "/internal/cache/invalidate",
    summary: "Invalidate registry cache / flush Redis rate keys",
    internal: true,
    operationId: "invalidateCache",
  },
  {
    method: "GET",
    path: "/api/v2/tenant-config",
    summary: "Tenant theme and feature flags",
    operationId: "getTenantConfig",
  },
  {
    method: "GET",
    path: "/api/v2/map/enrich",
    summary: "Map upstream enrich proxy",
    operationId: "getMapEnrich",
  },
  {
    method: "POST",
    path: "/internal/tenants/provision",
    summary: "Provision tenant (dev/test only)",
    internal: true,
    operationId: "provisionTenant",
  },
  {
    method: "GET",
    path: "/platform/v1/workspaces",
    summary: "List workspace types available for platform provisioning",
    operationId: "listPlatformWorkspaces",
  },
  {
    method: "GET",
    path: "/platform/v1/tenants",
    summary: "List tenants (platform ops, paginated)",
    operationId: "listPlatformTenants",
  },
  {
    method: "GET",
    path: "/platform/v1/tenants/{tenantId}",
    summary: "Get tenant by id (platform ops)",
    operationId: "getPlatformTenant",
  },
  {
    method: "POST",
    path: "/platform/v1/tenants",
    summary: "Create tenant (platform ops)",
    operationId: "createPlatformTenant",
  },
  {
    method: "PATCH",
    path: "/platform/v1/tenants/{tenantId}/status",
    summary: "Suspend or activate tenant (platform ops)",
    operationId: "patchPlatformTenantStatus",
  },
  {
    method: "POST",
    path: "/platform/v1/tenants/{tenantId}/owner-invite",
    summary: "Resend tenant owner invite (platform ops)",
    operationId: "resendPlatformTenantOwnerInvite",
  },
  {
    method: "GET",
    path: "/platform/v1/tenants/{tenantId}/domains",
    summary: "List custom domains for tenant",
    operationId: "listPlatformTenantDomains",
  },
  {
    method: "POST",
    path: "/platform/v1/tenants/{tenantId}/domains",
    summary: "Add custom domain (platform ops)",
    operationId: "createPlatformTenantDomain",
  },
  {
    method: "DELETE",
    path: "/platform/v1/tenants/{tenantId}/domains/{domainId}",
    summary: "Remove custom domain",
    operationId: "deletePlatformTenantDomain",
  },
  {
    method: "POST",
    path: "/platform/v1/tenants/{tenantId}/domains/{domainId}/verify",
    summary: "Verify tenant domain CNAME (stub)",
    operationId: "verifyPlatformTenantDomain",
  },
  {
    method: "GET",
    path: "/platform/v1/tenants/{tenantId}/sites/check",
    summary: "Check health of tenant site URLs",
    operationId: "checkPlatformTenantSites",
  },
  {
    method: "POST",
    path: "/platform/v1/tenants/{tenantId}/impersonate",
    summary: "Start read-only support impersonation session",
    operationId: "startPlatformTenantImpersonation",
  },
  {
    method: "POST",
    path: "/platform/v1/tenants/{tenantId}/impersonate/end",
    summary: "End support impersonation session (audit)",
    operationId: "endPlatformTenantImpersonation",
  },
  {
    method: "GET",
    path: "/platform/v1/plans",
    summary: "List platform SaaS plans",
    operationId: "listPlatformPlans",
  },
  {
    method: "PATCH",
    path: "/platform/v1/tenants/{tenantId}/subscription",
    summary: "Update tenant platform subscription",
    operationId: "patchPlatformTenantSubscription",
  },
  {
    method: "POST",
    path: "/platform/v1/tenants/{tenantId}/subscription/mark-paid",
    summary: "Mark tenant subscription paid (owner only)",
    operationId: "markPlatformTenantSubscriptionPaid",
  },
  {
    method: "POST",
    path: "/platform/v1/billing/run-past-due-check",
    summary: "Suspend tenants with expired past-due subscriptions",
    operationId: "runPlatformBillingPastDueCheck",
  },
  {
    method: "GET",
    path: "/platform/v1/domains/ssl-summary",
    summary: "Count tenant domains with SSL expiring within 14 days",
    operationId: "getPlatformDomainsSslSummary",
  },
  {
    method: "POST",
    path: "/platform/v1/domains/run-ssl-expiry-check",
    summary: "Audit tenant domains with SSL expiring within 14 days",
    operationId: "runPlatformDomainsSslExpiryCheck",
  },
  {
    method: "POST",
    path: "/platform/v1/tenants/{tenantId}/offboard",
    summary: "Start tenant offboarding (owner only)",
    operationId: "offboardPlatformTenant",
  },
  {
    method: "POST",
    path: "/platform/v1/tenants/{tenantId}/cancel-offboard",
    summary: "Cancel tenant offboarding (owner only)",
    operationId: "cancelPlatformTenantOffboard",
  },
  {
    method: "POST",
    path: "/platform/v1/tenants/{tenantId}/export",
    summary: "Export tenant GDPR zip (owner only)",
    operationId: "exportPlatformTenantGdpr",
  },
  {
    method: "POST",
    path: "/platform/v1/tenants/{tenantId}/purge",
    summary: "Purge offboarded tenant after retention (owner only)",
    operationId: "purgePlatformTenant",
  },
  {
    method: "POST",
    path: "/platform/v1/tenants/run-scheduled-deletions",
    summary: "Purge all tenants past scheduled deletion date",
    operationId: "runPlatformScheduledTenantDeletions",
  },
  {
    method: "GET",
    path: "/platform/v1/audit/export",
    summary: "Export platform audit events as CSV (owner only)",
    operationId: "exportPlatformAuditCsv",
  },
  {
    method: "GET",
    path: "/platform/v1/audit",
    summary: "List platform audit events",
    operationId: "listPlatformAuditEvents",
  },
  {
    method: "GET",
    path: "/platform/v1/team",
    summary: "List platform ops team members",
    operationId: "listPlatformTeam",
  },
  {
    method: "POST",
    path: "/platform/v1/auth/request-otp",
    summary: "Request OTP for platform ops login (phone whitelist)",
    operationId: "requestPlatformAuthOtp",
  },
  {
    method: "POST",
    path: "/platform/v1/auth/verify-otp",
    summary: "Verify OTP for platform ops login",
    operationId: "verifyPlatformAuthOtp",
  },
  {
    method: "POST",
    path: "/platform/v1/team",
    summary: "Add or update platform ops team member (owner only)",
    operationId: "upsertPlatformTeamMember",
  },
  {
    method: "GET",
    path: "/internal/test/db-pool-hold",
    summary: "Test-only pool hold hook",
    internal: true,
    operationId: "dbPoolHold",
  },
  {
    method: "POST",
    path: "/internal/outbox/{outboxId}/replay",
    summary: "Replay failed outbox row",
    internal: true,
    operationId: "replayOutbox",
  },
  {
    method: "POST",
    path: "/internal/payments/webhook",
    summary: "Signed PSP webhook ingress (WH-01)",
    internal: true,
    operationId: "paymentsWebhook",
  },
  // Phase 9.1 — identity production (INV-P9-007 · DEC-P9-012)
  {
    method: "POST",
    path: "/auth/phone-preflight",
    summary: "Check whether mobile may receive OTP on this tenant host",
    operationId: "phonePreflight",
  },
  {
    method: "POST",
    path: "/auth/request-otp",
    summary: "Issue mobile OTP challenge",
    operationId: "requestOtp",
  },
  {
    method: "POST",
    path: "/auth/verify-otp",
    summary: "Verify OTP and issue session JWT",
    operationId: "verifyOtp",
  },
  {
    method: "POST",
    path: "/public/auth/phone-preflight",
    summary: "Public catalog — check whether mobile is already registered",
    operationId: "publicPhonePreflight",
  },
  {
    method: "POST",
    path: "/public/auth/request-otp",
    summary: "Public catalog — issue mobile OTP (no invite gate)",
    operationId: "publicRequestOtp",
  },
  {
    method: "POST",
    path: "/public/auth/verify-otp",
    summary: "Public catalog — verify OTP; session or onboarding token",
    operationId: "publicVerifyOtp",
  },
  {
    method: "POST",
    path: "/public/auth/register/complete",
    summary: "Public catalog — complete guest profile and issue session",
    operationId: "publicRegisterComplete",
  },
  {
    method: "GET",
    path: "/auth/session",
    summary: "Hydrate operator session from cookie or bearer",
    operationId: "getAuthSession",
  },
  {
    method: "GET",
    path: "/auth/ability-context",
    summary: "Membership ability context for operator shell",
    operationId: "getAuthAbilityContext",
  },
  {
    method: "GET",
    path: "/identity/me",
    summary: "Read authenticated operator profile",
    operationId: "getIdentityMe",
  },
  {
    method: "GET",
    path: "/identity/me/entitlements",
    summary: "Read authenticated member module entitlements",
    operationId: "getIdentityMeEntitlements",
  },
  {
    method: "PATCH",
    path: "/identity/me",
    summary: "Patch authenticated operator profile",
    operationId: "patchIdentityMe",
  },
  {
    method: "POST",
    path: "/identity/me/avatar",
    summary: "Upload authenticated operator profile avatar",
    operationId: "uploadIdentityMeAvatar",
  },
  {
    method: "DELETE",
    path: "/identity/me/avatar",
    summary: "Remove authenticated operator profile avatar",
    operationId: "deleteIdentityMeAvatar",
  },
  {
    method: "GET",
    path: "/identity/me/avatar/url",
    summary: "Signed operator profile avatar preview URL",
    operationId: "getIdentityMeAvatarUrl",
  },
  {
    method: "POST",
    path: "/tours",
    summary: "Create tour",
    operationId: "createTour",
  },
  {
    method: "GET",
    path: "/tours",
    summary: "List tours for tenant (cursor pagination)",
    operationId: "listTours",
  },
  {
    method: "GET",
    path: "/tours/{tourId}",
    summary: "Get tour by id",
    operationId: "getTour",
  },
  {
    method: "PATCH",
    path: "/tours/{tourId}",
    summary: "Patch tour (optimistic lock)",
    operationId: "patchTour",
  },
  {
    method: "POST",
    path: "/tours/{tourId}/clone",
    summary: "Clone tour (workspace plugin hydrate + create)",
    operationId: "cloneTour",
  },
  {
    method: "POST",
    path: "/tours/clone-photo-remint",
    summary: "Copy MinIO blobs for wizard clone photo remint plan",
    operationId: "clonePhotoRemint",
  },
  // Phase 8.1 — urban owner settings (INV-P8-007)
  {
    method: "GET",
    path: "/urban/settings",
    summary: "Read urban workspace owner settings (tenants.theme.urban)",
    operationId: "getUrbanSettings",
  },
  {
    method: "PATCH",
    path: "/urban/settings",
    summary: "Patch urban workspace owner settings (tenants.theme.urban)",
    operationId: "patchUrbanSettings",
  },
  // Phase 8.2 — public catalog + registration intake
  {
    method: "GET",
    path: "/urban/catalog",
    summary: "List published urban catalog tours (anonymous)",
    operationId: "getUrbanCatalog",
  },
  {
    method: "GET",
    path: "/urban/catalog/{tourId}",
    summary: "Get published urban catalog tour detail (anonymous)",
    operationId: "getUrbanCatalogTour",
  },
  {
    method: "POST",
    path: "/urban/registrations",
    summary: "Public urban registration intake (anonymous)",
    operationId: "postUrbanRegistration",
  },
  {
    method: "GET",
    path: "/denali/catalog",
    summary: "List published denali catalog tours (anonymous)",
    operationId: "getDenaliCatalog",
  },
  {
    method: "GET",
    path: "/denali/catalog/{tourId}",
    summary: "Get published denali catalog tour detail (anonymous)",
    operationId: "getDenaliCatalogTour",
  },
  {
    method: "POST",
    path: "/denali/registrations",
    summary: "Public denali registration intake (anonymous)",
    operationId: "postDenaliRegistration",
  },
  {
    method: "GET",
    path: "/denali/dashboard/tours/{tourId}",
    summary: "Get registered-user denali dashboard tour card",
    operationId: "getDenaliDashboardTour",
  },
  {
    method: "GET",
    path: "/denali/reminders/feed",
    summary: "List denali reminder feed entries for registered user",
    operationId: "getDenaliReminderFeed",
  },
  // Phase 9.6 — tenant workspace branding (TENANT-WORKSPACE-BRANDING)
  {
    method: "GET",
    path: "/settings/branding",
    summary: "Read tenant workspace branding",
    operationId: "getSettingsBranding",
  },
  {
    method: "PATCH",
    path: "/settings/branding",
    summary: "Patch tenant display name (owner/admin)",
    operationId: "patchSettingsBranding",
  },
  {
    method: "POST",
    path: "/settings/branding/logo",
    summary: "Upload tenant brand logo (owner/admin)",
    operationId: "uploadSettingsBrandLogo",
  },
  {
    method: "DELETE",
    path: "/settings/branding/logo",
    summary: "Remove tenant brand logo (owner/admin)",
    operationId: "deleteSettingsBrandLogo",
  },
  {
    method: "GET",
    path: "/settings/branding/logo/url",
    summary: "Signed read URL for tenant brand logo",
    operationId: "getSettingsBrandLogoUrl",
  },
  {
    method: "GET",
    path: "/public/tenant-branding",
    summary: "Public tenant branding by host subdomain",
    operationId: "getPublicTenantBranding",
  },
  {
    method: "GET",
    path: "/public/tenant-context",
    summary: "Public tenant catalog bootstrap by host subdomain",
    operationId: "getPublicTenantContext",
  },
  // Phase 11.2 / 11.9 — workspace draft snapshots (DEC-P11-003)
  {
    method: "GET",
    path: "/workspaces/{workspaceId}/drafts",
    summary: "List user-scoped workspace draft index rows (no data blobs)",
    operationId: "listWorkspaceDrafts",
  },
  {
    method: "GET",
    path: "/workspaces/{workspaceId}/drafts/{namespace}/{key}/events",
    summary: "List append-only audit events for a workspace draft",
    operationId: "listWorkspaceDraftEvents",
  },
  {
    method: "GET",
    path: "/workspaces/{workspaceId}/drafts/{namespace}/{key}",
    summary: "Read user-scoped workspace draft snapshot",
    operationId: "getWorkspaceDraft",
  },
  {
    method: "PATCH",
    path: "/workspaces/{workspaceId}/drafts/{namespace}/{key}",
    summary: "Patch workspace draft with OCC",
    operationId: "patchWorkspaceDraft",
  },
  {
    method: "DELETE",
    path: "/workspaces/{workspaceId}/drafts/{namespace}/{key}",
    summary: "Delete workspace draft snapshot",
    operationId: "deleteWorkspaceDraft",
  },
] as const;
