import type { IngressSanitizationErrorCode } from "@app-tour/workspace-sdk/ingress";

import type { PlatformCoreErrorCode } from "./platform-core.error";

/** 1:1 map from SDK ingress sanitization codes to platform error codes. */
export const INGRESS_SANITIZATION_TO_PLATFORM: Record<
  IngressSanitizationErrorCode,
  PlatformCoreErrorCode
> = {
  NON_OBJECT_ROOT: "SANITIZE_NON_OBJECT_ROOT",
  ROOT_IS_ARRAY: "SANITIZE_ROOT_IS_ARRAY",
  MAX_DEPTH_EXCEEDED: "SANITIZE_MAX_DEPTH_EXCEEDED",
  FUNCTION_NOT_ALLOWED: "SANITIZE_FUNCTION_NOT_ALLOWED",
  BIGINT_NOT_ALLOWED: "SANITIZE_BIGINT_NOT_ALLOWED",
  SYMBOL_NOT_ALLOWED: "SANITIZE_SYMBOL_NOT_ALLOWED",
  UNSUPPORTED_PRIMITIVE: "SANITIZE_UNSUPPORTED_PRIMITIVE",
  ACCESSOR_PROPERTY: "SANITIZE_ACCESSOR_PROPERTY",
  NON_DATA_DESCRIPTOR: "SANITIZE_NON_DATA_DESCRIPTOR",
  MISSING_DESCRIPTOR: "SANITIZE_MISSING_DESCRIPTOR",
  PROTOTYPE_INTROSPECTION_TRAP: "SANITIZE_PROTOTYPE_INTROSPECTION_TRAP",
  UNSTABLE_PROTOTYPE: "SANITIZE_UNSTABLE_PROTOTYPE",
  NON_PLAIN_PROTOTYPE: "SANITIZE_NON_PLAIN_PROTOTYPE",
  SYMBOL_KEYS: "SANITIZE_SYMBOL_KEYS",
  HIDDEN_NON_ENUMERABLE_KEYS: "SANITIZE_HIDDEN_NON_ENUMERABLE_KEYS",
  ARRAY_NOT_ALLOWED: "SANITIZE_ARRAY_NOT_ALLOWED",
  ARRAY_LIKE_OBJECT: "SANITIZE_ARRAY_LIKE_OBJECT",
  INGRESS_REJECTED: "SANITIZE_INGRESS_REJECTED",
};
