export type PlatformCoreErrorCode =
  | "UNKNOWN_FIELD_ID"
  | "DUPLICATE_FIELD_ID"
  | "DUPLICATE_CELL_ID"
  | "DUPLICATE_CANONICAL_PATH"
  | "INVALID_FIELD_REGISTRY"
  | "INVALID_RULE_SET"
  | "INVALID_WIZARD_SURFACE"
  | "INVALID_VALIDATION_HOOKS"
  | "INVALID_LIFECYCLE"
  | "INVALID_RULE_CONTEXT"
  | "TENANT_ISOLATION_VIOLATION"
  | "PLUGIN_INVALID_SHAPE"
  | "PLUGIN_FUNCTION_NOT_ALLOWED"
  | "PLUGIN_INVALID_ROOT"
  | "UNKNOWN_CANONICAL_PATH"
  | "CANONICAL_TYPE_MISMATCH"
  | "REQUIRED_FIELD_EMPTY"
  | "CANONICAL_INVALID_SCHEMA_VERSION"
  | "CANONICAL_INVALID_ROOTS"
  | "CANONICAL_DUPLICATE_ROOT"
  | "CANONICAL_INVALID_DATA"
  | "CANONICAL_ROOT_UNKNOWN"
  | "CANONICAL_MAX_DEPTH_EXCEEDED"
  | "CANONICAL_FORBIDDEN_BIGINT"
  | "CANONICAL_FORBIDDEN_SYMBOL"
  | "CANONICAL_TOO_MANY_KEYS"
  | "CANONICAL_FORBIDDEN_KEY"
  | "SANITIZE_NON_OBJECT_ROOT"
  | "SANITIZE_ROOT_IS_ARRAY"
  | "SANITIZE_MAX_DEPTH_EXCEEDED"
  | "SANITIZE_FUNCTION_NOT_ALLOWED"
  | "SANITIZE_BIGINT_NOT_ALLOWED"
  | "SANITIZE_SYMBOL_NOT_ALLOWED"
  | "SANITIZE_UNSUPPORTED_PRIMITIVE"
  | "SANITIZE_ACCESSOR_PROPERTY"
  | "SANITIZE_NON_DATA_DESCRIPTOR"
  | "SANITIZE_MISSING_DESCRIPTOR"
  | "SANITIZE_PROTOTYPE_INTROSPECTION_TRAP"
  | "SANITIZE_UNSTABLE_PROTOTYPE"
  | "SANITIZE_NON_PLAIN_PROTOTYPE"
  | "SANITIZE_SYMBOL_KEYS"
  | "SANITIZE_HIDDEN_NON_ENUMERABLE_KEYS"
  | "SANITIZE_ARRAY_NOT_ALLOWED"
  | "SANITIZE_ARRAY_LIKE_OBJECT"
  | "SANITIZE_INGRESS_REJECTED"
  | "RULE_CONTEXT_UNMATCHED"
  | "AMBIGUOUS_RULE_RESOLUTION"
  | "CARDINALITY_VIOLATION"
  | "HIDDEN_FIELD_POISON"
  | "REGISTRY_CARDINALITY_VIOLATION";

export type PlatformCoreErrorDetails = Readonly<Record<string, unknown>>;

export class PlatformCoreError extends Error {
  readonly code: PlatformCoreErrorCode;
  readonly details?: PlatformCoreErrorDetails;

  constructor(
    code: PlatformCoreErrorCode,
    message: string,
    details?: PlatformCoreErrorDetails,
  ) {
    super(message);
    this.name = "PlatformCoreError";
    this.code = code;
    this.details = details;
  }
}
