/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceCommerceConfig } from "./commerce-schema.js";

/** workspaceType → frozen commerce when manifest commerce.frozen (Wave F.b / PC-07). */
export const WORKSPACE_FROZEN_COMMERCE_BY_WORKSPACE_TYPE: Readonly<
  Record<string, WorkspaceCommerceConfig>
> = Object.freeze({
  "denali": Object.freeze({ paymentMode: "offline_receipt", gatewayProvider: null, currency: "IRR" }),
});

export function resolveFrozenWorkspaceCommerce(
  workspaceType: string
): WorkspaceCommerceConfig | null {
  const key = workspaceType.trim().toLowerCase();
  if (key.length === 0) {
    return null;
  }
  return WORKSPACE_FROZEN_COMMERCE_BY_WORKSPACE_TYPE[key] ?? null;
}

export function isWorkspaceCommerceFrozen(workspaceType: string): boolean {
  return resolveFrozenWorkspaceCommerce(workspaceType) !== null;
}
