/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { DENALI_SMOKE_TENANT_ID, DENALI_SMOKE_SUBDOMAIN } from "@app-tour/workspace-denali";
import { GUEST_CLUB_SMOKE_TENANT_ID, GUEST_CLUB_SMOKE_SUBDOMAIN } from "@app-tour/workspace-guest-club";
import { URBAN_SMOKE_TENANT_ID, URBAN_SMOKE_SUBDOMAIN } from "@app-tour/workspace-urban";
import { buildDenaliTenantWizardTemplatePayload } from "@app-tour/workspace-denali";
import { buildUrbanMinimalWizardTemplatePayload } from "@app-tour/workspace-urban";

export const WORKSPACE_DEV_WIZARD_TEMPLATE_BINDINGS = [
  {
    workspaceId: "denali",
    tenantIds: ["00000000-0000-4000-8000-000000000003"],
    buildPayload: buildDenaliTenantWizardTemplatePayload,
    minPublishedSteps: 2,
  },
  {
    workspaceId: "urban",
    tenantIds: ["00000000-0000-4000-8000-000000000004"],
    buildPayload: buildUrbanMinimalWizardTemplatePayload,
    minPublishedSteps: 2,
  },
] as const;

export const WORKSPACE_DEV_SMOKE_TENANT_BINDINGS = [
  {
    workspaceId: "denali",
    tenantId: DENALI_SMOKE_TENANT_ID,
    subdomain: DENALI_SMOKE_SUBDOMAIN,
  },
  {
    workspaceId: "guest-club",
    tenantId: GUEST_CLUB_SMOKE_TENANT_ID,
    subdomain: GUEST_CLUB_SMOKE_SUBDOMAIN,
  },
  {
    workspaceId: "urban",
    tenantId: URBAN_SMOKE_TENANT_ID,
    subdomain: URBAN_SMOKE_SUBDOMAIN,
  },
] as const;
