/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { isKnownEquipmentIconKey } from "@app-tour/workspace-denali/settings/equipment-icon-registry";

export const WORKSPACE_EQUIPMENT_ICON_KEY_VALIDATOR_BINDINGS = [
  {
    workspaceType: "denali",
    validateEquipmentIconKey: isKnownEquipmentIconKey,
  },
] as const;

export function resolveEquipmentIconKeyValidator(
  workspaceType: string
): ((value: string) => boolean) | undefined {
  const binding = WORKSPACE_EQUIPMENT_ICON_KEY_VALIDATOR_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.validateEquipmentIconKey;
}
