/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";
import { assertDenaliFrozenWizardTemplateFieldsPresent, normalizeDenaliWizardTemplatePayloadSteps } from "@app-tour/workspace-denali/host/wizard/template-invariants";

export const WORKSPACE_WIZARD_TEMPLATE_ENFORCEMENT_BINDINGS = [
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    assertFrozenFields: assertDenaliFrozenWizardTemplateFieldsPresent,
    normalizeSteps: normalizeDenaliWizardTemplatePayloadSteps,
  },
] as const;

export function resolveWizardTemplateEnforcementBinding(workspaceType: string) {
  return WORKSPACE_WIZARD_TEMPLATE_ENFORCEMENT_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
}
