/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { URBAN_SMOKE_TENANT_ID, URBAN_SMOKE_SUBDOMAIN } from "@app-tour/workspace-urban";
import { buildUrbanMinimalWizardTemplatePayload } from "@app-tour/workspace-urban";

export const WORKSPACE_DEV_WIZARD_TEMPLATE_BINDINGS = [
  {
    workspaceId: "urban",
    tenantIds: ["00000000-0000-4000-8000-000000000004"],
    buildPayload: buildUrbanMinimalWizardTemplatePayload,
    minPublishedSteps: 2,
  },
] as const;

export const WORKSPACE_DEV_SMOKE_TENANT_BINDINGS = [
  {
    workspaceId: "urban",
    tenantId: URBAN_SMOKE_TENANT_ID,
    subdomain: URBAN_SMOKE_SUBDOMAIN,
  },
] as const;
