/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export const WORKSPACE_WIZARD_TEMPLATE_PATH_ALIAS_BINDINGS = [
  {
    workspaceType: "starter",
    pathAliases: new Set(["title"]),
    aliasCatalogWorkspaceType: "denali",
  },
] as const;

export function resolveWizardTemplatePathAliasBinding(workspaceType: string) {
  return WORKSPACE_WIZARD_TEMPLATE_PATH_ALIAS_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
}
