/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export type WorkspaceWizardTemplatePathAliasBinding = {
  readonly workspaceType: string;
  readonly pathAliases: ReadonlySet<string>;
  readonly aliasCatalogWorkspaceType: string;
};

export const WORKSPACE_WIZARD_TEMPLATE_PATH_ALIAS_BINDINGS: readonly WorkspaceWizardTemplatePathAliasBinding[] =
  [];

export function resolveWizardTemplatePathAliasBinding(
  _workspaceType: string,
): WorkspaceWizardTemplatePathAliasBinding | undefined {
  return undefined;
}
