/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

export const WORKSPACE_WIZARD_TEMPLATE_PATH_ALIAS_BINDINGS = [] as const;

export function resolveWizardTemplatePathAliasBinding(_workspaceType: string) {
  return undefined;
}
