export const TENANT_RESOLVER_REDIS = Symbol("TENANT_RESOLVER_REDIS");

export const TENANT_HOST_CACHE_TTL_SECONDS = 60;

export const TENANT_CUSTOM_DOMAIN_CACHE_TTL_SECONDS = 300;

export const TENANT_CORS_ORIGIN_CACHE_TTL_SECONDS = 300;

export const TENANT_CORS_ORIGIN_MEMORY_TTL_MS = 60_000;

