/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceValidationPipelineStage } from "@app-tour/workspace-sdk";
import { validateWorkspaceBookingCapability } from "./capability-validators/workspace-booking-capability-validator.ts";
import { validateWorkspaceDifficultyFitnessCapability } from "./capability-validators/workspace-difficulty-fitness-capability-validator.ts";
import { validateWorkspaceEquipmentCapability } from "./capability-validators/workspace-equipment-capability-validator.ts";
import { validateWorkspaceFinanceCapability } from "./capability-validators/workspace-finance-capability-validator.ts";
import { validateWorkspaceItineraryCapability } from "./capability-validators/workspace-itinerary-capability-validator.ts";
import { validateWorkspacePricingCapability } from "./capability-validators/workspace-pricing-capability-validator.ts";
import { validateWorkspaceTransportCapability } from "./capability-validators/workspace-transport-capability-validator.ts";

export type CapabilityValidatorBinding = {
  readonly capabilityId: string;
  readonly run: WorkspaceValidationPipelineStage;
};

/**
 * Manifest-ordered capability validator registry.
 * Rows are codegen-stable; runner skips empty list (no error).
 * Validator bodies: apps/api/src/tours/capability-validators/* (MAT-002).
 */
export const WORKSPACE_CAPABILITY_VALIDATORS: readonly CapabilityValidatorBinding[] = [
  {
    capabilityId: "workspaceBooking",
    run: validateWorkspaceBookingCapability,
  },
  {
    capabilityId: "workspaceDifficultyFitness",
    run: validateWorkspaceDifficultyFitnessCapability,
  },
  {
    capabilityId: "workspaceEquipment",
    run: validateWorkspaceEquipmentCapability,
  },
  {
    capabilityId: "workspaceFinance",
    run: validateWorkspaceFinanceCapability,
  },
  {
    capabilityId: "workspaceItinerary",
    run: validateWorkspaceItineraryCapability,
  },
  {
    capabilityId: "workspacePricing",
    run: validateWorkspacePricingCapability,
  },
  {
    capabilityId: "workspaceTransport",
    run: validateWorkspaceTransportCapability,
  },
];
