/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspaceValidationPipelineStage } from "@app-tour/workspace-sdk";

export type CapabilityValidatorBinding = {
  readonly capabilityId: string;
  readonly run: WorkspaceValidationPipelineStage;
};

/**
 * Manifest-ordered capability validator registry.
 * Rows are codegen-stable; runner skips empty list (no error).
 * Individual validators wire in CW8-04 (booking publish) / CW7-03 (equipment ids).
 */
export const WORKSPACE_CAPABILITY_VALIDATORS: readonly CapabilityValidatorBinding[] = [
  // workspaceBooking — validator port deferred to CW8-04/CW7-03
  // workspaceEquipment — validator port deferred to CW8-04/CW7-03
  // workspaceFinance — validator port deferred to CW8-04/CW7-03
];
