/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { extractDenaliTourListProjection } from "@app-tour/workspace-denali/host/list/tour-list-projection";
import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";
import { extractUrbanTourListProjection } from "@app-tour/workspace-urban/host/list/tour-list-projection";
import { URBAN_WORKSPACE_TYPE } from "@app-tour/workspace-urban";

export const WORKSPACE_TOUR_LIST_PROJECTION_BINDINGS = [
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    extractTourListProjection: extractDenaliTourListProjection,
  },
  {
    workspaceType: URBAN_WORKSPACE_TYPE,
    extractTourListProjection: extractUrbanTourListProjection,
  },
] as const;
