/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { DENALI_WORKSPACE_TYPE, DENALI_MAX_PHOTO_UPLOAD_BYTES, isDenaliWizardDraftSessionId, isDenaliWizardDraftPhotoReadKeyAllowed, putDenaliWizardDraftPhoto, getDenaliTourPhotoSignedReadUrl, ensureMinioPhotoBucket, readMinioPhotoConfigFromEnv, createMinioPhotoClient } from "@app-tour/workspace-denali";

export const WORKSPACE_WIZARD_MEDIA_BINDINGS = [
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    maxUploadBytes: DENALI_MAX_PHOTO_UPLOAD_BYTES,
    isSessionId: isDenaliWizardDraftSessionId,
    isDraftReadKeyAllowed: isDenaliWizardDraftPhotoReadKeyAllowed,
    putDraftPhoto: putDenaliWizardDraftPhoto,
    getSignedReadUrl: getDenaliTourPhotoSignedReadUrl,
    ensurePhotoBucket: ensureMinioPhotoBucket,
    readPhotoConfigFromEnv: readMinioPhotoConfigFromEnv,
    createPhotoClient: createMinioPhotoClient,
  },
] as const;
