/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import type { WorkspacePolicyValidator } from "@app-tour/workspace-sdk";
import { createTourWorkspacePolicyValidator as policy_cert_workspace_policy } from "@app-tour/workspace-policy-cert/host/policy/tour-policy";

export type WorkspacePolicyValidatorBinding = {
  readonly workspaceType: string;
  readonly createValidator: () => WorkspacePolicyValidator;
};

/** Manifest-declared workspace policy validators — one factory per workspace manifest. */
export const WORKSPACE_POLICY_VALIDATOR_BINDINGS: readonly WorkspacePolicyValidatorBinding[] = [
  {
    workspaceType: "policy-cert",
    createValidator: policy_cert_workspace_policy,
  },
] as const;

export function resolveWorkspacePolicyValidator(
  workspaceType: string
): WorkspacePolicyValidator | undefined {
  const binding = WORKSPACE_POLICY_VALIDATOR_BINDINGS.find(
    (entry) => entry.workspaceType === workspaceType
  );
  return binding?.createValidator();
}
