/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { URBAN_WORKSPACE_TYPE } from "@app-tour/workspace-urban";
import { mergeUrbanCanonicalPatchData, urbanTourPatchRequiresOwner, URBAN_TOUR_PUBLISH_FIELDS_OWNER_SURFACE } from "@app-tour/workspace-urban/tours";

export const WORKSPACE_TOUR_WRITE_BINDINGS = [
  {
    workspaceType: URBAN_WORKSPACE_TYPE,
    mergeCanonicalPatch: mergeUrbanCanonicalPatchData,
    publishFieldGate: urbanTourPatchRequiresOwner,
    publishOwnerSurface: URBAN_TOUR_PUBLISH_FIELDS_OWNER_SURFACE,
  },
] as const;
