/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";
import { mergeDenaliCanonicalPatchData, denaliTourPatchRequiresOwner, DENALI_TOUR_PUBLISH_FIELDS_OWNER_SURFACE } from "@app-tour/workspace-denali/host/tours";
import { FINANCE_WS3_WORKSPACE_TYPE } from "@app-tour/workspace-finance-ws3";
import { mergeFinanceWs3CanonicalPatchData, financeWs3TourPatchRequiresOwner, FINANCE_WS3_TOUR_PUBLISH_FIELDS_OWNER_SURFACE } from "@app-tour/workspace-finance-ws3/host/tours";
import { FINANCE_WS4_WORKSPACE_TYPE } from "@app-tour/workspace-finance-ws4";
import { mergeFinanceWs4CanonicalPatchData, financeWs4TourPatchRequiresOwner, FINANCE_WS4_TOUR_PUBLISH_FIELDS_OWNER_SURFACE } from "@app-tour/workspace-finance-ws4/host/tours";
import { FINANCE_WS5_WORKSPACE_TYPE } from "@app-tour/workspace-finance-ws5";
import { mergeFinanceWs5CanonicalPatchData, financeWs5TourPatchRequiresOwner, FINANCE_WS5_TOUR_PUBLISH_FIELDS_OWNER_SURFACE } from "@app-tour/workspace-finance-ws5/host/tours";
import { FINANCE_WS6_WORKSPACE_TYPE } from "@app-tour/workspace-finance-ws6";
import { mergeFinanceWs6CanonicalPatchData, financeWs6TourPatchRequiresOwner, FINANCE_WS6_TOUR_PUBLISH_FIELDS_OWNER_SURFACE } from "@app-tour/workspace-finance-ws6/host/tours";
import { URBAN_WORKSPACE_TYPE } from "@app-tour/workspace-urban";
import { mergeUrbanCanonicalPatchData, urbanTourPatchRequiresOwner, URBAN_TOUR_PUBLISH_FIELDS_OWNER_SURFACE } from "@app-tour/workspace-urban/host/tours";
import { assertWorkspaceOwner } from "@app-tour/workspace-urban/host/http";

export const WORKSPACE_TOUR_WRITE_BINDINGS = [
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    mergeCanonicalPatch: mergeDenaliCanonicalPatchData,
    publishFieldGate: denaliTourPatchRequiresOwner,
    publishOwnerSurface: DENALI_TOUR_PUBLISH_FIELDS_OWNER_SURFACE,
    forbidOperatorMemberTourPatch: true as const,
    starterCreateBridgeOperatorTenantId: "00000000-0000-4000-8000-000000000014" as const,
  },
  {
    workspaceType: FINANCE_WS3_WORKSPACE_TYPE,
    mergeCanonicalPatch: mergeFinanceWs3CanonicalPatchData,
    publishFieldGate: financeWs3TourPatchRequiresOwner,
    publishOwnerSurface: FINANCE_WS3_TOUR_PUBLISH_FIELDS_OWNER_SURFACE,
  },
  {
    workspaceType: FINANCE_WS4_WORKSPACE_TYPE,
    mergeCanonicalPatch: mergeFinanceWs4CanonicalPatchData,
    publishFieldGate: financeWs4TourPatchRequiresOwner,
    publishOwnerSurface: FINANCE_WS4_TOUR_PUBLISH_FIELDS_OWNER_SURFACE,
  },
  {
    workspaceType: FINANCE_WS5_WORKSPACE_TYPE,
    mergeCanonicalPatch: mergeFinanceWs5CanonicalPatchData,
    publishFieldGate: financeWs5TourPatchRequiresOwner,
    publishOwnerSurface: FINANCE_WS5_TOUR_PUBLISH_FIELDS_OWNER_SURFACE,
  },
  {
    workspaceType: FINANCE_WS6_WORKSPACE_TYPE,
    mergeCanonicalPatch: mergeFinanceWs6CanonicalPatchData,
    publishFieldGate: financeWs6TourPatchRequiresOwner,
    publishOwnerSurface: FINANCE_WS6_TOUR_PUBLISH_FIELDS_OWNER_SURFACE,
  },
  {
    workspaceType: URBAN_WORKSPACE_TYPE,
    mergeCanonicalPatch: mergeUrbanCanonicalPatchData,
    publishFieldGate: urbanTourPatchRequiresOwner,
    publishOwnerSurface: URBAN_TOUR_PUBLISH_FIELDS_OWNER_SURFACE,
    assertPublishFieldOwner: assertWorkspaceOwner,
  },
] as const;
