/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";
import { denaliWizardRulesSurface as denali_wizard_rules } from "@app-tour/workspace-denali/host/wizard/wizard-rules-surface";

export type WorkspaceWizardRulesModuleSync = (typeof WORKSPACE_WIZARD_RULES_BINDINGS)[number]["rulesModule"];

export const WORKSPACE_WIZARD_RULES_BINDINGS = [
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    rulesModule: Object.freeze({
      evaluateFormFieldRule: denali_wizard_rules.evaluateFormFieldRule,
      applyDenaliInvariantState: denali_wizard_rules.applyDenaliInvariantState,
      resolveDenaliRuleSetFromTemplate: denali_wizard_rules.resolveDenaliRuleSetFromTemplate,
      buildDefaultForm: denali_wizard_rules.buildDenaliTourCreateDefaultValues,
      readCanonicalBasics: denali_wizard_rules.readDenaliCanonicalBasics,
      canonicalToFormPathMap: denali_wizard_rules.canonicalToFormPathMap,
      tourKindValues: denali_wizard_rules.tourKindValues,
    }),
  },
] as const;

const rulesByWorkspaceType = Object.freeze(
  Object.fromEntries(
    WORKSPACE_WIZARD_RULES_BINDINGS.map((binding) => [
      binding.workspaceType as string,
      binding.rulesModule,
    ])
  )
) as Readonly<Record<string, WorkspaceWizardRulesModuleSync>>;

export function getWizardRulesModuleSyncForWorkspace(
  workspaceType: string
): WorkspaceWizardRulesModuleSync {
  const rules = rulesByWorkspaceType[workspaceType];
  if (rules === undefined) {
    throw new Error(`No wizard rules module for workspace: ${workspaceType}`);
  }
  return rules;
}
