#!/usr/bin/env bash
# Render /etc/caddy/caddy.env from VPS app env ports (P10-1-N-001)
set -euo pipefail

ENV_DIR="${ENV_DIR:-/etc/app-tour}"
OUT="${CADDY_ENV_FILE:-/etc/caddy/caddy.env}"
PLATFORM_ROOT_DOMAIN="${PLATFORM_ROOT_DOMAIN:-}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/ports.sh
source "${SCRIPT_DIR}/lib/ports.sh"
collect_app_ports "$ENV_DIR"

API_PORT="${API_PORT:-3001}"
WEB_PORT="${WEB_PORT:-3000}"
MARKETING_PORT="${MARKETING_PORT:-3002}"
PORTAL_PORT="${PORTAL_PORT:-3003}"

if [[ -z "$PLATFORM_ROOT_DOMAIN" ]]; then
  PLATFORM_ROOT_DOMAIN="$(read_env_var "${ENV_DIR}/web.env" PLATFORM_ROOT_DOMAIN 2>/dev/null || true)"
fi
if [[ -z "$PLATFORM_ROOT_DOMAIN" ]]; then
  PLATFORM_ROOT_DOMAIN="$(read_env_var "${ENV_DIR}/api.env" PLATFORM_ROOT_DOMAIN 2>/dev/null || true)"
fi
PLATFORM_ROOT_DOMAIN="${PLATFORM_ROOT_DOMAIN:-staging.example.com}"

mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
# Generated by render-caddy-env.sh — do not edit by hand
PLATFORM_ROOT_DOMAIN=${PLATFORM_ROOT_DOMAIN}
API_PORT=${API_PORT}
WEB_PORT=${WEB_PORT}
MARKETING_PORT=${MARKETING_PORT}
PORTAL_PORT=${PORTAL_PORT}
CADDY_ACME_EMAIL=${CADDY_ACME_EMAIL:-ops@example.com}
EOF

chmod 640 "$OUT"
echo "[caddy-env] wrote $OUT (root=${PLATFORM_ROOT_DOMAIN} web=${WEB_PORT} mkt=${MARKETING_PORT} ptl=${PORTAL_PORT})"
