/**
 * Compatibility re-export — SoT: `@app-tour/finance-core` (Phase 1.25).
 */
export type {
  ApproveManualReceiptAtomicInput,
  ApproveManualReceiptAtomicResult,
  CancelPendingManualPaymentAtomicInput,
  CancelPendingManualPaymentAtomicResult,
  CreatePaymentInput,
  CreateReceiptInput,
  CreateRefundInput,
  FinanceLedgerOutboxRow,
  FinanceOpenPaymentRow,
  FinancePaymentRow,
  FinancePrepaymentListRow,
  FinanceReceiptRow,
  FinanceRefundRow,
  FinanceRepositoryPort,
  FinanceSummaryRow,
  FinanceTourPaymentAggregateRow,
  ListFinanceExceptionSourcesResult,
  ListOutstandingBalanceCandidatesResult,
  ListPendingReceiptsPage,
  ListPendingReceiptsQuery,
  ListRefundsPageQuery,
  ListRefundsPageResult,
  OutstandingBalanceCandidateRow,
  PrepaymentBookingSyncDegradedRow,
  RecordPrepaymentAtomicInput,
  RecordPrepaymentAtomicResult,
  RegistrationInvoiceFacts,
  SumCompletedRefundsQuery,
  TransitionRefundStatusInput,
  UpdateReceiptReviewInput,
} from "@app-tour/finance-core";
