/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { BOOKING_WS2_WORKSPACE_TYPE } from "@app-tour/workspace-booking-ws2";
import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";

export type BookingCreateCapabilityMode = "none" | "create-pipeline";
export type BookingValidationCapabilityMode = "none" | "base-shape";
export type BookingCapacityCapabilityMode = "none" | "booking-owned";
export type BookingApprovalCapabilityMode = "none" | "host-lifecycle";
export type BookingEventReactionCapabilityMode = "none" | "in-process";

export type BookingGradedCapability<TMode extends string> = {
  readonly enabled: boolean;
  readonly mode: TMode;
};

export type BookingWorkspaceCapabilities = {
  readonly enabled: true;
  readonly publicCreate: BookingGradedCapability<BookingCreateCapabilityMode>;
  readonly operatorCreate: BookingGradedCapability<BookingCreateCapabilityMode>;
  readonly validation: BookingGradedCapability<BookingValidationCapabilityMode>;
  readonly capacity: BookingGradedCapability<BookingCapacityCapabilityMode>;
  readonly approval: BookingGradedCapability<BookingApprovalCapabilityMode>;
  readonly eventReaction: BookingGradedCapability<BookingEventReactionCapabilityMode>;
};

/**
 * Capability matrix — product gate (`supported`) vs graded booking depth.
 * Graded entries are enabled+mode only (API runtime; ops UI is opsManifest → web).
 */
export const WORKSPACE_BOOKING_CAPABILITIES = {
  [BOOKING_WS2_WORKSPACE_TYPE]: {
    enabled: true as const,
    publicCreate: {
      enabled: true as const,
      mode: "create-pipeline" as const,
    },
    operatorCreate: {
      enabled: true as const,
      mode: "create-pipeline" as const,
    },
    validation: {
      enabled: true as const,
      mode: "base-shape" as const,
    },
    capacity: {
      enabled: true as const,
      mode: "booking-owned" as const,
    },
    approval: {
      enabled: true as const,
      mode: "host-lifecycle" as const,
    },
    eventReaction: {
      enabled: true as const,
      mode: "in-process" as const,
    },
  },
  [DENALI_WORKSPACE_TYPE]: {
    enabled: true as const,
    publicCreate: {
      enabled: true as const,
      mode: "create-pipeline" as const,
    },
    operatorCreate: {
      enabled: true as const,
      mode: "create-pipeline" as const,
    },
    validation: {
      enabled: true as const,
      mode: "base-shape" as const,
    },
    capacity: {
      enabled: true as const,
      mode: "booking-owned" as const,
    },
    approval: {
      enabled: true as const,
      mode: "host-lifecycle" as const,
    },
    eventReaction: {
      enabled: true as const,
      mode: "in-process" as const,
    },
  },
} as const satisfies Record<string, BookingWorkspaceCapabilities>;

export function getBookingWorkspaceCapabilities(
  workspaceType: string
): BookingWorkspaceCapabilities | null {
  const key = workspaceType.trim();
  if (key.length === 0) {
    return null;
  }
  const caps = (WORKSPACE_BOOKING_CAPABILITIES as Record<string, BookingWorkspaceCapabilities>)[key];
  return caps ?? null;
}
