/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { BookingWs2EventReactionAdapter as booking_ws2_BookingEventReaction } from "@app-tour/workspace-booking-ws2/host/booking";

import { DenaliBookingEventReactionAdapter as denali_BookingEventReaction } from "@app-tour/workspace-denali/host/booking";

export const WORKSPACE_BOOKING_EVENT_REACTION_BINDINGS = {
  "booking-ws2": {
    requiresHostIo: false as const,
    create: () => new booking_ws2_BookingEventReaction(),
  },
  "denali": {
    requiresHostIo: false as const,
    create: () => new denali_BookingEventReaction(),
  },
} as const;

export function isBookingEventReactionBindingRegistered(workspaceType: string): boolean {
  return workspaceType.trim().toLowerCase() in WORKSPACE_BOOKING_EVENT_REACTION_BINDINGS;
}
