/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { BOOKING_WS2_WORKSPACE_TYPE } from "@app-tour/workspace-booking-ws2";
import { DENALI_WORKSPACE_TYPE } from "@app-tour/workspace-denali";

export const WORKSPACE_BOOKING_BINDINGS = [
  {
    workspaceType: BOOKING_WS2_WORKSPACE_TYPE,
    defaultModuleEnabledWhenUnset: true as const,
  },
  {
    workspaceType: DENALI_WORKSPACE_TYPE,
    defaultModuleEnabledWhenUnset: true as const,
  },
] as const;

const supportedWorkspaceTypes = new Set(
  WORKSPACE_BOOKING_BINDINGS.map((binding) => binding.workspaceType as string)
);

const defaultEnabledWhenUnset = new Set(
  WORKSPACE_BOOKING_BINDINGS.filter(
    (binding) => "defaultModuleEnabledWhenUnset" in binding && binding.defaultModuleEnabledWhenUnset === true
  ).map((binding) => binding.workspaceType as string)
);

export function isBookingSupportedWorkspace(workspaceType: string): boolean {
  return supportedWorkspaceTypes.has(workspaceType);
}

export function defaultBookingEnabledWhenModulesUnset(workspaceType: string): boolean {
  return defaultEnabledWhenUnset.has(workspaceType);
}
