/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { isDenaliOwnerRequiredError, DENALI_OWNER_REQUIRED } from "@app-tour/workspace-denali/host/http";
import { isDenaliRegistrationDuplicateError, DENALI_REGISTRATION_DUPLICATE } from "@app-tour/workspace-denali/host/http";
import { isDenaliRegistrationInvalidError, DENALI_REGISTRATION_INVALID } from "@app-tour/workspace-denali/host/http";
import { isDenaliRegistrationNotAmendableError, DENALI_REGISTRATION_NOT_AMENDABLE } from "@app-tour/workspace-denali/host/http";
import { isDenaliRegistrationNotFoundError, DENALI_REGISTRATION_NOT_FOUND } from "@app-tour/workspace-denali/host/http";
import { isHarborRegistrationDuplicateError, HARBOR_REGISTRATION_DUPLICATE } from "@app-tour/workspace-harbor/host/http";
import { isHarborWorkspaceRequiredError, HARBOR_WORKSPACE_REQUIRED } from "@app-tour/workspace-harbor/host/http";
import { isUrbanOwnerRequiredError, URBAN_OWNER_REQUIRED } from "@app-tour/workspace-urban/host/http";
import { isUrbanRegistrationClosedError, URBAN_REGISTRATION_CLOSED } from "@app-tour/workspace-urban/host/http";
import { isUrbanRegistrationDuplicateError, URBAN_REGISTRATION_DUPLICATE } from "@app-tour/workspace-urban/host/http";
import { isUrbanWorkspaceRequiredError, URBAN_WORKSPACE_REQUIRED } from "@app-tour/workspace-urban/host/http";

type WorkspaceHttpErrorBinding = {
  readonly workspaceId: string;
  readonly status: number;
  readonly isError: (error: unknown) => boolean;
  readonly code: string;
};

export const WORKSPACE_HTTP_ERROR_RESPONSE_BINDINGS: readonly WorkspaceHttpErrorBinding[] = [
  {
    workspaceId: "denali",
    status: 403,
    isError: isDenaliOwnerRequiredError,
    code: DENALI_OWNER_REQUIRED,
  },
  {
    workspaceId: "denali",
    status: 409,
    isError: isDenaliRegistrationDuplicateError,
    code: DENALI_REGISTRATION_DUPLICATE,
  },
  {
    workspaceId: "denali",
    status: 409,
    isError: isDenaliRegistrationNotAmendableError,
    code: DENALI_REGISTRATION_NOT_AMENDABLE,
  },
  {
    workspaceId: "denali",
    status: 400,
    isError: isDenaliRegistrationInvalidError,
    code: DENALI_REGISTRATION_INVALID,
  },
  {
    workspaceId: "denali",
    status: 404,
    isError: isDenaliRegistrationNotFoundError,
    code: DENALI_REGISTRATION_NOT_FOUND,
  },
  {
    workspaceId: "harbor",
    status: 409,
    isError: isHarborRegistrationDuplicateError,
    code: HARBOR_REGISTRATION_DUPLICATE,
  },
  {
    workspaceId: "harbor",
    status: 404,
    isError: isHarborWorkspaceRequiredError,
    code: HARBOR_WORKSPACE_REQUIRED,
  },
  {
    workspaceId: "urban",
    status: 403,
    isError: isUrbanOwnerRequiredError,
    code: URBAN_OWNER_REQUIRED,
  },
  {
    workspaceId: "urban",
    status: 404,
    isError: isUrbanWorkspaceRequiredError,
    code: URBAN_WORKSPACE_REQUIRED,
  },
  {
    workspaceId: "urban",
    status: 409,
    isError: isUrbanRegistrationDuplicateError,
    code: URBAN_REGISTRATION_DUPLICATE,
  },
  {
    workspaceId: "urban",
    status: 403,
    isError: isUrbanRegistrationClosedError,
    code: URBAN_REGISTRATION_CLOSED,
  },
];

export const WORKSPACE_HTTP_ERROR_CODE_STATUS = {
  [DENALI_OWNER_REQUIRED]: 403,
  [DENALI_REGISTRATION_DUPLICATE]: 409,
  [DENALI_REGISTRATION_NOT_AMENDABLE]: 409,
  [DENALI_REGISTRATION_INVALID]: 400,
  [DENALI_REGISTRATION_NOT_FOUND]: 404,
  [HARBOR_REGISTRATION_DUPLICATE]: 409,
  [HARBOR_WORKSPACE_REQUIRED]: 404,
  [URBAN_OWNER_REQUIRED]: 403,
  [URBAN_WORKSPACE_REQUIRED]: 404,
  [URBAN_REGISTRATION_DUPLICATE]: 409,
  [URBAN_REGISTRATION_CLOSED]: 403,
} as const satisfies Record<string, number>;

export function resolveWorkspaceHttpErrorCodeStatus(code: string): number | undefined {
  return WORKSPACE_HTTP_ERROR_CODE_STATUS[code as keyof typeof WORKSPACE_HTTP_ERROR_CODE_STATUS];
}
