/**
 * AUTO-GENERATED by scripts/generate-workspace-registry.mjs — DO NOT EDIT.
 * Source: workspace.manifest.json per workspace package.
 * Regenerate: pnpm run generate:workspace-registry
 */

import { isDenaliRegistrationDuplicateError, DENALI_REGISTRATION_DUPLICATE } from "@app-tour/workspace-denali/http";
import { isUrbanOwnerRequiredError, URBAN_OWNER_REQUIRED } from "@app-tour/workspace-urban/http";
import { isUrbanRegistrationClosedError, URBAN_REGISTRATION_CLOSED } from "@app-tour/workspace-urban/http";
import { isUrbanRegistrationDuplicateError, URBAN_REGISTRATION_DUPLICATE } from "@app-tour/workspace-urban/http";
import { isUrbanWorkspaceRequiredError, URBAN_WORKSPACE_REQUIRED } from "@app-tour/workspace-urban/http";

type WorkspaceHttpErrorBinding = {
  readonly workspaceId: string;
  readonly status: number;
  readonly isError: (error: unknown) => boolean;
  readonly code: string;
};

export const WORKSPACE_HTTP_ERROR_RESPONSE_BINDINGS: readonly WorkspaceHttpErrorBinding[] = [
  {
    workspaceId: "denali",
    status: 409,
    isError: isDenaliRegistrationDuplicateError,
    code: DENALI_REGISTRATION_DUPLICATE,
  },
  {
    workspaceId: "urban",
    status: 403,
    isError: isUrbanOwnerRequiredError,
    code: URBAN_OWNER_REQUIRED,
  },
  {
    workspaceId: "urban",
    status: 404,
    isError: isUrbanWorkspaceRequiredError,
    code: URBAN_WORKSPACE_REQUIRED,
  },
  {
    workspaceId: "urban",
    status: 409,
    isError: isUrbanRegistrationDuplicateError,
    code: URBAN_REGISTRATION_DUPLICATE,
  },
  {
    workspaceId: "urban",
    status: 403,
    isError: isUrbanRegistrationClosedError,
    code: URBAN_REGISTRATION_CLOSED,
  },
];

export const WORKSPACE_HTTP_ERROR_CODE_STATUS = {
  [DENALI_REGISTRATION_DUPLICATE]: 409,
  [URBAN_OWNER_REQUIRED]: 403,
  [URBAN_WORKSPACE_REQUIRED]: 404,
  [URBAN_REGISTRATION_DUPLICATE]: 409,
  [URBAN_REGISTRATION_CLOSED]: 403,
} as const satisfies Record<string, number>;

export function resolveWorkspaceHttpErrorCodeStatus(code: string): number | undefined {
  return WORKSPACE_HTTP_ERROR_CODE_STATUS[code as keyof typeof WORKSPACE_HTTP_ERROR_CODE_STATUS];
}
