export const DENALI_MODERN_SETTINGS_OVERLAY_STORAGE_PATHS = [
  "approximateReturnTime",
  "campPoint",
  "capacityMax",
  "capacityMin",
  "category",
  "duration",
  "customServiceLabels",
  "destinationId",
  "endDateTime",
  "endPoint",
  "gatheringPoints",
  "leaderUserIds",
  "localGuideName",
  "metrics.elevationGain",
  "overview.nonAttendanceDetails",
  "overview.peakHeight",
  "participants.fitnessLevel",
  "participants.fitnessPrerequisiteText",
  "participants.gearItems",
  "participants.maximumAge",
  "participants.minRequiredPeaks",
  "participants.minimumAge",
  "participants.nationalIdRequired",
  "participants.sportsInsuranceRequired",
  "photos",
  "policies.cancellationDeadlineHours",
  "policies.cancellationPenaltyPercentage",
  "policies.policiesText",
  "pricing.basePricePerPerson",
  "pricing.includesTourInsurance",
  "pricing.requiresPayment",
  "program.difficultyLevel",
  "program.hikingGoHours",
  "program.hikingHoursApprox",
  "program.hikingReturnHours",
  "program.itinerary",
  "program.longDescription",
  "program.shortDescription",
  "program.themeIds",
  "requiresLocalGuide",
  "requiresManualAdminApproval",
  "socialMediaLink",
  "startDateTime",
  "startPoint",
  "summitPoint",
  "title",
  "transport.adminCapacityApproval",
  "transport.allowPersonalCar",
  "transport.dongAmount",
  "transport.mode",
  "transport.transportCost",
] as const;

export function listDenaliSettingsOverlayStoragePaths(): readonly string[] {
  return DENALI_MODERN_SETTINGS_OVERLAY_STORAGE_PATHS;
}
